/* Campusly AI core — direct AI, scan, document export, image generation. */
(function(){
  const escv=v=>typeof esc==='function'?esc(v):String(v??'');
  const ctx=()=>{const p=state.profile||{};const tasks=(state.tasks||[]).filter(x=>!x.done).slice(0,12).map(x=>`${x.title}${x.deadline?` (${x.deadline})`:''}${x.priority?` [${x.priority}]`:''}`).join('; ')||'tidak ada';const classes=(state.schedule||[]).slice(0,12).map(x=>`${x.name} ${x.day||''} ${x.start||''}-${x.end||''}`).join('; ')||'tidak ada';const courses=(state.courses||[]).map(x=>x.name).slice(0,12).join(', ')||'tidak ada';return `Nama: ${p.preferredName||p.name||'mahasiswa'}; Universitas: ${p.university||'belum diisi'}; Jurusan: ${p.major||'belum diisi'}; Semester: ${p.semester||'belum diisi'}; GPA: ${p.gpa||'belum ada'}; Target GPA: ${p.targetGpa||'belum ada'}; Tugas aktif: ${tasks}; Jadwal: ${classes}; Mata kuliah: ${courses}.`;};
  const history=()=> (state.aiMessages||[]).slice(-14).filter(m=>m&&m.text).map(m=>({role:m.role==='assistant'?'assistant':'user',content:String(m.text)}));
  const push=(role,text)=>{state.aiMessages=state.aiMessages||[];state.aiMessages.push({role,text});save();};
  async function post(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||`AI gagal (HTTP ${r.status})`);return d;}
  function busy(on){const b=document.getElementById('aiSend');if(b)b.disabled=on;const s=document.getElementById('aiStatus');if(s)s.textContent=on?'Lagi mikir…':'';}
  function scroll(){requestAnimationFrame(()=>{const c=document.querySelector('.chat');if(c)c.scrollTop=c.scrollHeight;});}
  window.askAI=async function(q){const text=String(q||'').trim();if(!text)return;push('user',text);render();busy(true);try{const d=await post('/api/ai',{messages:history(),context:ctx()});push('assistant',d.text||'Gue belum dapet jawaban.');}catch(e){push('assistant',`⚠️ ${e.message||'AI gagal terhubung.'}\n\nCoba tekan "Kirim lagi" kalau koneksi/provider lagi bermasalah.`);window.__aiRetry=text;}finally{busy(false);render();scroll();}};
  window.sendAI=async function(){const el=document.getElementById('aiInput');const q=el?.value.trim();if(!q)return;el.value='';await askAI(q);};window.retryAI=()=>window.__aiRetry?askAI(window.__aiRetry):null;window.clearAI=()=>{state.aiMessages=[];window.__aiRetry='';window.__aiLastImage='';save();render();};
  window.scanAI=()=>{const i=document.getElementById('aiScan');if(i)i.click();};
  window.handleScanAI=async function(input){const file=input?.files?.[0];if(!file)return;if(file.size>8*1024*1024){toast('Foto maksimal 8 MB.');input.value='';return;}const reader=new FileReader();reader.onload=async()=>{push('user','📷 Scan soal');render();busy(true);try{const d=await post('/api/ai/vision',{image:reader.result,question:'Baca soal pada gambar. Berikan jawaban yang benar dan jelaskan langkah pengerjaannya dengan bahasa yang mudah dipahami mahasiswa.',context:ctx()});push('assistant',d.text||'Gue belum bisa membaca soal ini.');}catch(e){push('assistant',`⚠️ Scan gagal: ${e.message||'coba foto yang lebih jelas.'}`);}finally{busy(false);render();scroll();input.value='';}};reader.readAsDataURL(file);};
  window.generateAIImage=async function(){const el=document.getElementById('aiInput');const prompt=el?.value.trim()||window.prompt('Mau bikin gambar apa?','Ilustrasi akademik modern tentang mahasiswa belajar di perpustakaan');if(!prompt)return;push('user','🎨 '+prompt);render();busy(true);try{const d=await post('/api/ai/image',{prompt});window.__aiLastImage=d.image||'';push('assistant','🎨 Gambar berhasil dibuat.');}catch(e){push('assistant',`⚠️ Generate gambar gagal: ${e.message||'coba lagi.'}`);}finally{busy(false);render();scroll();}};
  async function exportLast(type){const msgs=state.aiMessages||[],last=[...msgs].reverse().find(m=>m.role==='assistant'&&m.text&&!String(m.text).startsWith('⚠️'));if(!last){toast('Belum ada jawaban AI yang bisa diekspor.');return;}try{toast(type==='pdf'?'Bikin PDF…':'Bikin PPT…');const r=await fetch(`/api/export/${type}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:last.text,title:type==='pdf'?'Campusly-Makalah':'Campusly-Presentasi'})});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||`Export gagal (HTTP ${r.status})`);}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=type==='pdf'?'campusly-makalah.pdf':'campusly-presentasi.pptx';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);toast(type==='pdf'?'PDF siap.':'PPT siap.');}catch(e){toast(e.message||'Export gagal.');}}
  window.exportAIPdf=()=>exportLast('pdf');window.exportAIPpt=()=>exportLast('ppt');
  window.ai=function(){const msgs=state.aiMessages||[];const bubbles=msgs.length?msgs.map((m,i)=>`<div class="bubble ${m.role==='user'?'me':''}">${escv(m.text).replace(/\n/g,'<br>')}${m.role==='assistant'&&i===msgs.length-1&&window.__aiLastImage?`<div style="margin-top:10px"><img src="${window.__aiLastImage}" alt="Gambar hasil AI" style="width:100%;border-radius:16px;display:block"><a class="btn small" style="display:inline-block;margin-top:8px" href="${window.__aiLastImage}" download="campusly-ai.png">Simpan gambar</a></div>`:''}</div>`).join(''):`<div class="bubble">Halo 👋 Gue Campusly AI. Tanya apa aja soal kuliah, minta bantu tugas, scan soal, bikin makalah, atau bikin materi.</div>`;return `${header('ASSISTANT','Campusly AI','Langsung tanya. Nggak ada prompt aneh-aneh.')}
<div class="card ai-card"><div class="chat" style="max-height:52vh;overflow:auto">${bubbles}</div><div class="ai-box"><textarea id="aiInput" placeholder="Tulis apa aja…" onkeydown="if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();sendAI()}"></textarea><button id="aiSend" class="btn primary" onclick="sendAI()">Kirim</button></div><div id="aiStatus" class="muted" style="min-height:20px;margin-top:6px"></div><div class="actions" style="margin-top:8px;flex-wrap:wrap"><button class="btn small" onclick="scanAI()">📷 Scan soal</button><button class="btn small" onclick="askAI('Bantu gue bikin makalah. Tanyain cuma detail yang memang perlu.')">📄 Buat makalah</button><button class="btn small" onclick="askAI('Buatkan study plan berdasarkan data Campusly gue.')">📚 Study plan</button><button class="btn small" onclick="askAI('Analisis GPA gue berdasarkan data Campusly yang tersedia.')">📊 Analisis GPA</button><button class="btn small" onclick="exportAIPdf()">⬇️ PDF</button><button class="btn small" onclick="exportAIPpt()">⬇️ PPT</button><button class="btn small" onclick="generateAIImage()">🎨 Gambar</button><button class="btn small" onclick="clearAI()">Hapus chat</button>${window.__aiRetry?'<button class="btn small" onclick="retryAI()">Kirim lagi</button>':''}</div><input id="aiScan" type="file" accept="image/png,image/jpeg,image/webp" capture="environment" style="display:none" onchange="handleScanAI(this)"></div>`;};
})();
