const KEY='campusly_state_v1';
const defaults={profile:{name:'Rizky',preferredName:'Rizky',university:'',major:'',semester:1,gpa:0,targetGpa:3.75,credits:0,totalCredits:144},tasks:[],notes:[],schedule:[],calendarEvents:[],finance:[],budgets:[],focus:{seconds:1500,running:false,session:0},courses:[],gpaRecords:[],thesisProjects:[],documents:[],notifications:[],reminders:[],analytics:{focusSeconds:0,focusHistory:[]},settings:{theme:'dark',accent:'purple'},onboarding:{complete:true}};
const ICON={home:'⌂',tasks:'✓',notes:'▤',schedule:'◫',calendar:'□',semester:'◈',gpa:'∑',finance:'◌',focus:'◷',analytics:'▥',thesis:'▱',documents:'▣',tools:'✦',ai:'✧',notifications:'♢',reminders:'⏰',settings:'⚙'};
const FEATURES=[['home','Home','Ringkasan kuliah'],['tasks','Tasks','Tugas & deadline'],['notes','Notes','Catatan kuliah'],['schedule','Jadwal','Jadwal kelas'],['calendar','Calendar','Agenda'],['semester','Semester','Mata kuliah'],['gpa','GPA','Kalkulator IPK'],['finance','Finance','Keuangan'],['focus','Focus','Pomodoro'],['analytics','Analytics','Progress'],['thesis','Thesis','Proyek skripsi'],['documents','Documents','Baca file'],['tools','Academic Tools','Tools akademik'],['ai','Campusly AI','Asisten AI'],['notifications','Notifications','Pusat notifikasi'],['reminders','Reminders','Pengingat'],['settings','Settings','Profil & preferensi']];
let state=load();let route=location.hash.slice(1)||'home';let timerId=null;
function clone(x){return JSON.parse(JSON.stringify(x))}function merge(a,b){return {...a,...b}}function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return {...clone(defaults),...x,profile:{...defaults.profile,...x.profile},settings:{...defaults.settings,...x.settings},focus:{...defaults.focus,...x.focus},analytics:{...defaults.analytics,...x.analytics}}}catch{return clone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function money(n){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0)}function go(r){route=r;location.hash=r;closeOverlay();render()}window.addEventListener('hashchange',()=>{route=location.hash.slice(1)||'home';render()});
function toast(msg){const d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function shell(content){const p=state.profile;const mobile=[['home','Home'],['tasks','Tasks'],['schedule','Jadwal'],['ai','AI'],['menu','Menu']];return `<div class="app"><aside class="sidebar"><div class="brand"><span class="logo">C</span>Campusly</div><nav class="side-nav">${FEATURES.map(([r,l])=>`<button class="${route===r?'active':''}" onclick="go('${r}')"><span class="ico">${ICON[r]}</span>${l}</button>`).join('')}</nav></aside><main class="main"><header class="topbar"><div class="search">⌕<input id="globalSearch" placeholder="Cari apa aja..." autocomplete="off" onkeydown="if(event.key==='Enter')searchApp(this.value)"></div><div class="avatar">${esc((p.preferredName||p.name||'R').slice(0,1).toUpperCase())}</div></header><section class="content">${content}</section></main><nav class="mobile-nav">${mobile.map(([r,l])=>`<button class="${(route===r||(r==='menu'&&FEATURES.some(x=>x[0]===route&&route!=='home'&&route!=='tasks'&&route!=='schedule'&&route!=='ai'))) ?'active':''}" onclick="${r==='menu'?'openMenu()':`go('${r}')`}"><span class="micon">${r==='menu'?'☷':ICON[r]}</span>${l}</button>`).join('')}</nav></div>`}
function header(k,t,s,action=''){return `<div class="eyebrow">${k}</div><div class="card-head"><div><h1 class="title">${t}</h1><p class="subtitle">${s}</p></div>${action}</div>`}
function render(){if(!FEATURES.some(x=>x[0]===route))route='home';const fn={home:home,tasks:tasks,notes:notes,schedule:schedule,calendar:calendar,semester:semester,gpa:gpa,finance:finance,focus:focus,analytics:analytics,thesis:thesis,documents:documents,tools:tools,ai:ai,notifications:notifications,reminders:reminders,settings:settings}[route];document.getElementById('app').innerHTML=shell(fn());if(route==='focus')updateTimer();}
function home(){const p=state.profile,open=state.tasks.filter(x=>!x.done),progress=Math.min(100,Math.round((Number(p.credits||0)/Math.max(1,Number(p.totalCredits||144)))*100));return `<div class="hero"><div><div class="eyebrow">TODAY</div><h1>Yo, ${esc(p.preferredName||p.name||'Rizky')} 👋</h1><p>Gas mulai hari ini. Semua kebutuhan kuliah ada di satu tempat.</p></div><div class="hero-actions"><button class="btn primary" onclick="openTask()">+ Add Task</button><button class="btn" onclick="go('ai')">✦ Tanya AI</button></div></div><div class="grid stats"><div class="card"><div class="stat-label">Semester</div><div class="stat-value">${p.semester||1}</div></div><div class="card"><div class="stat-label">GPA</div><div class="stat-value">${p.gpa?Number(p.gpa).toFixed(2):'—'}</div></div><div class="card"><div class="stat-label">Target GPA</div><div class="stat-value">${Number(p.targetGpa||3.75).toFixed(2)}</div></div><div class="card"><div class="stat-label">Tasks tersisa</div><div class="stat-value">${open.length}</div></div></div><div class="grid two"><div class="card"><div class="card-head"><h2>Yang harus diberesin</h2><span class="pill">${open.length} aktif</span></div>${open.slice(0,6).map(taskRow).join('')||'<div class="empty">Clean slate. Belum ada tugas. 😌</div>'}</div><div class="card"><div class="card-head"><h2>Academic progress</h2><span class="pill">${p.credits||0}/${p.totalCredits||144} SKS</span></div><div class="kpi">${progress}%</div><div class="progress"><i style="width:${progress}%"></i></div><p class="muted">Progress kredit menuju kelulusan.</p><div class="actions"><button class="btn" onclick="go('gpa')">Hitung GPA</button><button class="btn" onclick="go('semester')">Kelola semester</button></div></div></div>`}
function taskRow(x){return `<div class="row"><button class="check ${x.done?'done':''}" onclick="toggleTask(${x.id})">${x.done?'✓':''}</button><div class="row-main"><div class="row-title">${esc(x.title)}</div><div class="row-meta">${esc(x.course||'Tanpa mata kuliah')} · ${esc(x.deadline||'Tanpa deadline')}</div></div><span class="pill">${esc(x.priority||'MEDIUM')}</span></div>`}
function tasks(){return `${header('WORKSPACE','Tasks','Satu tempat untuk tugas, deadline, dan prioritas.',`<button class="btn primary" onclick="openTask()">+ Add Task</button>`)}<div class="card">${state.tasks.length?state.tasks.map(taskRow).join(''):'<div class="empty">Belum ada tugas.</div>'}</div>`}
function notes(){return `${header('WORKSPACE','Notes','Catatan kuliah, ide, dan bahan belajar.',`<button class="btn primary" onclick="openNote()">+ Add Note</button>`)}<div class="grid three">${state.notes.map(n=>`<div class="card"><div class="card-head"><h2>${esc(n.title)}</h2><button class="btn small danger" onclick="deleteNote(${n.id})">Hapus</button></div><p class="muted">${esc(n.body)}</p></div>`).join('')||'<div class="card"><div class="empty">Masih kosong.</div></div>'}</div>`}
function schedule(){return `${header('ACADEMIC','Jadwal','Kelas dan jadwal mingguan.',`<button class="btn primary" onclick="openClass()">+ Add Class</button>`)}<div class="card">${state.schedule.length?state.schedule.map(c=>`<div class="row"><div class="row-main"><div class="row-title">${esc(c.name)}</div><div class="row-meta">${esc(c.day)} · ${esc(c.room||'Tanpa ruangan')}</div></div><span class="pill">${esc(c.start)}–${esc(c.end)}</span></div>`).join(''):'<div class="empty">Belum ada jadwal.</div>'}</div>`}
function calendar(){const d=new Date(),y=d.getFullYear(),m=d.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate();let cells='';for(let i=0;i<42;i++){const n=i-first+1;const day=n<1?prev+n:n>days?n-days:n;const muted=n<1||n>days;const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;const ev=state.calendarEvents.filter(e=>e.date===iso);cells+=`<div class="cal-cell ${muted?'muted-day':''} ${!muted&&day===d.getDate()?'today':''}"><b>${day}</b>${ev.map(e=>`<div class="event">${esc(e.title)}</div>`).join('')}</div>`}return `${header('PLANNER','Calendar','Agenda dan deadline dalam tampilan kalender.',`<button class="btn primary" onclick="openEvent()">+ Add Event</button>`)}<div class="card calendar"><div class="cal-head">${['Min','Sen','Sel','Rab','Kam','Jum','Sab'].map(x=>`<div>${x}</div>`).join('')}</div><div class="cal-grid">${cells}</div></div>`}
function semester(){return `${header('ACADEMIC','Semester','Mata kuliah dan beban SKS.',`<button class="btn primary" onclick="openCourse()">+ Add Course</button>`)}<div class="card">${state.courses.length?state.courses.map((c,i)=>`<div class="row"><div class="row-main"><div class="row-title">${esc(c.name)} ${c.code?`· ${esc(c.code)}`:''}</div><div class="row-meta">${c.credits||0} SKS · ${esc(c.lecturer||'Dosen belum diisi')}</div></div><button class="btn small danger" onclick="deleteItem('courses',${i})">Hapus</button></div>`).join(''):'<div class="empty">Belum ada mata kuliah.</div>'}</div>`}
function gpa(){const records=state.gpaRecords||[];const total=records.reduce((a,x)=>a+(Number(x.credits)||0)*(Number(x.grade)||0),0),credits=records.reduce((a,x)=>a+(Number(x.credits)||0),0),calc=credits?total/credits:(Number(state.profile.gpa)||0);return `${header('ACADEMIC','GPA','Masukkan nilai untuk menghitung IPK semester ini.',`<button class="btn primary" onclick="openGrade()">+ Add Nilai</button>`)}<div class="grid two"><div class="card"><div class="stat-label">IPK hasil perhitungan</div><div class="stat-value">${calc?calc.toFixed(2):'—'}</div><p class="muted">${credits} SKS tercatat.</p></div><div class="card"><div class="stat-label">Target</div><div class="stat-value">${Number(state.profile.targetGpa||3.75).toFixed(2)}</div><p class="muted">Edit target di Settings.</p></div></div><div class="card">${records.map((x,i)=>`<div class="row"><div class="row-main"><div class="row-title">${esc(x.name)}</div><div class="row-meta">${x.credits} SKS · nilai ${x.grade}</div></div><button class="btn small danger" onclick="deleteItem('gpaRecords',${i})">Hapus</button></div>`).join('')||'<div class="empty">Belum ada nilai.</div>'}</div>`}
function finance(){const inc=state.finance.filter(x=>x.type==='in').reduce((a,x)=>a+Number(x.amount||0),0),out=state.finance.filter(x=>x.type==='out').reduce((a,x)=>a+Number(x.amount||0),0);return `${header('LIFE','Finance','Catat pemasukan dan pengeluaran.',`<button class="btn primary" onclick="openFinance()">+ Add Transaction</button>`)}<div class="grid three"><div class="card"><div class="stat-label">Pemasukan</div><div class="stat-value">${money(inc)}</div></div><div class="card"><div class="stat-label">Pengeluaran</div><div class="stat-value">${money(out)}</div></div><div class="card"><div class="stat-label">Saldo</div><div class="stat-value">${money(inc-out)}</div></div></div><div class="card">${state.finance.map((x,i)=>`<div class="row"><div class="row-main"><div class="row-title">${esc(x.title)}</div><div class="row-meta">${x.type==='in'?'+':'−'} ${money(x.amount)} · ${esc(x.date||'')}</div></div><button class="btn small danger" onclick="deleteItem('finance',${i})">Hapus</button></div>`).join('')||'<div class="empty">Belum ada transaksi.</div>'}</div>`}
function focus(){const sec=Math.max(0,Number(state.focus.seconds||1500)),min=Math.floor(sec/60),s=sec%60,p=Math.max(0,Math.min(100,(1-sec/1500)*100));return `${header('PRODUCTIVITY','Focus','Pomodoro sederhana yang benar-benar jalan.') }<div class="grid two"><div class="card"><div class="focus-ring" style="--p:${p}%"><div><div class="timer" id="timer">${String(min).padStart(2,'0')}:${String(s).padStart(2,'0')}</div></div></div><div class="actions" style="justify-content:center"><button class="btn primary" onclick="toggleFocus()">${state.focus.running?'Pause':'Start'}</button><button class="btn" onclick="resetFocus()">Reset</button></div></div><div class="card"><h2>Focus stats</h2><div class="kpi">${Math.round((state.analytics.focusSeconds||0)/60)}m</div><p class="muted">Total waktu fokus tersimpan.</p><button class="btn" onclick="go('analytics')">Lihat analytics</button></div></div>`}
function updateTimer(){clearInterval(timerId);if(!state.focus.running)return;timerId=setInterval(()=>{if(state.focus.seconds<=0){state.focus.running=false;state.analytics.focusSeconds=(state.analytics.focusSeconds||0)+1500;state.focus.seconds=1500;save();toast('Focus selesai. Istirahat dulu.');render();return}state.focus.seconds--;save();const el=document.getElementById('timer');if(el){const m=Math.floor(state.focus.seconds/60),s=state.focus.seconds%60;el.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}},1000)}function toggleFocus(){state.focus.running=!state.focus.running;save();render()}function resetFocus(){state.focus.running=false;state.focus.seconds=1500;save();render()}
function analytics(){const mins=Math.round((state.analytics.focusSeconds||0)/60),done=state.tasks.filter(x=>x.done).length,total=state.tasks.length;return `${header('INSIGHTS','Analytics','Progress kuliah dan produktivitas lo.')}<div class="grid three"><div class="card"><div class="stat-label">Focus time</div><div class="stat-value">${mins}m</div></div><div class="card"><div class="stat-label">Task selesai</div><div class="stat-value">${done}</div></div><div class="card"><div class="stat-label">Completion</div><div class="stat-value">${total?Math.round(done/total*100):0}%</div></div></div><div class="card"><h2>Progress</h2><p class="muted">Jaga ritme: fokus, selesaikan tugas, lalu review GPA.</p></div>`}
function thesis(){const items=state.thesisProjects||[];return `${header('ACADEMIC','Thesis','Tracking proyek skripsi / penelitian.',`<button class="btn primary" onclick="openThesis()">+ Add Project</button>`)}<div class="grid two">${items.map((x,i)=>`<div class="card"><div class="card-head"><h2>${esc(x.title)}</h2><span class="pill">${esc(x.status||'Planning')}</span></div><p class="muted">${esc(x.supervisor||'Pembimbing belum diisi')}</p><div class="progress"><i style="width:${Math.max(0,Math.min(100,Number(x.progress)||0))}%"></i></div><p class="muted">${Number(x.progress)||0}%</p><button class="btn small danger" onclick="deleteItem('thesisProjects',${i})">Hapus</button></div>`).join('')||'<div class="card"><div class="empty">Belum ada proyek.</div></div>'}</div>`}
function documents(){return `${header('WORKSPACE','Documents','Buka file teks langsung dari HP atau komputer.') }<div class="card"><div class="field"><label>Pilih file</label><input type="file" id="docFile" accept=".txt,.md,.csv,.json,.html,.htm,text/*" onchange="readDocument(this)"></div><div id="docOut" class="doc" style="margin-top:12px">Belum ada file.</div></div>`}
function tools(){return `${header('TOOLS','Academic Tools','Alat kecil yang sering kepakai.') }<div class="grid three"><div class="card"><h2>Target GPA</h2><p class="muted">${gpaTargetText()}</p><button class="btn" onclick="go('gpa')">Buka GPA</button></div><div class="card"><h2>Task planner</h2><p class="muted">Urutkan tugas berdasarkan deadline dan prioritas.</p><button class="btn" onclick="sortTasks()">Urutkan</button></div><div class="card"><h2>Study plan</h2><p class="muted">AI bisa bikin rencana belajar dari data tugas lo.</p><button class="btn" onclick="askAI('Buatkan rencana belajar 7 hari dari tugas saya.')">Buat dengan AI</button></div></div>`}
function gpaTargetText(){const g=Number(state.profile.gpa||0),t=Number(state.profile.targetGpa||3.75);return g?`Sekarang ${g.toFixed(2)}, target ${t.toFixed(2)}.`:`Target ${t.toFixed(2)}. Isi GPA untuk analisis.`}
function ai(){const msgs=state.aiMessages||[{role:'assistant',text:'Halo. Gue Campusly AI. Tanya soal tugas, jadwal, GPA, atau minta bikin rencana belajar.'}];return `${header('ASSISTANT','Campusly AI','Asisten akademik yang tahu konteks data Campusly lo.') }<div class="card"><div class="chat">${msgs.map(m=>`<div class="bubble ${m.role==='user'?'me':''}">${esc(m.text)}</div>`).join('')}</div><div class="ai-box"><textarea id="aiInput" placeholder="Contoh: susun prioritas tugas gue minggu ini..."></textarea><button class="btn primary" onclick="sendAI()">Kirim</button></div><div class="actions" style="margin-top:10px"><button class="btn small" onclick="askAI('Apa yang harus saya kerjakan dulu hari ini?')">Prioritas hari ini</button><button class="btn small" onclick="askAI('Buatkan jadwal belajar minggu ini.')">Study plan</button><button class="btn small" onclick="askAI('Analisis kondisi GPA saya.')">Analisis GPA</button></div></div>`}
async function sendAI(){const el=document.getElementById('aiInput');const q=el?.value.trim();if(!q)return;await askAI(q)}async function askAI(q){state.aiMessages=state.aiMessages||[];state.aiMessages.push({role:'user',text:q});save();render();const token=localStorage.getItem('campusly_token');if(token){try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({messages:[{role:'system',content:aiContext()},{role:'user',content:q}]})});const d=await r.json();if(r.ok&&d.text){state.aiMessages.push({role:'assistant',text:d.text});save();render();return}}catch(e){}}setTimeout(()=>{state.aiMessages.push({role:'assistant',text:localAI(q)});save();render()},250)}
function aiContext(){return `Kamu Campusly AI. Bahasa Indonesia santai. Data mahasiswa: semester ${state.profile.semester}, GPA ${state.profile.gpa||'belum ada'}, target ${state.profile.targetGpa}, tugas aktif ${state.tasks.filter(x=>!x.done).length}, mata kuliah ${state.courses.map(x=>x.name).join(', ')||'belum ada'}. Beri jawaban praktis dan jangan mengarang data.`}
function localAI(q){const l=q.toLowerCase(),open=state.tasks.filter(x=>!x.done).sort((a,b)=>String(a.deadline||'9999').localeCompare(String(b.deadline||'9999')));if(l.includes('prioritas')||l.includes('kerjakan dulu'))return open.length?`Mulai dari: 1) ${open.slice(0,3).map(x=>x.title).join(', ')}. Fokus 25 menit untuk satu tugas, lalu lanjut berikutnya.`:'Belum ada tugas aktif. Tambahkan task dulu.';if(l.includes('gpa'))return gpaTargetText()+' Kalau mau, tambahkan nilai di menu GPA supaya hitungannya lebih akurat.';if(l.includes('jadwal')||l.includes('study plan')||l.includes('belajar'))return `Rencana cepat: Senin–Jumat 2 sesi fokus/hari (25 menit + 5 menit istirahat). Prioritaskan deadline terdekat, sisakan 1 sesi untuk review materi dan 1 sesi untuk tugas besar.`;return `Gue bisa bantu dari data Campusly lo. Coba tanya tentang prioritas tugas, GPA, jadwal belajar, atau minta study plan.`}
function notifications(){return `${header('SYSTEM','Notifications','Pusat aktivitas dan pengingat.') }<div class="card">${state.notifications?.length?state.notifications.map(n=>`<div class="row"><div class="row-main"><div class="row-title">${esc(n.title||'Notifikasi')}</div><div class="row-meta">${esc(n.body||'')}</div></div></div>`).join(''):'<div class="empty">Belum ada notifikasi.</div>'}</div>`}
function reminders(){return `${header('PRODUCTIVITY','Reminders','Pengingat yang tersimpan.') }<div class="card"><div class="actions"><button class="btn primary" onclick="openReminder()">+ Add Reminder</button></div>${(state.reminders||[]).map((x,i)=>`<div class="row"><div class="row-main"><div class="row-title">${esc(x.title)}</div><div class="row-meta">${esc(x.date||'')}</div></div><button class="btn small danger" onclick="deleteItem('reminders',${i})">Hapus</button></div>`).join('')||'<div class="empty">Belum ada reminder.</div>'}</div>`}
function settings(){const p=state.profile;return `${header('ACCOUNT','Settings','Profil, target akademik, dan data lokal.') }<div class="grid two"><div class="card"><h2>Profil</h2><form class="form" onsubmit="saveSettings(event)"><div class="field"><label>Nama</label><input name="name" value="${esc(p.name)}"></div><div class="field"><label>Nama panggilan</label><input name="preferredName" value="${esc(p.preferredName)}"></div><div class="field"><label>Universitas</label><input name="university" value="${esc(p.university)}"></div><div class="field"><label>Jurusan</label><input name="major" value="${esc(p.major)}"></div><div class="field"><label>Semester</label><input name="semester" type="number" min="1" value="${p.semester||1}"></div><div class="field"><label>GPA</label><input name="gpa" type="number" step=".01" min="0" max="4" value="${p.gpa||''}"></div><div class="field"><label>Target GPA</label><input name="targetGpa" type="number" step=".01" min="0" max="4" value="${p.targetGpa||3.75}"></div><button class="btn primary">Simpan</button></form></div><div class="card"><h2>Data</h2><p class="muted">Data aplikasi saat ini tersimpan lokal di browser.</p><div class="actions"><button class="btn" onclick="exportData()">Export JSON</button><button class="btn danger" onclick="resetData()">Reset data</button></div></div></div>`}
function menu(){return `${header('NAVIGATION','Menu','Semua fitur tetap tersedia di HP—tidak ada fitur yang disembunyikan.') }<div class="menu-sheet">${FEATURES.filter(x=>!['home','tasks','schedule','ai'].includes(x[0])).map(([r,l,d])=>`<button class="menu-item" onclick="go('${r}')"><b>${ICON[r]} ${l}</b><span>${d}</span></button>`).join('')}</div>`}
function openMenu(){overlay('Menu',menu().replace(/<div class="eyebrow">NAVIGATION<\/div><div class="card-head">[\s\S]*?<\/div>/,''))}
function overlay(title,body){document.body.insertAdjacentHTML('beforeend',`<div class="overlay" id="overlay" onclick="if(event.target===this)closeOverlay()"><div class="modal"><div class="card-head"><h2>${title}</h2><button class="btn small" onclick="closeOverlay()">Tutup</button></div>${body}</div></div>`)}function closeOverlay(){document.getElementById('overlay')?.remove()}
function formModal(title,fields,submit){overlay(title,`<form class="form" onsubmit="${submit}(event)">${fields}<div class="actions"><button class="btn primary">Simpan</button><button type="button" class="btn" onclick="closeOverlay()">Batal</button></div></form>`)}
function openTask(){formModal('Tambah Task',`<div class="field"><label>Judul</label><input name="title" required autofocus></div><div class="field"><label>Mata kuliah</label><input name="course"></div><div class="field"><label>Deadline</label><input name="deadline" type="date"></div><div class="field"><label>Prioritas</label><select name="priority"><option>HIGH</option><option selected>MEDIUM</option><option>LOW</option></select></div>`,'saveTask')}
function saveTask(e){e.preventDefault();const f=new FormData(e.target);state.tasks.push({id:Date.now(),title:f.get('title'),course:f.get('course'),deadline:f.get('deadline'),priority:f.get('priority'),done:false});save();closeOverlay();render();toast('Task ditambahkan')}
function toggleTask(id){const x=state.tasks.find(x=>x.id===id);if(x){x.done=!x.done;save();render()}}
function openNote(){formModal('Tambah Note',`<div class="field"><label>Judul</label><input name="title" required autofocus></div><div class="field"><label>Isi</label><textarea name="body"></textarea></div>`,'saveNote')}
function saveNote(e){e.preventDefault();const f=new FormData(e.target);state.notes.push({id:Date.now(),title:f.get('title'),body:f.get('body')});save();closeOverlay();render()}
function deleteNote(id){state.notes=state.notes.filter(x=>x.id!==id);save();render()}
function openClass(){formModal('Tambah Jadwal',`<div class="field"><label>Mata kuliah</label><input name="name" required></div><div class="field"><label>Hari</label><select name="day">${['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Mulai</label><input name="start" type="time"></div><div class="field"><label>Selesai</label><input name="end" type="time"></div><div class="field"><label>Ruangan</label><input name="room"></div>`,'saveClass')}
function saveClass(e){e.preventDefault();const f=new FormData(e.target);state.schedule.push(Object.fromEntries(f));save();closeOverlay();render()}
function openEvent(){formModal('Tambah Event',`<div class="field"><label>Judul</label><input name="title" required></div><div class="field"><label>Tanggal</label><input name="date" type="date" required></div>`,'saveEvent')}
function saveEvent(e){e.preventDefault();const f=new FormData(e.target);state.calendarEvents.push({title:f.get('title'),date:f.get('date')});save();closeOverlay();render()}
function openCourse(){formModal('Tambah Mata Kuliah',`<div class="field"><label>Nama</label><input name="name" required></div><div class="field"><label>Kode</label><input name="code"></div><div class="field"><label>SKS</label><input name="credits" type="number" min="1" required></div><div class="field"><label>Dosen</label><input name="lecturer"></div>`,'saveCourse')}
function saveCourse(e){e.preventDefault();const f=new FormData(e.target);state.courses.push({name:f.get('name'),code:f.get('code'),credits:Number(f.get('credits')),lecturer:f.get('lecturer')});save();closeOverlay();render()}
function openGrade(){formModal('Tambah Nilai',`<div class="field"><label>Mata kuliah</label><input name="name" required></div><div class="field"><label>SKS</label><input name="credits" type="number" min="1" required></div><div class="field"><label>Nilai angka 0–4</label><input name="grade" type="number" min="0" max="4" step=".01" required></div>`,'saveGrade')}
function saveGrade(e){e.preventDefault();const f=new FormData(e.target);state.gpaRecords.push({name:f.get('name'),credits:Number(f.get('credits')),grade:Number(f.get('grade'))});save();closeOverlay();render()}
function openFinance(){formModal('Tambah Transaksi',`<div class="field"><label>Judul</label><input name="title" required></div><div class="field"><label>Jumlah</label><input name="amount" type="number" min="0" required></div><div class="field"><label>Tipe</label><select name="type"><option value="out">Pengeluaran</option><option value="in">Pemasukan</option></select></div><div class="field"><label>Tanggal</label><input name="date" type="date"></div>`,'saveFinance')}
function saveFinance(e){e.preventDefault();const f=new FormData(e.target);state.finance.push({title:f.get('title'),amount:Number(f.get('amount')),type:f.get('type'),date:f.get('date')});save();closeOverlay();render()}
function openThesis(){formModal('Tambah Project',`<div class="field"><label>Judul</label><input name="title" required></div><div class="field"><label>Pembimbing</label><input name="supervisor"></div><div class="field"><label>Status</label><select name="status"><option>Planning</option><option>Research</option><option>Writing</option><option>Revision</option><option>Done</option></select></div><div class="field"><label>Progress %</label><input name="progress" type="number" min="0" max="100" value="0"></div>`,'saveThesis')}
function saveThesis(e){e.preventDefault();const f=new FormData(e.target);state.thesisProjects.push({title:f.get('title'),supervisor:f.get('supervisor'),status:f.get('status'),progress:Number(f.get('progress'))});save();closeOverlay();render()}
function openReminder(){formModal('Tambah Reminder',`<div class="field"><label>Judul</label><input name="title" required></div><div class="field"><label>Tanggal</label><input name="date" type="datetime-local"></div>`,'saveReminder')}
function saveReminder(e){e.preventDefault();const f=new FormData(e.target);state.reminders.push({title:f.get('title'),date:f.get('date')});save();closeOverlay();render()}
function deleteItem(key,i){if(Array.isArray(state[key])){state[key].splice(i,1);save();render()}}
function saveSettings(e){e.preventDefault();const f=new FormData(e.target);state.profile.name=f.get('name');state.profile.preferredName=f.get('preferredName');state.profile.university=f.get('university');state.profile.major=f.get('major');state.profile.semester=Number(f.get('semester')||1);state.profile.gpa=Number(f.get('gpa')||0);state.profile.targetGpa=Number(f.get('targetGpa')||3.75);save();render();toast('Profil disimpan')}
function sortTasks(){state.tasks.sort((a,b)=>String(a.deadline||'9999').localeCompare(String(b.deadline||'9999')));save();go('tasks');toast('Tugas diurutkan')}
function readDocument(input){const f=input.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{document.getElementById('docOut').textContent=String(r.result||'');};r.readAsText(f)}
function searchApp(q){q=q.trim().toLowerCase();if(!q)return;const map={task:'tasks',tugas:'tasks',note:'notes',catatan:'notes',jadwal:'schedule',calendar:'calendar',gpa:'gpa',ipk:'gpa',uang:'finance',keuangan:'finance',focus:'focus',ai:'ai',skripsi:'thesis',dokumen:'documents',reminder:'reminders',setting:'settings',profil:'settings'};const key=Object.keys(map).find(k=>q.includes(k));if(key){go(map[key]);return}const t=state.tasks.find(x=>x.title.toLowerCase().includes(q));if(t){go('tasks');return}toast('Nggak ketemu. Coba kata kunci fitur.')}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='campusly-backup.json';a.click();URL.revokeObjectURL(a.href)}
function resetData(){if(confirm('Reset semua data Campusly di browser ini?')){localStorage.removeItem(KEY);state=clone(defaults);render();toast('Data direset')}}
render();
