/* Campusly — canonical frontend */
const KEY='campusly_state_v3';
const DEFAULT={profile:{name:'Rizky',preferredName:'Rizky',university:'',major:'',semester:1,gpa:0,targetGpa:3.75},tasks:[],notes:[],events:[],aiMessages:[],settings:{theme:'light'}};
const $=s=>document.querySelector(s);
const clone=x=>JSON.parse(JSON.stringify(x));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=()=>crypto.randomUUID?.()||Date.now()+Math.random().toString(16).slice(2);
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const icons={home:'M3 10l9-7 9 7v11H3z',tasks:'M5 12l4 4L19 6',calendar:'M5 4h14a2 2 0 012 2v13H3V6a2 2 0 012-2zM8 2v4M16 2v4M3 9h18',ai:'M12 3l2 6 6 3-6 2-2 7-2-7-6-2 6-3z',menu:'M4 6h16M4 12h16M4 18h16',plus:'M12 5v14M5 12h14',back:'M19 12H5m7 7l-7-7 7-7',search:'M11 4a7 7 0 107 7M16 16l5 5',close:'M6 6l12 12M18 6L6 18',send:'M4 12h15M13 6l6 6-6 6',scan:'M4 8V4h4M16 4h4v4M20 16v4h-4M8 20H4v-4',file:'M6 3h8l4 4v14H6zM14 3v5h5',image:'M4 5h16v14H4zM8 13l3-3 3 3 2-2 4 4M9 9h.01',mail:'M4 5h16v14H4zM4 7l8 6 8-6',instagram:'M7 3h10a4 4 0 014 4v10a4 4 0 01-4 4H7a4 4 0 01-4-4V7a4 4 0 014-4zM12 8a4 4 0 100 8 4 4 0 000-8zM17.5 6.5h.01',settings:'M12 8a4 4 0 100 8 4 4 0 000-8zM12 3v2m0 14v2M3 12h2m14 0h2',sun:'M12 3v2m0 14v2M3 12h2m14 0h2M5.6 5.6l1.4 1.4m10 10l1.4 1.4M18.4 5.6L17 7M7 17l-1.4 1.4',moon:'M20 15.5A8 8 0 018.5 4 8 8 0 1020 15.5z',trash:'M4 7h16M10 11v6M14 11v6M6 7l1 14M9 7V4h6v3'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="${icons[n]||icons.menu}"/></svg>`;
let S=load();
let route=location.hash.slice(1)||'home';
let monthCursor=new Date(new Date().getFullYear(),new Date().getMonth(),1);
function load(){try{const raw=JSON.parse(localStorage.getItem(KEY)||'{}');const s={...clone(DEFAULT),...raw};s.profile={...DEFAULT.profile,...(raw.profile||{})};s.settings={...DEFAULT.settings,...(raw.settings||{})};for(const k of ['tasks','notes','events','aiMessages'])if(!Array.isArray(s[k]))s[k]=[];return s}catch{return clone(DEFAULT)}}
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function go(r){route=r;location.hash=r;closeModal();render()}
addEventListener('hashchange',()=>{route=location.hash.slice(1)||'home';render()});
function applyTheme(){document.documentElement.dataset.theme=S.settings.theme==='dark'?'dark':'light'}
function toast(text){const x=document.createElement('div');x.className='toast';x.textContent=text;document.body.append(x);setTimeout(()=>x.remove(),2600)}
function closeModal(){$('#modal')?.remove()}
function modal(title,body,saveFn,saveLabel='Simpan'){closeModal();const d=document.createElement('div');d.id='modal';d.className='overlay';d.innerHTML=`<div class="modal"><div class="modal-head"><h2>${esc(title)}</h2><button class="icon-btn" onclick="closeModal()">${icon('close')}</button></div><div class="modal-body">${body}</div><div class="modal-actions"><button class="btn" onclick="closeModal()">Batal</button><button class="btn primary" id="modal-save">${esc(saveLabel)}</button></div></div>`;document.body.append(d);d.addEventListener('click',e=>{if(e.target===d)closeModal()});$('#modal-save').onclick=saveFn}
function field(label,name,value='',type='text',extra=''){return `<label class="field"><span>${esc(label)}</span><input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function textarea(label,name,value='',placeholder=''){return `<label class="field"><span>${esc(label)}</span><textarea name="${name}" placeholder="${esc(placeholder)}">${esc(value)}</textarea></label>`}
function header(k,title,sub,action=''){return `<div class="eyebrow">${esc(k)}</div><div class="page-head"><div><h1>${esc(title)}</h1><p>${esc(sub)}</p></div>${action}</div>`}
function shell(content){const p=S.profile;const nav=[['home','home','Beranda'],['tasks','tasks','Tugas'],['calendar','calendar','Kalender'],['ai','ai','AI'],['menu','menu','Menu']];return `<div class="app"><aside><div class="brand"><b>C</b><span>Campusly</span></div><nav>${nav.map(([r,i,l])=>`<button class="${route===r?'active':''}" onclick="go('${r}')">${icon(i)}<span>${l}</span></button>`).join('')}</nav><div class="aside-footer"><button onclick="go('settings')">${icon('settings')}<span>Pengaturan</span></button></div></aside><main><header><label class="search">${icon('search')}<input placeholder="Cari tugas, catatan, kelas..." onkeydown="if(event.key==='Enter')quickSearch(this.value)"></label><button class="avatar" onclick="go('settings')">${esc((p.preferredName||p.name||'R')[0].toUpperCase())}</button></header><section>${content}</section></main><nav class="mobile-nav">${nav.map(([r,i,l])=>`<button class="${route===r?'active':''}" onclick="go('${r}')">${icon(i)}<span>${l}</span></button>`).join('')}</nav></div>`}
function render(){applyTheme();const pages={home,tasks,calendar,ai,menu,notes,settings};try{$('#app').innerHTML=shell((pages[route]||home)())}catch(e){console.error(e);$('#app').innerHTML=shell(`<div class="error-card"><h1>Campusly mengalami error</h1><p>${esc(e.message||'Halaman gagal dimuat.')}</p><button class="btn primary" onclick="location.reload()">Muat ulang</button></div>`)}}
function home(){const active=S.tasks.filter(t=>!t.done).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'9999'));const today=new Date();const todayEvents=S.events.filter(e=>e.date===dateKey(today));return `${header('CAMPUS WORKSPACE',`Halo, ${S.profile.preferredName||'Rizky'}.`,'Semua kebutuhan kuliah dalam satu ruang yang rapi.',`<button class="btn primary" onclick="taskModal()">${icon('plus')} Tambah tugas</button>`)}<div class="hero"><div><span class="pill">Student workspace</span><h2>Fokus ke kuliah, bukan ke aplikasi.</h2><p>Tugas, kalender, catatan, dan AI dibuat sesederhana mungkin.</p><div class="actions"><button class="btn primary" onclick="go('calendar')">${icon('calendar')} Buka kalender</button><button class="btn" onclick="go('ai')">${icon('ai')} Tanya AI</button></div></div></div><div class="quick-grid"><button onclick="taskModal()">${icon('tasks')}<b>Tambah tugas</b><small>Atur deadline</small></button><button onclick="noteModal()">${icon('file')}<b>Catatan cepat</b><small>Simpan materi</small></button><button onclick="eventModal()">${icon('calendar')}<b>Agenda</b><small>Tambah jadwal</small></button><button onclick="go('ai')">${icon('ai')}<b>AI Tools</b><small>Scan, makalah, PPT</small></button></div><div class="stats"><article><small>Tugas aktif</small><strong>${active.length}</strong><span>yang belum selesai</span></article><article><small>Agenda hari ini</small><strong>${todayEvents.length}</strong><span>${today.toLocaleDateString('id-ID',{weekday:'long'})}</span></article><article><small>Semester</small><strong>${S.profile.semester||1}</strong><span>${esc(S.profile.major||'Program studi belum diisi')}</span></article><article><small>GPA</small><strong>${S.profile.gpa?Number(S.profile.gpa).toFixed(2):'—'}</strong><span>Target ${Number(S.profile.targetGpa||3.75).toFixed(2)}</span></article></div><div class="two"><article class="card"><div class="card-head"><div><h2>Prioritas tugas</h2><p>Deadline terdekat</p></div><button class="link" onclick="go('tasks')">Lihat semua</button></div>${active.slice(0,5).map(taskRow).join('')||empty('Belum ada tugas aktif.','Tambah tugas','taskModal()')}</article><article class="card"><div class="card-head"><div><h2>Hari ini</h2><p>${today.toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'})}</p></div><button class="link" onclick="go('calendar')">Kalender</button></div>${todayEvents.map(e=>`<div class="event-row"><b>${esc(e.time||'—')}</b><div><strong>${esc(e.title)}</strong><small>${esc(e.location||'')}</small></div></div>`).join('')||'<div class="empty">Belum ada agenda hari ini.</div>'}</article></div>`}
function taskRow(t){return `<div class="row"><button class="check ${t.done?'done':''}" onclick="toggleTask('${esc(t.id)}')">${t.done?'✓':''}</button><div><b>${esc(t.title)}</b><small>${esc(t.course||'Tanpa mata kuliah')} · ${esc(t.deadline||'Tanpa deadline')}</small></div><button class="icon-btn" onclick="taskModal('${esc(t.id)}')">✎</button></div>`}
function empty(text,label,action){return `<div class="empty"><p>${esc(text)}</p><button class="btn" onclick="${action}">${esc(label)}</button></div>`}
function tasks(){const q=(window.taskQ||'').toLowerCase();const list=S.tasks.filter(t=>!q||`${t.title} ${t.course||''}`.toLowerCase().includes(q)).sort((a,b)=>(a.done-b.done)||((a.deadline||'9999').localeCompare(b.deadline||'9999')));return `${header('WORKSPACE','Tugas','Satu daftar untuk semua deadline.',`<button class="btn primary" onclick="taskModal()">${icon('plus')} Tambah tugas</button>`)}<div class="toolbar"><input value="${esc(window.taskQ||'')}" placeholder="Cari tugas..." oninput="window.taskQ=this.value;render()"><button class="btn" onclick="window.taskQ='';render()">Reset</button></div><article class="card">${list.map(taskRow).join('')||empty('Belum ada tugas yang cocok.','Tambah tugas','taskModal()')}</article>`}
function calendar(){const y=monthCursor.getFullYear(),m=monthCursor.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),start=(first.getDay()+6)%7,cells=[];for(let i=0;i<42;i++){const n=i-start+1;cells.push(n<1?new Date(y,m-1,n):n>days?new Date(y,m+1,n-days):new Date(y,m,n))}const monthName=first.toLocaleDateString('id-ID',{month:'long',year:'numeric'});return `${header('PLANNER','Kalender','Kalender bulanan penuh dan nyaman dipakai di HP.',`<div class="cal-actions"><button class="icon-btn" onclick="changeMonth(-1)">‹</button><button class="btn" onclick="monthToday()">Hari ini</button><button class="icon-btn" onclick="changeMonth(1)">›</button><button class="btn primary" onclick="eventModal()">${icon('plus')} Agenda</button></div>`)}<article class="card calendar-card"><div class="calendar-title"><h2>${esc(monthName)}</h2><span>${days} hari</span></div><div class="cal-head">${['Sen','Sel','Rab','Kam','Jum','Sab','Min'].map(x=>`<b>${x}</b>`).join('')}</div><div class="cal-grid">${cells.map(d=>{const key=dateKey(d),events=S.events.filter(e=>e.date===key);return `<button class="day ${d.getMonth()!==m?'out':''} ${key===dateKey(new Date())?'today':''}" onclick="eventModal('','${key}')"><span>${d.getDate()}</span>${events.slice(0,3).map(e=>`<em>${esc(e.title)}</em>`).join('')}</button>`}).join('')}</div></article>`}
function changeMonth(n){monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()+n,1);render()}
function monthToday(){const d=new Date();monthCursor=new Date(d.getFullYear(),d.getMonth(),1);render()}
function ai(){const msgs=S.aiMessages.length?S.aiMessages:[{role:'assistant',text:'Halo! Gue Campusly AI. Pilih alat di bawah atau langsung tanya apa pun soal kuliah.'}];return `${header('ASSISTANT','Campusly AI','Satu tempat untuk chat, scan soal, makalah, PPT, dan gambar.')}<div class="ai-tools"><button onclick="aiChat()">${icon('ai')}<b>Chat AI</b><small>Tanya apa saja</small></button><button onclick="scanModal()">${icon('scan')}<b>Scan soal</b><small>Foto soal → jawaban</small></button><button onclick="paperModal()">${icon('file')}<b>Buat makalah</b><small>Draft + PDF</small></button><button onclick="pptModal()">${icon('file')}<b>Buat PPT</b><small>Materi → .pptx</small></button><button onclick="imageModal()">${icon('image')}<b>Generate gambar</b><small>Prompt → gambar</small></button></div><article class="card ai-card"><div class="card-head"><div><h2>Chat terbaru</h2><p>Riwayat tersimpan di perangkat ini.</p></div><button class="link" onclick="clearAI()">Bersihkan</button></div><div class="chat">${msgs.slice(-12).map(m=>`<div class="bubble ${m.role==='user'?'me':''}"><small>${m.role==='user'?'Kamu':'Campusly AI'}</small>${esc(m.text)}</div>`).join('')}</div><div class="ai-input"><textarea id="aiq" placeholder="Contoh: tugas mana yang harus gue kerjain dulu?"></textarea><button class="btn primary" onclick="sendAI()">${icon('send')} Kirim</button></div><div class="chips"><button onclick="askAI('Apa prioritas tugas saya hari ini?')">Prioritas</button><button onclick="askAI('Buatkan study plan 7 hari dari tugas saya.')">Study plan</button><button onclick="askAI('Bantu saya memahami materi kuliah dengan bahasa sederhana.')">Jelaskan materi</button></div></article>`}
function aiChat(){document.getElementById('aiq')?.focus()||toast('Chat AI sudah tersedia di bawah.')} 
async function sendAI(){const q=$('#aiq')?.value.trim();if(q)await askAI(q)}
async function askAI(q){S.aiMessages.push({role:'user',text:q});save();render();try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:S.aiMessages.slice(-12).map(m=>({role:m.role,content:m.text})),context:aiContext()})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.text)throw new Error(d.error||`AI gagal (HTTP ${r.status})`);S.aiMessages.push({role:'assistant',text:d.text})}catch(e){S.aiMessages.push({role:'assistant',text:`⚠️ ${e.message||'AI gagal terhubung.'}`})}save();render()}
function aiContext(){return `Nama ${S.profile.preferredName||S.profile.name}; semester ${S.profile.semester||1}; program studi ${S.profile.major||'belum diisi'}; GPA ${S.profile.gpa||'belum diisi'}; target GPA ${S.profile.targetGpa||3.75}; tugas aktif: ${S.tasks.filter(x=>!x.done).map(x=>x.title).join(', ')||'tidak ada'}.`}
function clearAI(){S.aiMessages=[];save();render()}
function scanModal(){modal('Scan soal / dokumen gambar',`<div class="tool-modal"><p>Upload foto soal. Campusly AI akan membaca gambar lalu menjelaskan jawaban dan langkahnya.</p><label class="drop"><span>${icon('scan')} Pilih gambar</span><input id="scan-file" type="file" accept="image/png,image/jpeg,image/webp"></label><div id="scan-result" class="result"></div></div>`,async()=>{const f=$('#scan-file')?.files?.[0];if(!f)return toast('Pilih gambar dulu.');const result=$('#scan-result');result.textContent='Sedang membaca gambar...';try{const image=await dataUrl(f);const r=await fetch('/api/ai/vision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,question:'Baca semua soal pada gambar. Jawab dengan benar dan jelaskan langkah pengerjaannya secara runtut.',context:aiContext()})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Scan gagal (HTTP ${r.status})`);result.textContent=d.text||'Tidak ada jawaban.'}catch(e){result.textContent=`Gagal: ${e.message||'Scan gagal.'}`}},'Scan')}
function paperModal(){modal('Buat makalah',`<div class="form">${field('Topik','topic','','text','required')}${field('Mata kuliah','course')}<label class="field"><span>Panjang</span><select name="length"><option>Ringkas (2–3 halaman)</option><option>Standar (4–6 halaman)</option><option>Lengkap (7–10 halaman)</option></select></label>${textarea('Instruksi tambahan','notes','','Contoh: pakai struktur akademik dan bahasa formal.')}</div><div id="paper-result" class="result"></div>`,async()=>{const o=Object.fromEntries(new FormData($('.modal')));if(!o.topic)return toast('Topik wajib diisi.');const out=$('#paper-result');out.textContent='Sedang menyusun makalah...';try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:`Buat makalah mahasiswa tentang ${o.topic}. Mata kuliah: ${o.course||'umum'}. Panjang: ${o.length}. ${o.notes||''}. Susun judul, pendahuluan, pembahasan, penutup, dan daftar poin referensi yang perlu dicari. Jangan mengarang sumber.`}],context:aiContext()})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.text)throw new Error(d.error||'AI gagal');out.innerHTML=`<pre>${esc(d.text)}</pre><div class="result-actions"><button class="btn primary" onclick="downloadExport('/api/export/pdf',${JSON.stringify(o.topic)},${JSON.stringify(d.text)},'application/pdf','campusly-makalah.pdf')">Export PDF</button></div>`}catch(e){out.textContent=`Gagal: ${e.message}`}},'Buat makalah')}
function pptModal(){modal('Buat PPT',`<div class="form">${field('Topik','topic','','text','required')}${field('Jumlah slide','slides',8,'number','min="3" max="20"')}${textarea('Gaya / isi yang wajib ada','notes','','Contoh: fokus pada konsep inti dan contoh kasus.')}</div><div id="ppt-result" class="result"></div>`,async()=>{const o=Object.fromEntries(new FormData($('.modal')));if(!o.topic)return toast('Topik wajib diisi.');const out=$('#ppt-result');out.textContent='Sedang membuat materi PPT...';try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:`Buat materi presentasi ${o.slides} slide tentang ${o.topic}. ${o.notes||''}. Gunakan format SLIDE 1: Judul lalu isi tiap slide dengan bullet yang jelas.`}],context:aiContext()})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.text)throw new Error(d.error||'AI gagal');out.innerHTML=`<pre>${esc(d.text)}</pre><div class="result-actions"><button class="btn primary" onclick="downloadExport('/api/export/ppt',${JSON.stringify(o.topic)},${JSON.stringify(d.text)},'application/vnd.openxmlformats-officedocument.presentationml.presentation','campusly-presentasi.pptx')">Export PPTX</button></div>`}catch(e){out.textContent=`Gagal: ${e.message}`}},'Buat PPT')}
function imageModal(){modal('Generate gambar',`<div class="form">${textarea('Prompt gambar','prompt','','Contoh: ilustrasi minimalis sistem tata surya untuk presentasi mahasiswa.')}</div><div id="image-result" class="image-result"></div>`,async()=>{const p=$('.modal textarea[name="prompt"]')?.value.trim();if(!p)return toast('Prompt wajib diisi.');const out=$('#image-result');out.textContent='Sedang membuat gambar...';try{const r=await fetch('/api/ai/image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:p})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.image)throw new Error(d.error||`Generate gambar gagal (HTTP ${r.status})`);out.innerHTML=`<img src="${d.image}" alt="Hasil generate"><a class="btn primary" download="campusly-generated.png" href="${d.image}">Simpan gambar</a>`}catch(e){out.textContent=`Gagal: ${e.message}`}},'Generate')}
function dataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
async function downloadExport(url,title,content,type,name){try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,content})});if(!r.ok)throw new Error((await r.text())||'Export gagal');const b=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([b],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){toast(`Export gagal: ${e.message}`)}}
function menu(){return `${header('CAMPUSLY','Menu','Navigasi ringkas, tanpa kontak orang lain yang tidak perlu.')}<div class="developer-card"><div class="dev-avatar">R</div><div><span class="eyebrow">DEVELOPER</span><h2>Rizky Khoilillu Rochman</h2><p>Pengembang Campusly</p></div></div><div class="contact-grid"><a href="mailto:rizkykhoilillurochman@gmail.com">${icon('mail')}<span><b>Email</b><small>rizkykhoilillurochman@gmail.com</small></span></a><a href="https://instagram.com/therealramanih_" target="_blank" rel="noopener">${icon('instagram')}<span><b>Instagram</b><small>@therealramanih_</small></span></a></div><div class="menu-grid"><button onclick="go('notes')">${icon('file')}<span><b>Catatan</b><small>Materi kuliah</small></span></button><button onclick="go('settings')">${icon('settings')}<span><b>Pengaturan</b><small>Profil & tema</small></span></button></div>`}
function notes(){return `${header('WORKSPACE','Catatan','Simpan materi dan ringkasan kuliah.',`<button class="btn primary" onclick="noteModal()">${icon('plus')} Catatan baru</button>`)}<div class="notes-grid">${S.notes.map((n,i)=>`<article class="card"><div class="card-head"><span class="pill">${esc(n.course||'Umum')}</span><button class="icon-btn" onclick="deleteNote(${i})">${icon('trash')}</button></div><h2>${esc(n.title)}</h2><p class="note">${esc(n.body)}</p></article>`).join('')||`<article class="card">${empty('Belum ada catatan.','Buat catatan','noteModal()')}</article>`}</div>`}
function settings(){const dark=S.settings.theme==='dark';return `${header('PREFERENCES','Pengaturan','Profil dan tampilan Campusly.')}<div class="two"><article class="card"><h2>Profil mahasiswa</h2><p>Data ini dipakai untuk konteks AI lokal.</p><div class="form">${field('Nama panggilan','preferredName',S.profile.preferredName)}${field('Universitas','university',S.profile.university)}${field('Program studi','major',S.profile.major)}${field('Semester','semester',S.profile.semester,'number','min="1" max="20"')}${field('GPA','gpa',S.profile.gpa,'number','min="0" max="4" step=".01"')}${field('Target GPA','targetGpa',S.profile.targetGpa,'number','min="0" max="4" step=".01"')}<button class="btn primary" onclick="saveProfile()">Simpan profil</button></div></article><article class="card"><h2>Tampilan</h2><p>${dark?'Mode gelap aktif.':'Mode terang aktif.'} Warna netral, kontras, dan tidak biru mencolok.</p><button class="btn" onclick="toggleTheme()">${icon(dark?'sun':'moon')} ${dark?'Gunakan mode terang':'Gunakan mode gelap'}</button><hr><button class="btn" onclick="exportLocal()">Export backup data</button></article></div>`}
function taskModal(taskId=''){const t=S.tasks.find(x=>x.id===taskId)||{};modal(taskId?'Edit tugas':'Tambah tugas',`<div class="form">${field('Judul','title',t.title||'','','required')}${field('Mata kuliah','course',t.course||'')}${field('Deadline','deadline',t.deadline||'', 'date')}${field('Prioritas','priority',t.priority||'Normal')}</div>`,()=>{const o=Object.fromEntries(new FormData($('.modal')));if(!o.title?.trim())return toast('Judul wajib diisi.');if(taskId)Object.assign(t,o);else S.tasks.push({id:id(),...o,done:false});save();closeModal();render()})}
function noteModal(){modal('Catatan baru',`<div class="form">${field('Judul','title')}${field('Mata kuliah','course')}${textarea('Isi catatan','body')}</div>`,()=>{const o=Object.fromEntries(new FormData($('.modal')));if(!o.title&&!o.body)return toast('Isi catatan dulu.');S.notes.unshift(o);save();closeModal();render()})}
function eventModal(eventId='',prefill=''){const e=S.events.find(x=>x.id===eventId)||{};modal(eventId?'Edit agenda':'Tambah agenda',`<div class="form">${field('Judul','title',e.title||'')}${field('Tanggal','date',e.date||prefill,'date','required')}${field('Jam','time',e.time||'','time')}${field('Lokasi','location',e.location||'')}${textarea('Catatan','body',e.body||'')}</div>`,()=>{const o=Object.fromEntries(new FormData($('.modal')));if(!o.title||!o.date)return toast('Judul dan tanggal wajib.');if(eventId)Object.assign(e,o);else S.events.push({id:id(),...o});save();closeModal();render()})}
function toggleTask(taskId){const t=S.tasks.find(x=>x.id===taskId);if(t){t.done=!t.done;save();render()}}
function deleteNote(i){if(confirm('Hapus catatan ini?')){S.notes.splice(i,1);save();render()}}
function saveProfile(){const o=Object.fromEntries(new FormData($('.form')));S.profile={...S.profile,...o,semester:+o.semester||1,gpa:+o.gpa||0,targetGpa:+o.targetGpa||3.75};save();toast('Profil tersimpan.');render()}
function toggleTheme(){S.settings.theme=S.settings.theme==='dark'?'light':'dark';save();applyTheme();render()}
function exportLocal(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download='campusly-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function quickSearch(q){const x=q.trim().toLowerCase();if(!x)return;if(S.tasks.some(t=>`${t.title} ${t.course||''}`.toLowerCase().includes(x))){window.taskQ=q;go('tasks')}else{go('tasks');window.taskQ=q}}
window.go=go;window.closeModal=closeModal;window.taskModal=taskModal;window.noteModal=noteModal;window.eventModal=eventModal;window.toggleTask=toggleTask;window.changeMonth=changeMonth;window.monthToday=monthToday;window.askAI=askAI;window.sendAI=sendAI;window.scanModal=scanModal;window.paperModal=paperModal;window.pptModal=pptModal;window.imageModal=imageModal;window.toggleTheme=toggleTheme;window.saveProfile=saveProfile;window.exportLocal=exportLocal;window.clearAI=clearAI;window.quickSearch=quickSearch;window.deleteNote=deleteNote;
window.addEventListener('error',e=>console.error('Campusly runtime:',e.error||e.message));
applyTheme();render();
