/* Campusly core — single canonical runtime. Feature implementations are merged below. */
const KEY='campusly_state_v1';
const defaults={profile:{name:'Rizky',preferredName:'Rizky',university:'',major:'',semester:1,gpa:0,targetGpa:3.75,credits:0,totalCredits:144},tasks:[],notes:[],schedule:[],calendarEvents:[],finance:[],budgets:[],focus:{seconds:1500,running:false,session:0},courses:[],gpaRecords:[],thesisProjects:[],documents:[],notifications:[],reminders:[],analytics:{focusSeconds:0,focusHistory:[]},settings:{theme:'dark',accent:'purple'},onboarding:{complete:true}};
const FEATURES=[['home','Home','Ringkasan kuliah'],['tasks','Tasks','Tugas & deadline'],['notes','Notes','Catatan kuliah'],['schedule','Jadwal','Jadwal kelas'],['calendar','Calendar','Agenda'],['semester','Semester','Mata kuliah'],['gpa','GPA','Kalkulator IPK'],['finance','Finance','Keuangan'],['focus','Focus','Pomodoro'],['analytics','Analytics','Progress'],['thesis','Thesis','Proyek skripsi'],['documents','Documents','Baca file'],['tools','Academic Tools','Tools akademik'],['ai','Campusly AI','Asisten AI'],['notifications','Notifications','Pusat notifikasi'],['reminders','Reminders','Pengingat'],['settings','Settings','Profil & preferensi']];
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return {...clone(defaults),...x,profile:{...defaults.profile,...(x.profile||{})},settings:{...defaults.settings,...(x.settings||{})},focus:{...defaults.focus,...(x.focus||{})},analytics:{...defaults.analytics,...(x.analytics||{})}}}catch{return clone(defaults)}}
let state=window.state=load();let route=location.hash.slice(1)||'home';let timerId=null;
function save(){localStorage.setItem(KEY,JSON.stringify(state));window.state=state}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(n){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0)}
function toast(msg){const d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function go(r){route=r;location.hash=r;closeOverlay();render()}
window.addEventListener('hashchange',()=>{route=location.hash.slice(1)||'home';render()});
function header(k,t,s,action=''){return `<div class="eyebrow">${esc(k)}</div><div class="card-head"><div><h1 class="title">${esc(t)}</h1><p class="subtitle">${esc(s)}</p></div>${action}</div>`}
function shell(content){const p=state.profile;const mobile=[['home','Home'],['tasks','Tasks'],['calendar','Calendar'],['ai','AI'],['menu','Menu']];return `<div class="app"><aside class="sidebar"><div class="brand"><span class="logo">C</span>Campusly</div><nav class="side-nav">${FEATURES.map(([r,l])=>`<button class="${route===r?'active':''}" onclick="go('${r}')"><span class="ico">${l.slice(0,1)}</span>${esc(l)}</button>`).join('')}</nav></aside><main class="main"><header class="topbar"><div class="search"><span aria-hidden="true">⌕</span><input id="globalSearch" placeholder="Cari apa aja..." autocomplete="off" onkeydown="if(event.key==='Enter')searchApp(this.value)"></div><div class="avatar">${esc((p.preferredName||p.name||'R').slice(0,1).toUpperCase())}</div></header><section class="content">${content}</section></main><nav class="mobile-nav">${mobile.map(([r,l])=>`<button class="${(route===r||(r==='menu'&&route!=='home'&&route!=='tasks'&&route!=='calendar'&&route!=='ai'))?'active':''}" onclick="${r==='menu'?'openMenu()':`go('${r}')`}"><span class="micon">${esc(l.slice(0,1))}</span>${esc(l)}</button>`).join('')}</nav></div>`}
function render(){state=window.state||state;if(!FEATURES.some(x=>x[0]===route))route='home';const fn={home,tasks,notes,schedule,calendar,semester,gpa,finance,focus,analytics,thesis,documents,tools,ai,notifications,reminders,settings}[route];document.getElementById('app').innerHTML=shell(fn?fn():'');if(route==='focus')updateTimer()}
function home(){const p=state.profile,open=state.tasks.filter(x=>!x.done),progress=Math.min(100,Math.round((Number(p.credits||0)/Math.max(1,Number(p.totalCredits||144)))*100));return `<div class="hero"><div><div class="eyebrow">TODAY</div><h1>Yo, ${esc(p.preferredName||p.name||'Rizky')} 👋</h1><p>Gas mulai hari ini. Semua kebutuhan kuliah ada di satu tempat.</p></div><div class="hero-actions"><button class="btn primary" onclick="openTask()">+ Add Task</button><button class="btn" onclick="go('ai')">✦ Tanya AI</button></div></div><div class="grid stats"><div class="card"><div class="stat-label">Semester</div><div class="stat-value">${p.semester||1}</div></div><div class="card"><div class="stat-label">GPA</div><div class="stat-value">${p.gpa?Number(p.gpa).toFixed(2):'—'}</div></div><div class="card"><div class="stat-label">Target GPA</div><div class="stat-value">${Number(p.targetGpa||3.75).toFixed(2)}</div></div><div class="card"><div class="stat-label">Tasks tersisa</div><div class="stat-value">${open.length}</div></div></div><div class="grid two"><div class="card"><div class="card-head"><h2>Yang harus diberesin</h2><span class="pill">${open.length} aktif</span></div>${open.slice(0,6).map(x=>`<div class="row"><div class="row-main"><div class="row-title">${esc(x.title)}</div><div class="row-meta">${esc(x.course||'Tanpa mata kuliah')} · ${esc(x.deadline||'Tanpa deadline')}</div></div></div>`).join('')||'<div class="empty">Clean slate. Belum ada tugas. 😌</div>'}</div><div class="card"><div class="card-head"><h2>Academic progress</h2><span class="pill">${p.credits||0}/${p.totalCredits||144} SKS</span></div><div class="kpi">${progress}%</div><div class="progress"><i style="width:${progress}%"></i></div><p class="muted">Progress kredit menuju kelulusan.</p><div class="actions"><button class="btn" onclick="go('gpa')">Hitung GPA</button><button class="btn" onclick="go('semester')">Kelola semester</button></div></div></div>`}
function focus(){const sec=Math.max(0,Number(state.focus.seconds||1500)),min=Math.floor(sec/60),s=sec%60;return `${header('PRODUCTIVITY','Focus','Pomodoro sederhana yang benar-benar jalan.')}<div class="grid two"><div class="card"><div class="focus-ring"><div class="timer" id="timer">${String(min).padStart(2,'0')}:${String(s).padStart(2,'0')}</div></div><div class="actions" style="justify-content:center"><button class="btn primary" onclick="toggleFocus()">${state.focus.running?'Pause':'Start'}</button><button class="btn" onclick="resetFocus()">Reset</button></div></div><div class="card"><h2>Focus stats</h2><div class="kpi">${Math.round((state.analytics.focusSeconds||0)/60)}m</div><p class="muted">Total waktu fokus tersimpan.</p><button class="btn" onclick="go('analytics')">Lihat analytics</button></div></div>`}
function updateTimer(){clearInterval(timerId);if(!state.focus.running)return;timerId=setInterval(()=>{if(state.focus.seconds<=0){state.focus.running=false;state.analytics.focusSeconds=(state.analytics.focusSeconds||0)+1500;state.focus.seconds=1500;save();toast('Focus selesai. Istirahat dulu.');render();return}state.focus.seconds--;save();const el=document.getElementById('timer');if(el){const m=Math.floor(state.focus.seconds/60),s=state.focus.seconds%60;el.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}},1000)}
function toggleFocus(){state.focus.running=!state.focus.running;save();render()}
function resetFocus(){state.focus.running=false;state.focus.seconds=1500;save();render()}
function analytics(){const mins=Math.round((state.analytics.focusSeconds||0)/60),done=state.tasks.filter(x=>x.done).length,total=state.tasks.length;return `${header('INSIGHTS','Analytics','Progress kuliah dan produktivitas lo.')}<div class="grid three"><div class="card"><div class="stat-label">Focus time</div><div class="stat-value">${mins}m</div></div><div class="card"><div class="stat-label">Task selesai</div><div class="stat-value">${done}</div></div><div class="card"><div class="stat-label">Completion</div><div class="stat-value">${total?Math.round(done/total*100):0}%</div></div></div>`}
function thesis(){const a=state.thesisProjects||[];return `${header('ACADEMIC','Thesis','Tracking proyek skripsi / penelitian.',`<button class="btn primary" onclick="openThesis()">+ Add Project</button>`)}<div class="grid two">${a.map((x,i)=>`<div class="card"><div class="card-head"><h2>${esc(x.title)}</h2><span class="pill">${esc(x.status||'Planning')}</span></div><p class="muted">${esc(x.supervisor||'Pembimbing belum diisi')}</p><div class="progress"><i style="width:${Math.max(0,Math.min(100,Number(x.progress)||0))}%"></i></div><p class="muted">${Number(x.progress)||0}%</p><button class="btn small danger" onclick="deleteItem('thesisProjects',${i})">Hapus</button></div>`).join('')||'<div class="card"><div class="empty">Belum ada proyek.</div></div>'}</div>`}
function documents(){return `${header('WORKSPACE','Documents','Buka file teks langsung dari HP atau komputer.')}<div class="card"><div class="field"><label>Pilih file</label><input type="file" accept=".txt,.md,.csv,.json,.html,.htm,text/*" onchange="readDocument(this)"></div><pre id="docOut" class="doc" style="margin-top:12px;white-space:pre-wrap">Belum ada file.</pre></div>`}
function readDocument(input){const f=input.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{document.getElementById('docOut').textContent=String(r.result||'')};r.readAsText(f)}
function tools(){return `${header('TOOLS','Academic Tools','Alat kecil yang sering kepakai.')}<div class="grid three"><div class="card"><h2>Target GPA</h2><p class="muted">${gpaTargetText()}</p><button class="btn" onclick="go('gpa')">Buka GPA</button></div><div class="card"><h2>Task planner</h2><p class="muted">Urutkan tugas berdasarkan deadline.</p><button class="btn" onclick="sortTasks()">Urutkan</button></div><div class="card"><h2>Study plan</h2><p class="muted">Buat rencana belajar dari tugas lo.</p><button class="btn" onclick="askAI('Buatkan rencana belajar 7 hari dari tugas saya.')">Buat dengan AI</button></div></div>`}
function gpaTargetText(){const g=Number(state.profile.gpa||0),t=Number(state.profile.targetGpa||3.75);return g?`Sekarang ${g.toFixed(2)}, target ${t.toFixed(2)}.`:`Target ${t.toFixed(2)}. Isi GPA untuk analisis.`}
function ai(){const msgs=state.aiMessages||[{role:'assistant',text:'Halo. Gue Campusly AI. Tanya soal tugas, jadwal, GPA, atau minta bikin rencana belajar.'}];return `${header('ASSISTANT','Campusly AI','Asisten akademik yang tahu konteks data Campusly lo.')}<div class="card"><div class="chat">${msgs.map(m=>`<div class="bubble ${m.role==='user'?'me':''}">${esc(m.text)}</div>`).join('')}</div><div class="ai-box"><textarea id="aiInput" placeholder="Contoh: susun prioritas tugas gue minggu ini..."></textarea><button class="btn primary" onclick="sendAI()">Kirim</button></div><div class="actions" style="margin-top:10px"><button class="btn small" onclick="askAI('Apa yang harus saya kerjakan dulu hari ini?')">Prioritas hari ini</button><button class="btn small" onclick="askAI('Buatkan jadwal belajar minggu ini.')">Study plan</button><button class="btn small" onclick="askAI('Analisis kondisi GPA saya.')">Analisis GPA</button></div></div>`}
async function sendAI(){const el=document.getElementById('aiInput');const q=el?.value.trim();if(q)await askAI(q)}
async function askAI(q){state.aiMessages=state.aiMessages||[];state.aiMessages.push({role:'user',text:q});save();render();const token=localStorage.getItem('campusly_token');if(token){try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({messages:[{role:'system',content:aiContext()},{role:'user',content:q}]})});const d=await r.json();if(r.ok&&d.text){state.aiMessages.push({role:'assistant',text:d.text});save();render();return}}catch(e){}}setTimeout(()=>{state.aiMessages.push({role:'assistant',text:localAI(q)});save();render()},250)}
function aiContext(){return `Kamu Campusly AI. Bahasa Indonesia santai. Data mahasiswa: semester ${state.profile.semester}, GPA ${state.profile.gpa||'belum ada'}, target ${state.profile.targetGpa}, tugas aktif ${state.tasks.filter(x=>!x.done).length}, mata kuliah ${state.courses.map(x=>x.name).join(', ')||'belum ada'}. Beri jawaban praktis dan jangan mengarang data.`}
function localAI(q){const l=q.toLowerCase(),open=state.tasks.filter(x=>!x.done).sort((a,b)=>String(a.deadline||'9999').localeCompare(String(b.deadline||'9999')));if(l.includes('prioritas')||l.includes('kerjakan dulu'))return open.length?`Mulai dari: ${open.slice(0,3).map(x=>x.title).join(', ')}.`:'Belum ada tugas aktif. Tambahkan task dulu.';if(l.includes('gpa'))return gpaTargetText();if(l.includes('jadwal')||l.includes('study plan')||l.includes('belajar'))return 'Rencana cepat: 2 sesi fokus per hari, prioritaskan deadline terdekat, sisakan satu sesi untuk review materi.';return 'Gue bisa bantu dari data Campusly lo. Coba tanya prioritas tugas, GPA, jadwal belajar, atau minta study plan.'}
function notifications(){return `${header('SYSTEM','Notifications','Pusat aktivitas dan pengingat.')}<div class="card">${state.notifications?.length?state.notifications.map(n=>`<div class="row"><div class="row-main"><div class="row-title">${esc(n.title||'Notifikasi')}</div><div class="row-meta">${esc(n.body||'')}</div></div></div>`).join(''):'<div class="empty">Belum ada notifikasi.</div>'}</div>`}
function menu(){return `${header('NAVIGATION','Menu','Semua fitur Campusly.')}<div class="menu-sheet">${FEATURES.filter(x=>!['home','tasks','calendar','ai'].includes(x[0])).map(([r,l,d])=>`<button class="menu-item" onclick="go('${r}')"><b>${esc(l)}</b><span>${esc(d)}</span></button>`).join('')}</div>`}
function openMenu(){overlay('Menu',menu().replace(/<div class="eyebrow">NAVIGATION<\/div><div class="card-head">[\s\S]*?<\/div>/,''))}
function overlay(title,body){document.getElementById('overlay')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="overlay" id="overlay" onclick="if(event.target===this)closeOverlay()"><div class="modal"><div class="card-head"><h2>${esc(title)}</h2><button class="btn small" onclick="closeOverlay()">Tutup</button></div>${body}</div></div>`)}
function closeOverlay(){document.getElementById('overlay')?.remove()}
function sortTasks(){state.tasks.sort((a,b)=>String(a.deadline||'9999').localeCompare(String(b.deadline||'9999')));save();go('tasks')}
function deleteItem(key,i){if(Array.isArray(state[key])){state[key].splice(i,1);save();render()}}
function resetData(){if(confirm('Reset semua data Campusly di browser ini?')){localStorage.removeItem(KEY);state=clone(defaults);window.state=state;render();toast('Data direset')}}

/* ================= MERGED NON-AI FEATURE CORE ================= */
(function(){
  'use strict';
  const KEY='campusly_state_v1';
  const $$=s=>Array.from(document.querySelectorAll(s));
  const escv=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid=()=>Date.now()+Math.floor(Math.random()*10000);
  const today=()=>new Date().toISOString().slice(0,10);
  const daysLeft=d=>d?Math.ceil((new Date(d+'T00:00:00')-new Date(today()+'T00:00:00'))/86400000):null;
  const fmt=d=>{if(!d)return 'Tanpa deadline';const x=new Date(d+'T00:00:00');return isNaN(x)?d:x.toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'})};
  function normalize(){const s=window.state||{};['tasks','notes','schedule','calendarEvents','courses','gpaRecords','finance','budgets','reminders','notifications','attendance','documents'].forEach(k=>{if(!Array.isArray(s[k]))s[k]=[]});s.profile=s.profile||{};s.settings=s.settings||{};s.analytics=s.analytics||{focusSeconds:0,focusHistory:[]};s.focus=s.focus||{seconds:1500,running:false,session:0};s.profile.semester=Number(s.profile.semester||1);s.profile.targetGpa=Number(s.profile.targetGpa||3.75);s.profile.totalCredits=Number(s.profile.totalCredits||144);s.profile.credits=Number(s.profile.credits||0);s.tasks.forEach((t,i)=>{t.id=t.id??uid()+i;t.priority=t.priority||'MEDIUM';t.subtasks=Array.isArray(t.subtasks)?t.subtasks:[]});s.courses.forEach((c,i)=>{c.id=c.id??uid()+i;c.credits=Number(c.credits||0)});s.schedule.forEach((c,i)=>{c.id=c.id??uid()+i});window.state=s;state=s;return s}
  const S=()=>normalize();
  function persist(msg){state=window.state;localStorage.setItem(KEY,JSON.stringify(window.state));if(msg&&window.toast)window.toast(msg);if(window.render)window.render()}
  function close(){document.getElementById('cp-modal')?.remove()}
  function modal(title,body,onSubmit){close();const d=document.createElement('div');d.id='cp-modal';d.className='cp-modal';d.innerHTML=`<div class="cp-backdrop"></div><div class="cp-dialog" role="dialog" aria-modal="true"><div class="cp-head"><h2>${escv(title)}</h2><button type="button" class="cp-x" aria-label="Tutup">×</button></div><form id="cp-form"><div class="cp-body">${body}</div><div class="cp-actions"><button type="button" class="btn" id="cp-cancel">Batal</button><button class="btn primary">Simpan</button></div></form></div>`;document.body.appendChild(d);d.querySelector('.cp-x').onclick=close;d.querySelector('.cp-backdrop').onclick=close;d.querySelector('#cp-cancel').onclick=close;d.querySelector('form').onsubmit=e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget),e.currentTarget)};setTimeout(()=>d.querySelector('input,textarea,select')?.focus(),20)}
  const field=(label,name,value='',type='text',attrs='')=>`<label class="cp-field"><span>${escv(label)}</span><input name="${escv(name)}" type="${type}" value="${escv(value)}" ${attrs}></label>`;
  const area=(label,name,value='')=>`<label class="cp-field"><span>${escv(label)}</span><textarea name="${escv(name)}" rows="7">${escv(value)}</textarea></label>`;
  const sel=(label,name,value,opts)=>`<label class="cp-field"><span>${escv(label)}</span><select name="${escv(name)}">${opts.map(o=>`<option value="${escv(o[0])}" ${String(o[0])===String(value)?'selected':''}>${escv(o[1])}</option>`).join('')}</select></label>`;
  const empty=t=>`<div class="cp-empty">${t}</div>`;
  function dueBadge(t){const d=daysLeft(t.deadline);if(t.done||d===null)return '';if(d<0)return `<span class="cp-due late">${Math.abs(d)} hari terlambat</span>`;if(d===0)return `<span class="cp-due late">Hari ini</span>`;if(d===1)return `<span class="cp-due soon">Besok</span>`;if(d<=3)return `<span class="cp-due soon">${d} hari lagi</span>`;return `<span class="cp-due">${d} hari lagi</span>`}
  function taskCard(t){const subs=t.subtasks||[],done=subs.filter(x=>x.done).length;return `<article class="cp-task ${t.done?'is-done':''}"><button class="cp-check ${t.done?'checked':''}" onclick="cpTaskToggle(${t.id})" aria-label="Selesaikan tugas">${t.done?'✓':''}</button><div class="cp-task-main"><div class="cp-task-title">${escv(t.title)}</div><div class="cp-task-meta">${escv(t.course||'Tanpa mata kuliah')} · ${fmt(t.deadline)} · ${escv(t.priority||'MEDIUM')} ${dueBadge(t)}</div>${subs.length?`<div class="cp-subbar"><span>${done}/${subs.length} subtasks</span><i><b style="width:${Math.round(done/subs.length*100)}%"></b></i></div>`:''}</div><div class="cp-task-actions"><button class="btn small" onclick="cpEditTask(${t.id})">Edit</button><button class="btn small danger" onclick="cpDeleteTask(${t.id})">Hapus</button></div></article>`}
  function taskModal(edit){const s=S(),t=s.tasks.find(x=>Number(x.id)===Number(edit))||{},subs=(t.subtasks||[]).map(x=>x.title||x).join('\n');modal(edit?'Edit tugas':'Tambah tugas',`${field('Judul tugas','title',t.title||'','text','required')}${field('Mata kuliah','course',t.course||'')}${field('Deadline','deadline',t.deadline||'','date')}${sel('Prioritas','priority',t.priority||'MEDIUM',[['HIGH','Tinggi'],['MEDIUM','Sedang'],['LOW','Rendah']])}${field('Estimasi (menit)','estimate',t.estimate||60,'number','min="5" step="5"')}${area('Subtask — satu per baris','subtasks',subs)}`,(f)=>{const old=s.tasks.find(x=>Number(x.id)===Number(edit)),o={id:edit?Number(edit):uid(),title:String(f.get('title')||'').trim(),course:String(f.get('course')||'').trim(),deadline:String(f.get('deadline')||''),priority:String(f.get('priority')||'MEDIUM'),estimate:Number(f.get('estimate')||60),done:!!old?.done,subtasks:String(f.get('subtasks')||'').split('\n').map(x=>x.trim()).filter(Boolean).map((x,i)=>({id:old?.subtasks?.[i]?.id||uid()+i,title:x,done:!!old?.subtasks?.[i]?.done}))};if(!o.title)return;if(edit){const i=s.tasks.findIndex(x=>Number(x.id)===Number(edit));if(i>=0)s.tasks[i]=o}else s.tasks.unshift(o);close();persist(edit?'Tugas diperbarui':'Tugas ditambahkan')})}
  window.openTask=()=>taskModal();window.cpEditTask=id=>taskModal(id);window.cpTaskToggle=id=>{const s=S(),t=s.tasks.find(x=>Number(x.id)===Number(id));if(!t)return;t.done=!t.done;if(t.done)t.completedAt=new Date().toISOString();persist(t.done?'Task selesai 🔥':'Task dibuka lagi')};window.cpDeleteTask=id=>{if(!confirm('Hapus tugas ini?'))return;const s=S();s.tasks=s.tasks.filter(x=>Number(x.id)!==Number(id));persist('Tugas dihapus')};
  window.tasks=function(){return `${header('WORKSPACE','Tasks','Deadline, prioritas, subtasks, dan progres pengerjaan.',`<button class="btn primary" onclick="openTask()">＋ Add Task</button>`)}<div class="cp-toolbar"><input id="cp-tq" placeholder="Cari tugas atau mata kuliah..." oninput="cpRenderTasks()"><select id="cp-tf" onchange="cpRenderTasks()"><option value="all">Semua</option><option value="open">Belum selesai</option><option value="done">Selesai</option><option value="soon">≤ 3 hari</option><option value="late">Terlambat</option></select><select id="cp-to" onchange="cpRenderTasks()"><option value="deadline">Deadline</option><option value="priority">Prioritas</option><option value="new">Terbaru</option></select></div><div id="cp-task-list" class="cp-task-list"></div>`};
  window.cpRenderTasks=function(){const s=S(),q=(document.getElementById('cp-tq')?.value||'').toLowerCase(),f=document.getElementById('cp-tf')?.value||'all',o=document.getElementById('cp-to')?.value||'deadline';let a=s.tasks.filter(t=>!q||`${t.title} ${t.course||''}`.toLowerCase().includes(q));a=a.filter(t=>f==='all'||f==='open'&&!t.done||f==='done'&&t.done||f==='soon'&&!t.done&&daysLeft(t.deadline)>=0&&daysLeft(t.deadline)<=3||f==='late'&&!t.done&&daysLeft(t.deadline)<0);if(o==='deadline')a.sort((x,y)=>(x.done-y.done)||(x.deadline||'9999').localeCompare(y.deadline||'9999'));if(o==='new')a.sort((x,y)=>(y.id||0)-(x.id||0));if(o==='priority'){const p={HIGH:0,MEDIUM:1,LOW:2};a.sort((x,y)=>(p[x.priority]??1)-(p[y.priority]??1))}const el=document.getElementById('cp-task-list');if(el)el.innerHTML=a.map(taskCard).join('')||empty('Nggak ada tugas yang cocok.')};
  window.notes=function(){return `${header('WORKSPACE','Notes','Catatan yang gampang dicari dan nggak hilang di tengah semester.',`<button class="btn primary" onclick="cpNewNote()">＋ Add Note</button>`)}<div class="cp-toolbar"><input id="cp-nq" placeholder="Cari catatan..." oninput="cpRenderNotes()"></div><div id="cp-note-grid" class="grid three"></div>`};
  window.cpRenderNotes=function(){const s=S(),q=(document.getElementById('cp-nq')?.value||'').toLowerCase(),a=s.notes.filter(n=>!q||`${n.title} ${n.body||''}`.toLowerCase().includes(q)),el=document.getElementById('cp-note-grid');if(el)el.innerHTML=a.map(n=>`<article class="card cp-note"><div class="card-head"><h2>${escv(n.title||'Tanpa judul')}</h2><div class="actions"><button class="btn small" onclick="cpEditNote(${n.id})">Edit</button><button class="btn small danger" onclick="cpDeleteNote(${n.id})">Hapus</button></div></div><p class="muted">${escv(n.body||'')}</p></article>`).join('')||empty('Belum ada catatan.')};
  function noteModal(id){const s=S(),n=s.notes.find(x=>Number(x.id)===Number(id))||{};modal(id?'Edit catatan':'Catatan baru',`${field('Judul','title',n.title||'','text','required')}${area('Isi','body',n.body||'')}`,(f)=>{const o={id:id?Number(id):uid(),title:String(f.get('title')||'').trim(),body:String(f.get('body')||''),updatedAt:new Date().toISOString()};if(id){const i=s.notes.findIndex(x=>Number(x.id)===Number(id));if(i>=0)s.notes[i]=o}else s.notes.unshift(o);close();persist('Catatan tersimpan')})}
  window.cpNewNote=()=>noteModal();window.openNote=()=>noteModal();window.cpEditNote=id=>noteModal(id);window.cpDeleteNote=id=>{if(!confirm('Hapus catatan ini?'))return;const s=S();s.notes=s.notes.filter(x=>Number(x.id)!==Number(id));persist('Catatan dihapus')};
  function conflict(candidate,ignore){const a=String(candidate.start||''),b=String(candidate.end||'');if(!a||!b||a>=b)return 'Jam mulai/selesai tidak valid.';for(const x of S().schedule){if(Number(x.id)===Number(ignore)||x.day!==candidate.day)continue;if(a<String(x.end||'')&&b>String(x.start||''))return `Bentrok dengan ${x.name} (${x.start}–${x.end}).`}return ''}
  function classModal(id){const s=S(),c=s.schedule.find(x=>Number(x.id)===Number(id))||{};modal(id?'Edit kelas':'Tambah kelas',`${field('Mata kuliah','name',c.name||'','text','required')}${sel('Hari','day',c.day||'Senin',['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu'].map(x=>[x,x]))}${field('Mulai','start',c.start||'08:00','time','required')}${field('Selesai','end',c.end||'10:00','time','required')}${field('Ruangan','room',c.room||'')}${field('Dosen','lecturer',c.lecturer||'')}`,(f)=>{const o={id:id?Number(id):uid(),name:String(f.get('name')||'').trim(),day:String(f.get('day')||''),start:String(f.get('start')||''),end:String(f.get('end')||''),room:String(f.get('room')||''),lecturer:String(f.get('lecturer')||'')},err=conflict(o,id);if(err){toast(err);return}if(id){const i=s.schedule.findIndex(x=>Number(x.id)===Number(id));if(i>=0)s.schedule[i]=o}else s.schedule.push(o);close();persist('Jadwal tersimpan')})}
  window.openClass=()=>classModal();window.cpEditClass=id=>classModal(id);window.schedule=function(){const s=S(),days=['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu'];return `${header('ACADEMIC','Jadwal','Jadwal mingguan, deteksi bentrok, dan absensi.',`<button class="btn primary" onclick="openClass()">＋ Add Class</button>`)}<div class="cp-week">${days.map(day=>{const a=s.schedule.filter(x=>x.day===day).sort((x,y)=>String(x.start).localeCompare(String(y.start)));return `<section class="card"><div class="card-head"><h2>${day}</h2><span class="pill">${a.length} kelas</span></div>${a.map(c=>{const at=s.attendance.find(x=>Number(x.classId)===Number(c.id))||{present:0,absent:0},total=at.present+at.absent;return `<div class="cp-class"><div><b>${escv(c.name)}</b><span>${escv(c.start)}–${escv(c.end)} · ${escv(c.room||'')}</span><small>${escv(c.lecturer||'Dosen belum diisi')} · Kehadiran ${total?Math.round(at.present/total*100):0}%</small></div><div class="cp-class-actions"><button class="btn small" onclick="cpAttend(${c.id},1)">Hadir</button><button class="btn small" onclick="cpAttend(${c.id},0)">Alpa</button><button class="btn small" onclick="cpEditClass(${c.id})">Edit</button><button class="btn small danger" onclick="cpDeleteClass(${c.id})">Hapus</button></div></div>`}).join('')||empty('Tidak ada kelas')}</section>`}).join('')}</div>`};
  window.cpAttend=(id,p)=>{const s=S();let a=s.attendance.find(x=>Number(x.classId)===Number(id));if(!a){a={classId:Number(id),present:0,absent:0};s.attendance.push(a)}p?a.present++:a.absent++;persist(p?'Kehadiran dicatat':'Alpa dicatat')};window.cpDeleteClass=id=>{if(!confirm('Hapus jadwal ini?'))return;const s=S();s.schedule=s.schedule.filter(x=>Number(x.id)!==Number(id));s.attendance=s.attendance.filter(x=>Number(x.classId)!==Number(id));persist('Jadwal dihapus')};
  let calMonth=new Date();window.calendar=function(){const s=S(),y=calMonth.getFullYear(),m=calMonth.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),now=new Date();let cells='';for(let i=0;i<42;i++){const n=i-first+1;if(n<1||n>days){cells+=`<div class="cal-cell muted-day"><b>${n<1?new Date(y,m,0).getDate()+n:n-days}</b></div>`;continue}const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`,events=[...s.calendarEvents.map((e,i)=>({...e,__i:i})).filter(e=>e.date===iso),...s.tasks.filter(t=>t.deadline===iso).map(t=>({title:'📝 '+t.title,task:true}))];cells+=`<div class="cal-cell ${now.getFullYear()===y&&now.getMonth()===m&&now.getDate()===n?'today':''}"><b>${n}</b>${events.slice(0,4).map(e=>`<div class="event ${e.task?'task-event':''}" ${e.task?'':'onclick="cpEditEvent('+e.__i+')"'}>${escv(e.title)}</div>`).join('')}${events.length>4?`<small>+${events.length-4} lagi</small>`:''}</div>`}return `${header('PLANNER','Calendar',calMonth.toLocaleDateString('id-ID',{month:'long',year:'numeric'}),`<div class="actions"><button class="btn" onclick="cpCal(-1)">‹</button><button class="btn" onclick="cpCal(0)">Hari ini</button><button class="btn" onclick="cpCal(1)">›</button><button class="btn primary" onclick="cpNewEvent()">＋ Event</button></div>`)}<div class="card calendar"><div class="cal-head">${['Min','Sen','Sel','Rab','Kam','Jum','Sab'].map(x=>`<div>${x}</div>`).join('')}</div><div class="cal-grid">${cells}</div></div>`};
  window.cpCal=d=>{calMonth=d===0?new Date():new Date(calMonth.getFullYear(),calMonth.getMonth()+d,1);render()};function eventModal(id){const s=S(),e=s.calendarEvents[Number(id)]||{};modal(id!=null?'Edit event':'Tambah event',`${field('Judul','title',e.title||'','text','required')}${field('Tanggal','date',e.date||today(),'date','required')}`,(f)=>{const o={title:String(f.get('title')||'').trim(),date:String(f.get('date')||'')};if(id!=null)s.calendarEvents[Number(id)]=o;else s.calendarEvents.push({...o,id:uid()});close();persist('Event tersimpan')})}window.cpNewEvent=()=>eventModal();window.cpEditEvent=id=>eventModal(id);
  window.semester=function(){const s=S(),total=s.courses.reduce((a,x)=>a+Number(x.credits||0),0);return `${header('ACADEMIC','Semester',`${s.courses.length} mata kuliah · ${total} SKS`,`<button class="btn primary" onclick="cpNewCourse()">＋ Add Course</button>`)}<div class="card">${s.courses.map(c=>`<div class="row"><div class="row-main"><div class="row-title">${escv(c.name)} ${c.code?`· ${escv(c.code)}`:''}</div><div class="row-meta">${Number(c.credits)||0} SKS · ${escv(c.lecturer||'Dosen belum diisi')}</div></div><button class="btn small" onclick="cpEditCourse(${c.id})">Edit</button><button class="btn small danger" onclick="cpDeleteCourse(${c.id})">Hapus</button></div>`).join('')||empty('Belum ada mata kuliah.')}</div>`};
  function courseModal(id){const s=S(),c=s.courses.find(x=>Number(x.id)===Number(id))||{};modal(id?'Edit mata kuliah':'Tambah mata kuliah',`${field('Nama','name',c.name||'','text','required')}${field('Kode','code',c.code||'')}${field('SKS','credits',c.credits||3,'number','min="1" max="12" required')}${field('Dosen','lecturer',c.lecturer||'')}`,(f)=>{const o={id:id?Number(id):uid(),name:String(f.get('name')||'').trim(),code:String(f.get('code')||'').trim(),credits:Number(f.get('credits')||0),lecturer:String(f.get('lecturer')||'').trim()};if(id){const i=s.courses.findIndex(x=>Number(x.id)===Number(id));if(i>=0)s.courses[i]=o}else s.courses.push(o);close();persist('Mata kuliah tersimpan')})}window.cpNewCourse=()=>courseModal();window.cpEditCourse=id=>courseModal(id);window.cpDeleteCourse=id=>{if(!confirm('Hapus mata kuliah?'))return;const s=S();s.courses=s.courses.filter(x=>Number(x.id)!==Number(id));persist('Mata kuliah dihapus')};
  function gradeModal(id){const s=S(),g=s.gpaRecords[Number(id)]||{};modal(id!=null?'Edit nilai':'Tambah nilai',`${field('Mata kuliah','name',g.name||'','text','required')}${field('SKS','credits',g.credits||3,'number','min="1" max="12" required')}${field('Nilai GPA 0–4','grade',g.grade??4,'number','min="0" max="4" step="0.01" required')}`,(f)=>{const o={name:String(f.get('name')||'').trim(),credits:Number(f.get('credits')||0),grade:Number(f.get('grade')||0)};if(id!=null)s.gpaRecords[Number(id)]=o;else s.gpaRecords.push(o);const cr=s.gpaRecords.reduce((a,x)=>a+x.credits,0);s.profile.gpa=cr?s.gpaRecords.reduce((a,x)=>a+x.credits*x.grade,0)/cr:0;close();persist('Nilai tersimpan')})}
  window.openGrade=()=>gradeModal();window.cpEditGrade=id=>gradeModal(id);window.gpa=function(){const s=S(),r=s.gpaRecords,total=r.reduce((a,x)=>a+x.credits*x.grade,0),cr=r.reduce((a,x)=>a+x.credits,0),g=cr?total/cr:Number(s.profile.gpa||0),target=Number(s.profile.targetGpa||3.75);return `${header('ACADEMIC','GPA','IPK semester dari data nilai yang lo masukkan.',`<button class="btn primary" onclick="openGrade()">＋ Add Nilai</button>`)}<div class="grid two"><div class="card"><div class="stat-label">GPA sekarang</div><div class="stat-value">${g?g.toFixed(2):'—'}</div><p class="muted">${cr} SKS tercatat</p></div><div class="card"><div class="stat-label">Target GPA</div><div class="stat-value">${target.toFixed(2)}</div><p class="muted">${g>=target?'Target tercapai 🎯':`Kurang ${(target-g).toFixed(2)} poin`}</p></div></div><div class="card">${r.map((x,i)=>`<div class="row"><div class="row-main"><div class="row-title">${escv(x.name)}</div><div class="row-meta">${x.credits} SKS · ${Number(x.grade).toFixed(2)}</div></div><button class="btn small" onclick="cpEditGrade(${i})">Edit</button><button class="btn small danger" onclick="cpDeleteGrade(${i})">Hapus</button></div>`).join('')||empty('Belum ada nilai.')}</div>`};window.cpDeleteGrade=i=>{if(!confirm('Hapus nilai?'))return;const s=S();s.gpaRecords.splice(i,1);const cr=s.gpaRecords.reduce((a,x)=>a+x.credits,0);s.profile.gpa=cr?s.gpaRecords.reduce((a,x)=>a+x.credits*x.grade,0)/cr:0;persist('Nilai dihapus')};
  window.finance=function(){const s=S(),inc=s.finance.filter(x=>x.type==='in').reduce((a,x)=>a+Number(x.amount||0),0),out=s.finance.filter(x=>x.type==='out').reduce((a,x)=>a+Number(x.amount||0),0);return `${header('LIFE','Finance','Pemasukan, pengeluaran, dan saldo pribadi.',`<button class="btn primary" onclick="cpNewFinance()">＋ Transaksi</button>`)}<div class="grid three"><div class="card"><div class="stat-label">Pemasukan</div><div class="stat-value">${money(inc)}</div></div><div class="card"><div class="stat-label">Pengeluaran</div><div class="stat-value">${money(out)}</div></div><div class="card"><div class="stat-label">Saldo</div><div class="stat-value">${money(inc-out)}</div></div></div><div class="card">${s.finance.slice().reverse().map((x,i)=>`<div class="row"><div class="row-main"><div class="row-title">${escv(x.title||'Transaksi')}</div><div class="row-meta">${x.type==='in'?'+':'−'} ${money(x.amount)} · ${fmt(x.date)}</div></div><button class="btn small danger" onclick="cpDeleteFinance(${s.finance.length-1-i})">Hapus</button></div>`).join('')||empty('Belum ada transaksi.')}</div>`};window.cpNewFinance=()=>modal('Tambah transaksi',`${field('Nama','title','','text','required')}${sel('Tipe','type','out',[['out','Pengeluaran'],['in','Pemasukan']])}${field('Nominal','amount',0,'number','min="0" required')}${field('Tanggal','date',today(),'date','required')}`,(f)=>{const s=S();s.finance.push({id:uid(),title:String(f.get('title')||''),type:String(f.get('type')||'out'),amount:Number(f.get('amount')||0),date:String(f.get('date')||today())});close();persist('Transaksi tersimpan')});window.cpDeleteFinance=i=>{if(!confirm('Hapus transaksi?'))return;const s=S();s.finance.splice(i,1);persist('Transaksi dihapus')};
  window.reminders=function(){const s=S();return `${header('PRODUCTIVITY','Reminders','Pengingat pribadi supaya tugas nggak kelewat.',`<button class="btn primary" onclick="cpNewReminder()">＋ Reminder</button>`)}<div class="card">${s.reminders.map((r,i)=>`<div class="row"><button class="check ${r.done?'done':''}" onclick="cpToggleReminder(${i})">${r.done?'✓':''}</button><div class="row-main"><div class="row-title ${r.done?'done-text':''}">${escv(r.title)}</div><div class="row-meta">${fmt(r.date)}${r.time?' · '+escv(r.time):''}</div></div><button class="btn small danger" onclick="cpDeleteReminder(${i})">Hapus</button></div>`).join('')||empty('Belum ada reminder.')}</div>`};window.cpNewReminder=()=>modal('Tambah reminder',`${field('Judul','title','','text','required')}${field('Tanggal','date',today(),'date','required')}${field('Jam','time','08:00','time')}`,(f)=>{const s=S();s.reminders.push({id:uid(),title:String(f.get('title')||''),date:String(f.get('date')||today()),time:String(f.get('time')||''),done:false});close();persist('Reminder dibuat')});window.cpToggleReminder=i=>{const s=S();if(s.reminders[i])s.reminders[i].done=!s.reminders[i].done;persist()};window.cpDeleteReminder=i=>{if(!confirm('Hapus reminder?'))return;const s=S();s.reminders.splice(i,1);persist('Reminder dihapus')};
  function backupDownload(){const blob=new Blob([JSON.stringify(window.state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`campusly-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function importBackup(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>{const f=input.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x||typeof x!=='object')throw Error();window.state={...window.state,...x};state=window.state;normalize();persist('Backup berhasil dipulihkan')}catch{toast('File backup tidak valid.')}};r.readAsText(f)};input.click()}
  window.settings=function(){const s=S(),p=s.profile;return `${header('SETTINGS','Settings','Profil, preferensi, dan keamanan data.',`<button class="btn primary" onclick="cpSaveProfile()">Simpan profil</button>`)}<div class="grid two"><div class="card"><h2>Profil mahasiswa</h2>${field('Nama','cp-name',p.name||'')}${field('Nama panggilan','cp-preferred',p.preferredName||'')}${field('Universitas','cp-university',p.university||'')}${field('Jurusan','cp-major',p.major||'')}${field('Semester','cp-semester',p.semester||1,'number','min="1" max="20"')}${field('Target GPA','cp-target',p.targetGpa||3.75,'number','min="0" max="4" step="0.01"')}${field('Total SKS kelulusan','cp-total',p.totalCredits||144,'number','min="1"')}</div><div class="card"><h2>Data</h2><p class="muted">Semua data inti tersimpan lokal di perangkat ini.</p><div class="actions cp-stack"><button class="btn" onclick="cpBackup()">↓ Export backup</button><button class="btn" onclick="cpImport()">↑ Import backup</button><button class="btn danger" onclick="cpReset()">Reset semua data</button></div><hr><h3>Privasi</h3><p class="muted">Jangan masukkan password, API key, atau data sensitif ke catatan Campusly.</p></div></div>`};window.cpSaveProfile=()=>{const s=S(),get=n=>document.querySelector(`[name="${n}"]`)?.value||'';s.profile.name=get('cp-name');s.profile.preferredName=get('cp-preferred');s.profile.university=get('cp-university');s.profile.major=get('cp-major');s.profile.semester=Number(get('cp-semester')||1);s.profile.targetGpa=Number(get('cp-target')||3.75);s.profile.totalCredits=Number(get('cp-total')||144);persist('Profil disimpan')};window.cpBackup=backupDownload;window.cpImport=importBackup;window.cpReset=()=>{if(!confirm('Reset SEMUA data Campusly di perangkat ini? Ini tidak bisa dibatalkan.'))return;localStorage.removeItem(KEY);location.reload()};
  window.searchApp=function(q){q=String(q||'').trim().toLowerCase();if(!q){toast('Ketik sesuatu untuk mencari.');return}const s=S(),hits=[['Tasks',s.tasks.filter(x=>`${x.title} ${x.course||''}`.toLowerCase().includes(q)),'tasks'],['Notes',s.notes.filter(x=>`${x.title} ${x.body||''}`.toLowerCase().includes(q)),'notes'],['Mata kuliah',s.courses.filter(x=>`${x.name} ${x.code||''} ${x.lecturer||''}`.toLowerCase().includes(q)),'semester']].flatMap(([g,a,r])=>a.slice(0,5).map(x=>({g,r,label:g==='Tasks'?x.title:g==='Notes'?x.title:x.name})));modal(`Hasil pencarian · “${q}”`,hits.length?hits.map(h=>`<button type="button" class="cp-search-hit" data-route="${h.r}"><b>${escv(h.g)}</b><span>${escv(h.label)}</span></button>`).join(''):empty('Nggak ketemu. Coba kata kunci lain.'),()=>{});$$('.cp-search-hit').forEach(b=>b.onclick=()=>{close();go(b.dataset.route)})};
  function boot(){normalize();const orig=window.render;if(orig&&!window.__cpRenderPatched){window.__cpRenderPatched=true;window.render=function(){orig();requestAnimationFrame(()=>{if(route==='tasks')cpRenderTasks();if(route==='notes')cpRenderNotes()})}}window.addEventListener('storage',e=>{if(e.key===KEY){window.state=JSON.parse(e.newValue||'{}');state=window.state;normalize();window.render?.()}});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('globalSearch')?.focus()}})}
  boot();
})();

/* Keep the runtime alive after the merged feature layer has installed its overrides. */
render();
