const http=require('http');
const fs=require('fs');
const path=require('path');
const PptxGenJS=require('pptxgenjs');
const {Document,Packer,Paragraph,TextRun,HeadingLevel,AlignmentType}=require('docx');
const PORT=Number(process.env.PORT||8787),ROOT=__dirname,MODEL='gemini-3.7-flash',MAX=16*1024*1024;
const PUBLIC=new Set(['index.html','campusly-v5.js','campusly-v5.css','manifest.webmanifest','icon.svg']);
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.webmanifest':'application/manifest+json; charset=utf-8','.svg':'image/svg+xml'};
const fail=(message,status=500)=>Object.assign(new Error(message),{status});
const hits=new Map();
function send(res,status,data,type='application/json; charset=utf-8'){const b=Buffer.isBuffer(data)?data:Buffer.from(typeof data==='string'?data:JSON.stringify(data));res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store','Content-Length':b.length,'X-Content-Type-Options':'nosniff'});res.end(b)}
function security(res){res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; frame-ancestors 'none'")}
function limited(req,n=30){const k=req.headers['x-forwarded-for']||req.socket.remoteAddress||'x';const now=Date.now(),old=hits.get(k);const v=!old||now-old.t>60000?{t:now,n:0}:old;v.n++;hits.set(k,v);return v.n<=n}
function read(req){return new Promise((ok,no)=>{let a=[],size=0;req.on('data',c=>{size+=c.length;if(size>MAX)return no(fail('Payload terlalu besar.',413));a.push(c)});req.on('end',()=>{try{ok(JSON.parse(Buffer.concat(a).toString('utf8')||'{}'))}catch{no(fail('JSON tidak valid.',400))}});req.on('error',no)})}
const strip=s=>String(s??'').replace(/\r/g,'').replace(/```(?:html|xml|markdown|text|javascript|js)?/gi,'').replace(/```/g,'').trim();
const html=s=>/<!doctype\s+html|<html[\s>]|<head[\s>]|<body[\s>]|<script[\s>]|<style[\s>]/i.test(String(s||''));
function plain(s){let v=String(s||'');if(!html(v))return v.trim();const m=v.match(/<body[^>]*>([\s\S]*?)<\/body>/i);return(m?m[1]:v).replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<style[\s\S]*?<\/style>/gi,'').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/\s{2,}/g,' ').trim()}
function instruction(mode){if(mode==='paper')return'Kamu penulis makalah akademik Indonesia. Buat lengkap, natural, objektif, rapi, dengan judul, abstrak, kata kunci, pendahuluan, pembahasan, kesimpulan, daftar pustaka. Jangan mengarang sumber/DOI/URL. Jika sumber tidak tersedia tandai perlu diverifikasi.';if(mode==='ppt')return'Kamu pembuat presentasi mahasiswa Indonesia. Buat ringkas dan mudah dipresentasikan. Format wajib setiap slide: SLIDE N: Judul lalu 3-5 bullet lalu VISUAL: deskripsi singkat. Jangan HTML atau kode.';if(mode==='translate')return'Kamu penerjemah. Terjemahkan teks apa adanya ke bahasa target, pertahankan makna, istilah, struktur, dan nada. Jangan beri komentar tambahan.';return'Kamu Campusly AI, teman kuliah mahasiswa Indonesia. Jawab pakai bahasa Indonesia yang santai, natural, dan gaya ngobrol Gen Z: pakai gue/lo kalau cocok, boleh slang ringan seperti jir, wkwk, gas, tapi jangan berlebihan. Tetap akurat dan membantu. Untuk tugas akademik, tetap rapi dan jelas. Jangan HTML, CSS, JavaScript, XML, atau source code.'}
function promptOf(d){if(typeof d.input==='string')return d.input;if(typeof d.text==='string')return d.text;if(typeof d.content==='string')return d.content;if(Array.isArray(d.messages))return d.messages.slice(-12).map(x=>`${x.role==='assistant'?'Campusly AI':'User'}: ${x.content||''}`).join('\n\n');return ''}
async function ai(d,mode='chat'){const key=String(process.env.GEMINI_API_KEY||'').trim();if(!key)throw fail('GEMINI_API_KEY belum diatur di Blitz.',503);let p=promptOf(d);if(!p.trim())throw fail('Input AI kosong.',400);if(mode==='translate'){const from=d.from||'bahasa sumber';const to=d.to||d.target||'bahasa Indonesia';p=`Terjemahkan dari ${from} ke ${to}.\n\n${p}`}const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({systemInstruction:{parts:[{text:instruction(mode)}]},contents:[{role:'user',parts:[{text:p}]}]})}).catch(e=>{throw fail(`Tidak bisa menghubungi Gemini: ${e.message}`,502)});let raw=await r.text(),j={};try{j=JSON.parse(raw)}catch{}if(!r.ok){const msg=j?.error?.message||`Gemini HTTP ${r.status}`;console.error(`[Gemini ${MODEL}] ${msg}`);throw fail(`Gemini gagal: ${msg}`,502)}const text=plain(strip(j?.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||''));if(!text)throw fail('Gemini mengembalikan jawaban kosong.',502);return text}
function runs(t){return [new TextRun({text:String(t)})]}
async function docx(res,d){const c=String(d.content||'').trim();if(!c)throw fail('Konten makalah kosong.',400);const children=c.split('\n').map(x=>{const s=x.trim();if(!s)return new Paragraph({text:''});const h=s.match(/^#{1,3}\s+(.+)/);const b=s.match(/^[-*•]\s+(.+)/);return h?new Paragraph({text:h[1],heading:HeadingLevel.HEADING_2}):b?new Paragraph({children:runs(b[1]),bullet:{level:0}}):new Paragraph({children:runs(s),alignment:AlignmentType.JUSTIFIED})});const b=await Packer.toBuffer(new Document({sections:[{children}]}));send(res,200,b,'application/vnd.openxmlformats-officedocument.wordprocessingml.document');res.setHeader('Content-Disposition','attachment; filename="campusly-makalah.docx"')}
function pdf(c){const lines=[];for(const x of c.split('\n')){let s=x.trim()||' ';while(s.length>95){lines.push(s.slice(0,95));s=s.slice(95)}lines.push(s)}const pages=[];for(let i=0;i<lines.length;i+=48)pages.push(lines.slice(i,i+48));let o=['','<< /Type /Pages /Kids [] /Count 0 >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'],ids=[];const esc=x=>String(x).replace(/\\/g,'\\\\').replace(/[()]/g,m=>'\\'+m).replace(/[^\x20-\x7E]/g,' ');for(const pg of pages){const st=['BT','/F1 11 Tf','50 790 Td','14 TL'];pg.forEach((x,i)=>{if(i)st.push('0 -14 Td');st.push(`(${esc(x)}) Tj`)});st.push('ET');const cid=o.length;o.push(`<< /Length ${Buffer.byteLength(st.join('\n'))} >>\nstream\n${st.join('\n')}\nendstream`);const pid=o.length;o.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents ${cid} 0 R >>`);ids.push(pid)}o[1]=`<< /Type /Pages /Kids [${ids.map(x=>x+' 0 R').join(' ')}] /Count ${ids.length} >>`;const cat=o.length;o.push(`<< /Type /Catalog /Pages 2 0 R >>`);let out='%PDF-1.4\n',off=[0];for(let i=1;i<o.length;i++){off[i]=Buffer.byteLength(out,'latin1');out+=`${i} 0 obj\n${o[i]}\nendobj\n`}const x=Buffer.byteLength(out,'latin1');out+=`xref\n0 ${o.length}\n0000000000 65535 f \n${off.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size ${o.length} /Root ${cat} 0 R >>\nstartxref\n${x}\n%%EOF`;return Buffer.from(out,'latin1')}
async function ppt(res,d){const c=String(d.content||'').trim();if(!c)throw fail('Konten PPT kosong.',400);const p=new PptxGenJS();p.layout='LAYOUT_WIDE';p.author='Campusly';for(const raw of c.split(/(?=SLIDE\s+\d+\s*:)/i).map(x=>x.trim()).filter(Boolean)){const s=p.addSlide(),ls=raw.split('\n').map(x=>x.trim()).filter(Boolean),title=(ls.shift()||'Campusly').replace(/^SLIDE\s+\d+\s*:\s*/i,'');s.addText(title,{x:.6,y:.45,w:12,h:.7,fontSize:26,bold:true});const bullets=ls.filter(x=>!/^VISUAL\s*:/i.test(x)).map(x=>x.replace(/^[-*•]\s*/,''));s.addText(bullets.map(x=>({text:x,options:{bullet:{indent:16}}})),{x:.8,y:1.45,w:11.5,h:4.9,fontSize:18,breakLine:true});const v=ls.find(x=>/^VISUAL\s*:/i.test(x));if(v)s.addText(v,{x:.8,y:6.4,w:11.5,h:.4,fontSize:10,italic:true})}const b=await p.write({outputType:'nodebuffer'});send(res,200,b,'application/vnd.openxmlformats-officedocument.presentationml.presentation');res.setHeader('Content-Disposition','attachment; filename="campusly-presentasi.pptx"')}
function serve(res,p){const f=p==='/'?'index.html':p.slice(1).split('/')[0];if(!PUBLIC.has(f))return false;const full=path.join(ROOT,f);if(!fs.existsSync(full))return false;const b=fs.readFileSync(full);send(res,200,b,MIME[path.extname(f)]||'application/octet-stream');return true}
async function route(req,res){security(res);const p=new URL(req.url,`http://${req.headers.host||'localhost'}`).pathname;if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type'});return res.end()}
if(req.method==='GET'&&p==='/api/health')return send(res,200,{ok:true,version:'canonical-v12',model:MODEL});
if(req.method==='GET'&&p==='/api/ready')return send(res,200,{ready:true,ai:MODEL,exports:['docx','pdf','pptx'],features:['chat','translate','paper','ppt']});
if(req.method==='GET'&&p==='/api/ai/health')return send(res,200,{ok:true,model:MODEL,models:[MODEL],imageGeneration:false});
if(req.method==='POST'&&['/api/ai','/api/translate','/api/ai/translate','/api/generate-paper','/api/paper','/api/generate-makalah','/api/generate-ppt','/api/ppt'].includes(p)){if(!limited(req))return send(res,429,{error:'Terlalu banyak request. Tunggu sebentar.'});try{const d=await read(req);let mode=d.mode||'chat';if(p.includes('translate'))mode='translate';if(p.includes('paper')||p.includes('makalah'))mode='paper';if(p.includes('ppt'))mode='ppt';return send(res,200,{text:await ai(d,mode)})}catch(e){return send(res,e.status||500,{error:e.message||'AI gagal.'})}}
if(req.method==='POST'&&p==='/api/ai/vision')try{return send(res,200,{text:await ai(await read(req),'chat')})}catch(e){return send(res,e.status||500,{error:e.message})};
if(req.method==='POST'&&['/api/export/docx','/api/export/word'].includes(p))try{return await docx(res,await read(req))}catch(e){return send(res,e.status||500,{error:e.message})};
if(req.method==='POST'&&p==='/api/export/pdf')try{const d=await read(req),c=String(d.content||'').trim();if(!c)throw fail('Konten PDF kosong.',400);const b=pdf(c);res.setHeader('Content-Disposition','attachment; filename="campusly-makalah.pdf"');return send(res,200,b,'application/pdf')}catch(e){return send(res,e.status||500,{error:e.message})};
if(req.method==='POST'&&['/api/export/ppt','/api/export/pptx'].includes(p))try{return await ppt(res,await read(req))}catch(e){return send(res,e.status||500,{error:e.message})};
if(req.method==='GET'&&serve(res,p))return;return send(res,404,{error:'Not found'})}
http.createServer((q,s)=>route(q,s).catch(e=>send(s,e.status||500,{error:e.message||'Server error'}))).listen(PORT,'0.0.0.0',()=>console.log(`Campusly canonical-v12 listening on ${PORT} — ${MODEL}`));
