const http=require('http');
const fs=require('fs');
const path=require('path');
const PptxGenJS=require('pptxgenjs');
const {Document,Packer,Paragraph,TextRun,HeadingLevel,AlignmentType}=require('docx');

const PORT=Number(process.env.PORT||8787);
const ROOT=__dirname;
const PRIMARY='gemini-3.7-flash';
const FALLBACK='gemini-3.5-flash-lite';
const MAX=16*1024*1024;
const PUBLIC=new Set(['index.html','campusly-v5.js','campusly-v5.css','manifest.webmanifest','icon.svg']);
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.webmanifest':'application/manifest+json; charset=utf-8','.svg':'image/svg+xml'};
const hits=new Map();
const fail=(message,status=500)=>Object.assign(new Error(message),{status});
function json(res,status,data){const body=Buffer.from(JSON.stringify(data));res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Content-Length':body.length});res.end(body)}
function binary(res,status,body,type,name){res.writeHead(status,{'Content-Type':type,'Content-Disposition':`attachment; filename="${name}"`,'Cache-Control':'no-store','Content-Length':body.length});res.end(body)}
function security(res){res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'")}
function limited(req,limit=30){const k=req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown',now=Date.now(),old=hits.get(k),x=!old||now-old.time>=60000?{time:now,count:0}:old;x.count++;hits.set(k,x);return x.count<=limit}
function body(req){return new Promise((resolve,reject)=>{let a=[],n=0;req.on('data',c=>{n+=c.length;if(n>MAX){reject(fail('Payload terlalu besar.',413));req.destroy();return}a.push(c)});req.on('end',()=>{try{resolve(JSON.parse(Buffer.concat(a).toString()||'{}'))}catch{reject(fail('JSON tidak valid.',400))}});req.on('error',reject)})}
function clean(s){return String(s??'').replace(/\r/g,'').replace(/```(?:html|xml|markdown|text|javascript|js)?/gi,'').replace(/```/g,'').trim()}
function strip(s){const v=clean(s);return /<(html|body|script|style)\b/i.test(v)?v.replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<style[\s\S]*?<\/style>/gi,'').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/\s{2,}/g,' ').trim():v}
function system(mode){if(mode==='paper')return 'Kamu penulis makalah akademik Indonesia. Buat tulisan lengkap, objektif, rapi. Struktur: judul, abstrak, kata kunci, pendahuluan, pembahasan, kesimpulan, daftar pustaka. Jangan mengarang sumber, DOI, URL, data, atau kutipan; tandai referensi yang perlu diverifikasi.';if(mode==='ppt')return 'Kamu penyusun presentasi mahasiswa Indonesia. Buat materi ringkas dan mudah dipresentasikan. Format wajib tiap slide: SLIDE N: Judul, 3-5 bullet, VISUAL: deskripsi singkat. Jangan HTML, CSS, JS, XML, atau source code.';if(mode==='translate')return 'Kamu penerjemah profesional. Terjemahkan hanya teks yang diberikan ke bahasa target. Pertahankan makna, istilah, struktur, dan nada. Jangan memberi komentar tambahan.';return 'Kamu Campusly AI, teman kuliah mahasiswa Indonesia. Jawab natural, santai, gaya ngobrol Gen Z. Pakai gue/lo jika cocok dan slang ringan seperti jir, wkwk, gas, nah, tapi jangan dipaksakan. Tetap akurat. Untuk akademik tetap jelas dan rapi.'}
function prompt(data,mode){for(const k of ['input','message','prompt','text','content'])if(typeof data[k]==='string'&&data[k].trim())return data[k].trim();if(Array.isArray(data.messages))return data.messages.slice(-12).map(m=>`${m?.role==='assistant'?'Campusly AI':'User'}: ${String(m?.content??'').trim()}`).filter(Boolean).join('\n\n');if(mode==='paper'||mode==='ppt'){const t=data.topic||data.judul||data.title;if(t)return `Buat ${mode==='paper'?'makalah':'presentasi'} tentang: ${t}`};return ''}
async function callGemini(model,parts,mode){const key=String(process.env.GEMINI_API_KEY||'').trim();if(!key)throw fail('GEMINI_API_KEY belum diatur di Blitz.',503);let r;try{r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({systemInstruction:{parts:[{text:system(mode)}]},contents:[{role:'user',parts}],generationConfig:{temperature:mode==='chat'?0.8:0.55}})})}catch(e){throw fail(`Tidak bisa menghubungi Gemini: ${e.message||'network error'}`,502)}const raw=await r.text();let d={};try{d=JSON.parse(raw)}catch{}if(!r.ok)throw Object.assign(fail(d?.error?.message||`Gemini HTTP ${r.status}`,r.status),{geminiStatus:r.status});const text=strip(d?.candidates?.[0]?.content?.parts?.map(x=>x?.text||'').join('')||'');if(!text)throw fail('Gemini mengembalikan jawaban kosong.',502);return text}
async function gemini(data,mode){let p=prompt(data,mode);if(!p)throw fail('Input AI kosong.',400);if(mode==='translate')p=`Terjemahkan dari ${data.from||data.source||'bahasa sumber'} ke ${data.to||data.target||data.targetLanguage||'bahasa Indonesia'}.\n\n${p}`;try{return await callGemini(PRIMARY,[{text:p}],mode)}catch(e){if([400,403,404,429].includes(e.geminiStatus)){console.warn(`Gemini ${PRIMARY} gagal (${e.geminiStatus}); mencoba ${FALLBACK}`);return callGemini(FALLBACK,[{text:p}],mode)}throw e}}
async function vision(data){const m=String(data.image||'').match(/^data:([^;]+);base64,(.+)$/);if(!m)throw fail('Gambar soal tidak valid.',400);const text=String(data.question||'Baca soal ini dengan teliti, jelaskan langkah pengerjaan dan jawabannya dalam bahasa Indonesia yang jelas dan santai.');const parts=[{text},{inlineData:{mimeType:m[1],data:m[2]}}];try{return await callGemini(PRIMARY,parts,'chat')}catch(e){if([400,403,404,429].includes(e.geminiStatus))return callGemini(FALLBACK,parts,'chat');throw e}}
function ai(text){return{ok:true,text,result:text,response:text,answer:text,message:text,content:text,translatedText:text}}
async function docx(c){const children=clean(c).split('\n').map(x=>{const s=x.trim();if(!s)return new Paragraph({text:''});const h=s.match(/^#{1,3}\s+(.+)$/);const b=s.match(/^[-*•]\s+(.+)$/);if(h)return new Paragraph({text:h[1],heading:HeadingLevel.HEADING_2});if(b)return new Paragraph({children:[new TextRun({text:b[1]})],bullet:{level:0}});return new Paragraph({children:[new TextRun({text:s})],alignment:AlignmentType.JUSTIFIED})});return Packer.toBuffer(new Document({sections:[{children}]}))}
function pdf(c){const esc=s=>String(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7E]/g,' '),lines=[];for(const raw of clean(c).split('\n')){let s=raw.trim()||' ';while(s.length>92){lines.push(s.slice(0,92));s=s.slice(92)}lines.push(s)}const pages=[];for(let i=0;i<Math.max(1,lines.length);i+=48)pages.push(lines.slice(i,i+48));const o=[null,null,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'],ids=[];for(const pg of pages){const st=['BT','/F1 11 Tf','50 790 Td','14 TL'];pg.forEach((x,i)=>{if(i)st.push('0 -14 Td');st.push(`(${esc(x)}) Tj`)});st.push('ET');const cid=o.length;o.push(`<< /Length ${Buffer.byteLength(st.join('\n'),'latin1')} >>\nstream\n${st.join('\n')}\nendstream`);const pid=o.length;o.push(`<< /Type /Page /Parent 1 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 2 0 R >> >> /Contents ${cid} 0 R >>`);ids.push(pid)}o[1]=`<< /Type /Pages /Kids [${ids.map(x=>x+' 0 R').join(' ')}] /Count ${ids.length} >>`;const root=o.length;o.push(`<< /Type /Catalog /Pages 1 0 R >>`);let out='%PDF-1.4\n';const off=[0];for(let i=1;i<o.length;i++){off[i]=Buffer.byteLength(out,'latin1');out+=`${i} 0 obj\n${o[i]}\nendobj\n`}const x=Buffer.byteLength(out,'latin1');out+=`xref\n0 ${o.length}\n0000000000 65535 f \n`;for(let i=1;i<o.length;i++)out+=`${String(off[i]).padStart(10,'0')} 00000 n \n`;return Buffer.from(out+`trailer\n<< /Size ${o.length} /Root ${root} 0 R >>\nstartxref\n${x}\n%%EOF`,'latin1')}
async function pptx(c,title='Campusly'){const ppt=new PptxGenJS();ppt.layout='LAYOUT_WIDE';ppt.author='Campusly';const slides=clean(c).split(/(?=SLIDE\s+\d+\s*:)/i).map(x=>x.trim()).filter(Boolean);if(!slides.length)throw fail('Format presentasi kosong.',400);for(const raw of slides){const s=ppt.addSlide(),ls=raw.split('\n').map(x=>x.trim()).filter(Boolean),h=(ls.shift()||title).replace(/^SLIDE\s+\d+\s*:\s*/i,'');s.addText(h,{x:.6,y:.45,w:12,h:.7,fontSize:26,bold:true});const visual=ls.find(x=>/^VISUAL\s*:/i.test(x)),bs=ls.filter(x=>!/^VISUAL\s*:/i.test(x)).map(x=>x.replace(/^[-*•]\s*/,''));s.addText(bs.map(text=>({text,options:{bullet:{indent:16}}})),{x:.8,y:1.45,w:11.5,h:4.9,fontSize:18,breakLine:true});if(visual)s.addText(visual,{x:.8,y:6.45,w:11.5,h:.35,fontSize:10,italic:true})}return ppt.write({outputType:'nodebuffer'})}
function serve(res,p){const n=p==='/'?'index.html':p.slice(1).split('/')[0];if(!PUBLIC.has(n))return false;const f=path.join(ROOT,n);if(!fs.existsSync(f))return false;const b=fs.readFileSync(f);res.writeHead(200,{'Content-Type':MIME[path.extname(n)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(b);return true}
async function route(req,res){security(res);const p=new URL(req.url,`http://${req.headers.host||'localhost'}`).pathname;if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type'});return res.end()}if(req.method==='GET'&&p==='/api/health')return json(res,200,{ok:true,version:'canonical-v14',model:PRIMARY,fallback:FALLBACK});if(req.method==='GET'&&p==='/api/ready')return json(res,200,{ready:true,ai:PRIMARY,fallback:FALLBACK,exports:['docx','pdf','pptx'],features:['chat','translate','paper','ppt','vision']});if(req.method==='GET'&&p==='/api/ai/health')return json(res,200,{ok:true,model:PRIMARY,fallback:FALLBACK});const aiRoutes=new Set(['/api/ai','/api/translate','/api/ai/translate','/api/generate-paper','/api/paper','/api/generate-makalah','/api/generate-ppt','/api/ppt']);if(req.method==='POST'&&aiRoutes.has(p)){if(!limited(req))return json(res,429,{ok:false,error:'Terlalu banyak request. Tunggu sebentar.'});try{const d=await body(req);let mode=d.mode||'chat';if(p.includes('translate'))mode='translate';else if(p.includes('paper')||p.includes('makalah'))mode='paper';else if(p.includes('ppt'))mode='ppt';return json(res,200,ai(await gemini(d,mode)))}catch(e){return json(res,e.status||500,{ok:false,error:e.message||'AI gagal.'})}}if(req.method==='POST'&&p==='/api/ai/vision'){try{return json(res,200,ai(await vision(await body(req))))}catch(e){return json(res,e.status||500,{ok:false,error:e.message||'Vision gagal.'})}}if(req.method==='POST'&&['/api/export/docx','/api/export/word'].includes(p)){try{const d=await body(req),b=await docx(d.content||'');return binary(res,200,b,'application/vnd.openxmlformats-officedocument.wordprocessingml.document','campusly-makalah.docx')}catch(e){return json(res,e.status||500,{ok:false,error:e.message||'DOCX gagal.'})}}if(req.method==='POST'&&p==='/api/export/pdf'){try{const d=await body(req),b=pdf(d.content||'');return binary(res,200,b,'application/pdf','campusly-makalah.pdf')}catch(e){return json(res,e.status||500,{ok:false,error:e.message||'PDF gagal.'})}}if(req.method==='POST'&&['/api/export/ppt','/api/export/pptx'].includes(p)){try{const d=await body(req),b=await pptx(d.content||'',d.title||'Campusly');return binary(res,200,b,'application/vnd.openxmlformats-officedocument.presentationml.presentation','campusly-presentasi.pptx')}catch(e){return json(res,e.status||500,{ok:false,error:e.message||'PPTX gagal.'})}}if(req.method==='GET'&&serve(res,p))return;if(req.method==='GET')return json(res,404,{ok:false,error:'Not found'});return json(res,404,{ok:false,error:'Endpoint tidak ditemukan'})}
const server=http.createServer((req,res)=>route(req,res).catch(e=>{console.error(e);if(!res.headersSent)json(res,500,{ok:false,error:'Server error'})}));server.listen(PORT,'0.0.0.0',()=>console.log(`Campusly canonical-v14 listening on ${PORT}; primary=${PRIMARY}; fallback=${FALLBACK}`));
