/* Campusly — one canonical frontend. No overlays, duplicate runtimes, or patch layers. */
(()=>{
'use strict';
const KEY='campusly_state_v5';
const $=(s,r=document)=>r.querySelector(s);
const uid=()=>crypto.randomUUID?.()||Date.now()+'-'+Math.random().toString(16).slice(2);
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
const fmt=d=>d?new Date(d+'T00:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'}):'Tanpa tanggal';
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
const defaults={profile:{name:'',preferredName:'',university:'',major:'',faculty:'',nim:'',semester:1,gpa:'',targetGpa:3.75,completed:false},settings:{theme:'dark',notifications:true},tasks:[],schedule:[],events:[],notes:[],finance:[],grades:[],notifications:[],ai:[]};
function merge(a,b){for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])&&a[k]&&typeof a[k]==='object')merge(a[k],b[k]);else a[k]=b[k]}return a}
function load(){try{return merge(structuredClone(defaults),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return structuredClone(defaults)}}
let S=load(),route=location.hash.slice(1)||'home',historyRoutes=[],month=new Date(new Date().getFullYear(),new Date().getMonth(),1);
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),2600)}
function go(r){if(r===route)return;historyRoutes.push(route);route=r;location.hash=r;render()}
function back(){route=historyRoutes.pop()||'home';location.hash=route;render()}
addEventListener('hashchange',()=>{const r=location.hash.slice(1)||'home';if(r!==route){route=r;render()}});
const paths={home:'M3 10.5 12 3l9 7.5V20a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z',schedule:'<path d="M4 5h16v15H4zM8 3v4M16 3v4M4 9h16"/>',tasks:'<path d="m5 12 4 4L19 6"/><path d="M4 4h5M4 20h5"/>',calendar:'<rect x="3" y="4" width="18" height="17" rx="3"/><path d="M16 2v4M8 2v4M3 9h18"/>',ai:'<path d="M12 3l1.8 5.2L19 10l-5.2 1.8L12 17l-1.8-5.2L5 10l5.2-1.8z"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',settings:'<circle cx="12" cy="12" r="4"/><path d="M12 3v3M12 18v3M3 12h3M18 12h3M5.6 5.6l2.1 2.1M16.3 16.3l2.1 2.1M18.4 5.6l-2.1 2.1M7.7 16.3l-2.1 2.1"/>',plus:'<path d="M12 5v14M5 12h14"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',back:'<path d="m15 18-6-6 6-6M9 12h11"/>',note:'<path d="M5 3h10l4 4v14H5zM15 3v5h5M8 13h8M8 17h6"/>',wallet:'<path d="M4 6h16v14H4zM4 6V4h13M16 13h4"/><circle cx="16" cy="13" r="1"/>',file:'<path d="M6 3h8l4 4v14H6zM14 3v5h5M9 13h6M9 17h5"/>',chart:'<path d="M4 19V5M4 19h17M7 15l3-4 3 2 5-7"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 3 15 0 18M12 3c-3 3-3 15 0 18"/>',scan:'<path d="M5 4H3v4M19 4h2v4M5 20H3v-4M19 20h2v-4M7 9h10M7 13h10M7 17h6"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>'};
function icon(n){return `<span class="ui-icon"><svg viewBox="0 0 24 24" aria-hidden="true">${paths[n]||paths.menu}</svg></span>`}
const field=(l,n,v='',type='text',extra='')=>`<label class="field"><span>${esc(l)}</span><input name="${esc(n)}" type="${type}" value="${esc(v)}" ${extra}></label>`;
const area=(l,n,v='',p='')=>`<label class="field"><span>${esc(l)}</span><textarea name="${esc(n)}" placeholder="${esc(p)}">${esc(v)}</textarea></label>`;
const select=(l,n,v,opts)=>`<label class="field"><span>${esc(l)}</span><select name="${esc(n)}">${opts.map(o=>`<option value="${esc(o[0])}" ${String(o[0])===String(v)?'selected':''}>${esc(o[1])}</option>`).join('')}</select></label>`;
function modal(title,body,action,label='Simpan'){document.querySelector('.overlay')?.remove();const d=document.createElement('div');d.className='overlay';d.innerHTML=`<div class="modal"><header><h2>${esc(title)}</h2><button class="icon-btn" data-x>${icon('close')}</button></header><form class="modal-body">${body}</form><footer><button type="button" class="btn" data-c>Batal</button><button type="button" class="btn primary" data-s>${esc(label)}</button></footer></div>`;document.body.append(d);$('[data-x]',d).onclick=()=>d.remove();$('[data-c]',d).onclick=()=>d.remove();$('[data-s]',d).onclick=action}
const mainNav=[['home','home','Beranda'],['schedule','schedule','Jadwal'],['tasks','tasks','Tugas'],['calendar','calendar','Kalender'],['ai','ai','AI'],['menu','menu','Menu']];
function header(k,t,s,action=''){return `<div class="eyebrow">${esc(k)}</div><div class="page-head">${route!=='home'?`<button class="back-btn" onclick="back()">${icon('back')}<span>Kembali</span></button>`:''}<div class="head-copy"><h1>${esc(t)}</h1><p>${esc(s)}</p></div>${action}</div>`}
function shell(content){document.documentElement.dataset.theme=S.settings.theme==='light'?'light':'dark';return `<div class="app"><aside><div class="brand"><b>C</b><span>Campusly</span></div>${mainNav.map(x=>`<button class="nav-item ${route===x[0]?'active':''}" data-route="${x[0]}" onclick="go('${x[0]}')">${icon(x[1])}<span>${x[2]}</span></button>`).join('')}<div class="aside-bottom"><button onclick="go('settings')">${icon('settings')}<span>Pengaturan</span></button></div></aside><main><header class="top"><div class="search-wrap">${icon('search')}<input id="global-search" placeholder="Cari tugas, catatan, jadwal..." value="${esc(window._q||'')}" onkeydown="if(event.key==='Enter')search(this.value)"><button class="search-go" onclick="search($('#global-search')?.value)">Cari</button></div><button class="round" onclick="toggleTheme()">${S.settings.theme==='dark'?'☀':'☾'}</button><button class="avatar" onclick="go('settings')">${esc((S.profile.preferredName||S.profile.name||'M')[0].toUpperCase())}</button></header><section>${content}</section></main></div><nav class="mobile-nav">${mainNav.map(x=>`<button class="nav-item ${route===x[0]?'active':''}" onclick="go('${x[0]}')">${icon(x[1])}<span>${x[2]}</span></button>`).join('')}</nav>`}
function empty(t,b,fn){return `<div class="empty"><p>${esc(t)}</p>${b?`<button class="btn" onclick="${fn}">${esc(b)}</button>`:''}</div>`}
function onboarding(){return `<div class="onboard"><div class="onboard-card"><div class="logo">C</div><div class="eyebrow">CAMPUSLY</div><h1>Selamat datang di Campusly</h1><p>Lengkapi profil kuliah satu kali untuk menyesuaikan workspace.</p><form id="onboard-form" class="form grid2">${field('Nama lengkap','name','','text','required')}${field('Nama panggilan','preferredName','','text','required')}${field('Universitas','university','','text','required')}${field('Program studi','major','','text','required')}${field('Fakultas','faculty')}${field('NIM','nim')}${field('Semester','semester',1,'number','min="1" required')}${field('GPA sekarang','gpa','','number','min="0" max="4" step="0.01"')}${field('Target GPA','targetGpa',3.75,'number','min="0" max="4" step="0.01"')}<button class="btn primary wide">Masuk ke Campusly</button></form></div></div>`}
function home(){const active=S.tasks.filter(t=>!t.done).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'9999'));return shell(header('CAMPUS WORKSPACE',`Selamat datang, ${S.profile.preferredName||S.profile.name||'Mahasiswa'}`,'Workspace akademik untuk tugas, jadwal, agenda, dan AI.',`<button class="btn primary" onclick="taskModal()">${icon('plus')} Tambah tugas</button>`)+`<div class="hero"><span class="pill">Student workspace</span><h2>Kelola aktivitas kuliah dalam satu tempat.</h2><p>Atur tugas, jadwal, agenda, catatan, keuangan, dan kebutuhan akademik tanpa berpindah-pindah aplikasi.</p><div class="actions"><button class="btn primary" onclick="go('tasks')">Lihat tugas</button><button class="btn" onclick="go('schedule')">Lihat jadwal</button><button class="btn" onclick="go('ai')">Buka AI</button></div></div><div class="stats"><article><small>Tugas aktif</small><strong>${active.length}</strong><span>belum selesai</span></article><article><small>Semester</small><strong>${S.profile.semester}</strong><span>${esc(S.profile.major||'Belum diisi')}</span></article><article><small>GPA</small><strong>${S.profile.gpa?Number(S.profile.gpa).toFixed(2):'—'}</strong><span>target ${Number(S.profile.targetGpa).toFixed(2)}</span></article><article><small>Jadwal</small><strong>${S.schedule.length}</strong><span>kelas tersimpan</span></article></div><div class="quick-grid"><button onclick="taskModal()">${icon('tasks')}<b>Tambah tugas</b><small>Deadline dan prioritas</small></button><button onclick="scheduleModal()">${icon('schedule')}<b>Tambah jadwal</b><small>Kelas mingguan</small></button><button onclick="noteModal()">${icon('note')}<b>Catatan</b><small>Simpan materi</small></button><button onclick="financeModal()">${icon('wallet')}<b>Keuangan</b><small>Pemasukan dan pengeluaran</small></button></div><article class="card"><div class="card-head"><div><h2>Deadline terdekat</h2><p>Tugas yang perlu diperhatikan</p></div><button class="link" onclick="go('tasks')">Semua →</button></div>${active.slice(0,6).map(taskRow).join('')||empty('Belum ada tugas.','Tambah tugas','taskModal()')}</article>`)}
function taskRow(t){return `<div class="row"><button class="check ${t.done?'done':''}" onclick="toggleTask('${t.id}')">${t.done?'✓':''}</button><div><b>${esc(t.title)}</b><small>${esc(t.course||'Tanpa mata kuliah')} · ${fmt(t.deadline)}</small></div><button class="icon-btn" onclick="taskModal('${t.id}')">✎</button></div>`}
function tasks(){const q=(window._taskQ||'').toLowerCase(),list=S.tasks.filter(t=>!q||`${t.title} ${t.course||''}`.toLowerCase().includes(q)).sort((a,b)=>(a.done-b.done)||(a.deadline||'9999').localeCompare(b.deadline||'9999'));return shell(header('WORKSPACE','Tugas','Kelola seluruh deadline dan prioritas.',`<button class="btn primary" onclick="taskModal()">${icon('plus')} Tambah tugas</button>`)+`<div class="toolbar"><input value="${esc(window._taskQ||'')}" placeholder="Cari tugas..." oninput="window._taskQ=this.value;render()"></div><article class="card">${list.map(taskRow).join('')||empty('Belum ada tugas yang cocok.','Tambah tugas','taskModal()')}</article>`)}
function schedule(){const days=['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu'];return shell(header('ACADEMIC','Jadwal kuliah','Kelas mingguan, dosen, ruangan, dan validasi bentrok.',`<button class="btn primary" onclick="scheduleModal()">${icon('plus')} Tambah kelas</button>`)+`<div class="week-grid">${days.map(d=>`<article class="card"><div class="card-head"><h2>${d}</h2><span class="pill">${S.schedule.filter(x=>x.day===d).length}</span></div>${S.schedule.filter(x=>x.day===d).sort((a,b)=>a.start.localeCompare(b.start)).map(c=>`<div class="class-item"><b>${esc(c.name)}</b><small>${c.start}–${c.end} · ${esc(c.room||'')}</small><small>${esc(c.lecturer||'Dosen belum diisi')}</small><div class="actions"><button class="btn small" onclick="scheduleModal('${c.id}')">Edit</button><button class="btn small danger" onclick="deleteSchedule('${c.id}')">Hapus</button></div></div>`).join('')||'<p class="muted">Belum ada kelas.</p>'}</article>`).join('')}</div>`)}
function calendar(){const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate();let cells='';for(let i=0;i<42;i++){const n=i-start+1,d=n<1?new Date(y,m-1,n):n>days?new Date(y,m+1,n-days):new Date(y,m,n),k=d.toISOString().slice(0,10),ev=S.events.filter(e=>e.date===k);cells+=`<button class="day ${d.getMonth()!==m?'out':''} ${k===today()?'today':''}" onclick="eventModal(null,'${k}')"><b>${d.getDate()}</b>${ev.slice(0,3).map(e=>`<em>${esc(e.title)}</em>`).join('')}</button>`}return shell(header('PLANNER','Kalender','Agenda dan deadline.',`<div class="cal-actions"><button class="icon-btn" onclick="changeMonth(-1)">‹</button><button class="btn" onclick="monthToday()">Hari ini</button><button class="icon-btn" onclick="changeMonth(1)">›</button><button class="btn primary" onclick="eventModal()">${icon('plus')} Agenda</button></div>`)+`<article class="card calendar-card"><div class="calendar-title"><h2>${first.toLocaleDateString('id-ID',{month:'long',year:'numeric'})}</h2></div><div class="cal-head">${['Sen','Sel','Rab','Kam','Jum','Sab','Min'].map(x=>`<b>${x}</b>`).join('')}</div><div class="cal-grid">${cells}</div></article>`)}
function ai(){return shell(header('ASSISTANT','Campusly AI','Asisten akademik. Chat tetap santai; dokumen dibuat formal dan baku.')+`<div class="ai-tools"><button onclick="chatModal()">${icon('ai')}<b>Chat AI</b><small>Tanya apa saja</small></button><button onclick="scanModal()">${icon('scan')}<b>Scan soal</b><small>Gambar → pembahasan</small></button><button onclick="paperModal()">${icon('file')}<b>Buat makalah</b><small>DOCX + PDF</small></button><button onclick="pptModal()">${icon('chart')}<b>Buat PPT</b><small>PPTX siap edit</small></button></div><article class="card"><div class="chat">${S.ai.slice(-12).map(m=>`<div class="bubble ${m.role==='user'?'me':''}"><small>${m.role==='user'?'Anda':'Campusly AI'}</small>${esc(m.text)}</div>`).join('')||'<p class="muted">Belum ada percakapan.</p>'}</div><div class="ai-input"><textarea id="ai-text" placeholder="Tulis pertanyaan Anda..."></textarea><button class="btn primary" onclick="sendAI()">Kirim</button></div></article>`)}
function menu(){return shell(header('CAMPUSLY','Menu','Fitur tambahan untuk kebutuhan akademik.')+`<div class="menu-grid">${[['notes','note','Catatan','Simpan materi dan ide'],['finance','wallet','Keuangan','Catat pemasukan dan pengeluaran'],['gpa','chart','GPA / IPK','Pantau nilai kuliah'],['tools','chart','Tools kuliah','Translator, kalkulator, konversi, dan timer'],['settings','settings','Pengaturan','Profil, tema, dan notifikasi']].map(x=>`<button onclick="go('${x[0]}')">${icon(x[1])}<div><b>${x[2]}</b><small>${x[3]}</small></div><span>›</span></button>`).join('')}</div>`)}
function notes(){return shell(header('WORKSPACE','Catatan','Materi dan ide tersimpan.',`<button class="btn primary" onclick="noteModal()">${icon('plus')} Catatan</button>`)+`<div class="notes-grid">${S.notes.map(n=>`<article class="card"><div class="card-head"><h2>${esc(n.title)}</h2><button class="icon-btn" onclick="noteModal('${n.id}')">✎</button></div><p class="note">${esc(n.body)}</p><button class="btn small danger" onclick="deleteNote('${n.id}')">Hapus</button></article>`).join('')||empty('Belum ada catatan.','Buat catatan','noteModal()')}</div>`)}
function finance(){const inc=S.finance.filter(x=>x.type==='in').reduce((a,x)=>a+x.amount,0),out=S.finance.filter(x=>x.type==='out').reduce((a,x)=>a+x.amount,0);return shell(header('LIFE','Keuangan','Pantau pemasukan, pengeluaran, dan saldo.',`<button class="btn primary" onclick="financeModal()">${icon('plus')} Transaksi</button>`)+`<div class="stats"><article><small>Pemasukan</small><strong>${money(inc)}</strong></article><article><small>Pengeluaran</small><strong>${money(out)}</strong></article><article><small>Saldo</small><strong>${money(inc-out)}</strong></article></div><article class="card">${S.finance.slice().reverse().map(x=>`<div class="row"><div><b>${esc(x.title)}</b><small>${x.type==='in'?'+':'−'} ${money(x.amount)} · ${fmt(x.date)}</small></div><button class="btn small danger" onclick="deleteFinance('${x.id}')">Hapus</button></div>`).join('')||empty('Belum ada transaksi.')}</article>`)}
function gpa(){const total=S.grades.reduce((a,x)=>a+x.credits,0),pts=S.grades.reduce((a,x)=>a+x.credits*x.grade,0),g=total?pts/total:0;return shell(header('ACADEMIC','GPA / IPK','Hitung dan pantau nilai kuliah.',`<button class="btn primary" onclick="gradeModal()">${icon('plus')} Tambah nilai</button>`)+`<div class="stats"><article><small>GPA</small><strong>${g?g.toFixed(2):'—'}</strong><span>${total} SKS</span></article><article><small>Target</small><strong>${Number(S.profile.targetGpa).toFixed(2)}</strong></article></div><article class="card">${S.grades.map(x=>`<div class="row"><div><b>${esc(x.name)}</b><small>${x.credits} SKS · ${Number(x.grade).toFixed(2)}</small></div><button class="btn small danger" onclick="deleteGrade('${x.id}')">Hapus</button></div>`).join('')||empty('Belum ada nilai.','Tambah nilai','gradeModal()')}</article>`)}
function settings(){return shell(header('PREFERENCES','Pengaturan','Profil, tema, notifikasi, dan backup.')+`<article class="card form">${field('Nama lengkap','name',S.profile.name)}${field('Nama panggilan','preferredName',S.profile.preferredName)}${field('Universitas','university',S.profile.university)}${field('Program studi','major',S.profile.major)}${field('Fakultas','faculty',S.profile.faculty)}${field('NIM','nim',S.profile.nim)}${field('Semester','semester',S.profile.semester,'number','min="1"')}${field('Target GPA','targetGpa',S.profile.targetGpa,'number','min="0" max="4" step="0.01"')}<label class="field"><span>Tema</span><select id="theme-select"><option value="dark" ${S.settings.theme==='dark'?'selected':''}>Gelap</option><option value="light" ${S.settings.theme==='light'?'selected':''}>Terang</option></select></label><label class="switch"><input id="notif-toggle" type="checkbox" ${S.settings.notifications?'checked':''}> Notifikasi</label><button class="btn primary" onclick="saveSettings()">Simpan perubahan</button><hr><div class="actions"><button class="btn" onclick="backup()">Export data</button><button class="btn" onclick="importBackup()">Import data</button><button class="btn danger" onclick="resetApp()">Reset data</button></div></article>`)}
function tools(){return shell(header('UTILITY','Tools kuliah','Utilitas akademik dalam satu halaman.')+`<div class="tool-grid"><button onclick="translator()">${icon('globe')}<b>Translator</b><small>Terjemahkan teks</small></button><button onclick="science()">${icon('chart')}<b>Kalkulator</b><small>Operasi matematika</small></button><button onclick="convert()">${icon('chart')}<b>Konversi satuan</b><small>Panjang, berat, suhu</small></button><button onclick="gradeCalc()">${icon('chart')}<b>Kalkulator nilai</b><small>Nilai berbobot</small></button><button onclick="timer()">${icon('clock')}<b>Study timer</b><small>Pomodoro 25 menit</small></button></div>`)}
function taskModal(id){const o=S.tasks.find(x=>x.id===id)||{};modal(id?'Edit tugas':'Tambah tugas',`<div class="form">${field('Judul tugas','title',o.title||'','text','required')}${field('Mata kuliah','course',o.course||'')}${field('Deadline','deadline',o.deadline||today(),'date')}${select('Prioritas','priority',o.priority||'MEDIUM',[['HIGH','Tinggi'],['MEDIUM','Sedang'],['LOW','Rendah']])}</div>`,()=>{const f=new FormData($('.modal-body')),n={id:id||uid(),title:String(f.get('title')||'').trim(),course:String(f.get('course')||''),deadline:String(f.get('deadline')||''),priority:String(f.get('priority')||'MEDIUM'),done:o.done||false};if(!n.title)return toast('Judul tugas wajib diisi.');if(id)S.tasks[S.tasks.findIndex(x=>x.id===id)]=n;else S.tasks.push(n);save();document.querySelector('.overlay').remove();render();toast('Tugas tersimpan')})}
function toggleTask(id){const x=S.tasks.find(t=>t.id===id);if(x){x.done=!x.done;save();render()}}
function eventModal(id,date){const o=S.events.find(x=>x.id===id)||{};modal(id?'Edit agenda':'Tambah agenda',`<div class="form">${field('Judul','title',o.title||'','text','required')}${field('Tanggal','date',date||o.date||today(),'date','required')}${field('Jam','time',o.time||'08:00','time')}${field('Lokasi','location',o.location||'')}</div>`,()=>{const f=new FormData($('.modal-body')),n={id:id||uid(),title:String(f.get('title')||'').trim(),date:String(f.get('date')||today()),time:String(f.get('time')||''),location:String(f.get('location')||'')};if(!n.title)return toast('Judul agenda wajib diisi.');if(id)S.events[S.events.findIndex(x=>x.id===id)]=n;else S.events.push(n);save();document.querySelector('.overlay').remove();render()})}
function scheduleModal(id){const o=S.schedule.find(x=>x.id===id)||{},ds=['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu'].map(x=>[x,x]);modal(id?'Edit kelas':'Tambah kelas',`<div class="form">${field('Mata kuliah','name',o.name||'','text','required')}${select('Hari','day',o.day||'Senin',ds)}${field('Mulai','start',o.start||'08:00','time')}${field('Selesai','end',o.end||'10:00','time')}${field('Ruangan','room',o.room||'')}${field('Dosen','lecturer',o.lecturer||'')}</div>`,()=>{const f=new FormData($('.modal-body')),n={id:id||uid(),name:String(f.get('name')||'').trim(),day:String(f.get('day')),start:String(f.get('start')),end:String(f.get('end')),room:String(f.get('room')||''),lecturer:String(f.get('lecturer')||'')};if(!n.name)return toast('Mata kuliah wajib diisi.');if(n.start>=n.end)return toast('Jam selesai harus setelah jam mulai.');if(S.schedule.some(x=>x.id!==id&&x.day===n.day&&n.start<x.end&&n.end>x.start))return toast('Jadwal bentrok dengan kelas lain.');if(id)S.schedule[S.schedule.findIndex(x=>x.id===id)]=n;else S.schedule.push(n);save();document.querySelector('.overlay').remove();render();toast('Jadwal tersimpan')})}
function deleteSchedule(id){if(confirm('Hapus kelas ini?')){S.schedule=S.schedule.filter(x=>x.id!==id);save();render()}}
function noteModal(id){const o=S.notes.find(x=>x.id===id)||{};modal(id?'Edit catatan':'Catatan baru',`<div class="form">${field('Judul','title',o.title||'','text','required')}${area('Isi','body',o.body||'','Tulis catatan...')}</div>`,()=>{const f=new FormData($('.modal-body')),n={id:id||uid(),title:String(f.get('title')||'').trim(),body:String(f.get('body')||'')};if(!n.title)return toast('Judul catatan wajib diisi.');if(id)S.notes[S.notes.findIndex(x=>x.id===id)]=n;else S.notes.push(n);save();document.querySelector('.overlay').remove();render()})}
function deleteNote(id){if(confirm('Hapus catatan?')){S.notes=S.notes.filter(x=>x.id!==id);save();render()}}
function financeModal(){modal('Tambah transaksi',`<div class="form">${field('Nama','title','','text','required')}${select('Tipe','type','out',[['out','Pengeluaran'],['in','Pemasukan']])}${field('Nominal','amount',0,'number','min="0" required')}${field('Tanggal','date',today(),'date')}</div>`,()=>{const f=new FormData($('.modal-body'));S.finance.push({id:uid(),title:String(f.get('title')),type:String(f.get('type')),amount:Number(f.get('amount')||0),date:String(f.get('date')||today())});save();document.querySelector('.overlay').remove();render()})}
function deleteFinance(id){if(confirm('Hapus transaksi?')){S.finance=S.finance.filter(x=>x.id!==id);save();render()}}
function gradeModal(){modal('Tambah nilai',`<div class="form">${field('Mata kuliah','name','','text','required')}${field('SKS','credits',3,'number','min="1"')}${field('Nilai 0–4','grade',4,'number','min="0" max="4" step="0.01"')}</div>`,()=>{const f=new FormData($('.modal-body'));S.grades.push({id:uid(),name:String(f.get('name')),credits:Number(f.get('credits')||0),grade:Number(f.get('grade')||0)});save();document.querySelector('.overlay').remove();render()})}
function deleteGrade(id){if(confirm('Hapus nilai?')){S.grades=S.grades.filter(x=>x.id!==id);save();render()}}
async function api(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Request gagal (${r.status})`);return d}
function aiContext(){return JSON.stringify({profile:S.profile,tasks:S.tasks.slice(0,30),schedule:S.schedule.slice(0,30),events:S.events.slice(0,30),grades:S.grades.slice(0,30)})}
async function sendAI(){const e=$('#ai-text'),text=e?.value.trim();if(!text)return toast('Tulis pertanyaan terlebih dahulu.');S.ai.push({role:'user',text});save();render();try{const d=await api('/api/ai',{messages:S.ai.slice(-10).map(x=>({role:x.role,content:x.text})),context:aiContext(),mode:'chat'});S.ai.push({role:'assistant',text:d.text||'AI tidak mengembalikan jawaban.'})}catch(err){S.ai.push({role:'assistant',text:'⚠️ '+err.message})}save();render()}
function chatModal(){go('ai');setTimeout(()=>$('#ai-text')?.focus(),50)}
function scanModal(){modal('Scan soal',`<div class="form"><label class="drop">${icon('scan')} Pilih foto soal<input id="scan-file" type="file" accept="image/*"></label><div class="output-label">Pembahasan</div><div id="scan-out" class="result output-box">Hasil scan akan muncul di sini.</div></div>`,async()=>{const f=$('#scan-file')?.files?.[0],out=$('#scan-out');if(!f)return toast('Pilih foto terlebih dahulu.');out.textContent='Menganalisis soal…';const rd=new FileReader();rd.onload=async()=>{try{const d=await api('/api/ai/vision',{image:rd.result,question:'Baca soal dengan teliti. Jelaskan langkah pengerjaan dan jawabannya dalam bahasa Indonesia yang jelas.'});out.textContent=d.text||'Tidak ada jawaban.'}catch(e){out.textContent='⚠️ '+e.message}};rd.readAsDataURL(f)},'Analisis')}
async function genAI(prompt,mode){const d=await api('/api/ai',{messages:[{role:'user',content:prompt}],context:aiContext(),mode});return d.text||''}
function paperModal(){modal('Buat makalah',`<div class="form">${field('Topik','topic','','text','required')}${field('Panjang','length','5 halaman')}${field('Gaya sitasi','cite','APA 7')}${area('Instruksi tambahan','extra','','Fokus, konteks, atau ketentuan dosen')}<div class="output-label">Pratinjau makalah</div><div id="paper-out" class="result output-box">Naskah akan dibuat dengan bahasa Indonesia baku dan format akademik.</div><div id="paper-actions" class="actions"></div></div>`,async()=>{const f=new FormData($('.modal-body')),out=$('#paper-out');out.textContent='Menyusun makalah akademik…';try{const text=await genAI(`Tulis makalah akademik tentang ${f.get('topic')}. Panjang: ${f.get('length')}. Gaya sitasi: ${f.get('cite')}. ${f.get('extra')}. Gunakan bahasa Indonesia baku sesuai KBBI dan EYD/PUEBI. Jangan gunakan sapaan percakapan, slang, emoji, atau komentar meta. Struktur: judul, abstrak, pendahuluan, pembahasan, kesimpulan, daftar pustaka. Jangan mengarang sumber, DOI, URL, kutipan, atau data.`,'paper');window.__paperText=text;out.textContent=text;$('#paper-actions').innerHTML='<button class="btn primary" onclick="exportDOCX(window.__paperText,\'Campusly Makalah\')">Download Word (.docx)</button><button class="btn" onclick="exportPDF(window.__paperText,\'Campusly Makalah\')">Download PDF</button>'}catch(e){out.textContent='⚠️ '+e.message}},'Generate')}
async function downloadExport(path,payload,name){try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d.error||`Export gagal (${r.status})`)}const blob=await r.blob();if(!blob.size)throw Error('File hasil export kosong.');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);toast(`${name} berhasil dibuat.`)}catch(e){toast(e.message)}}
function exportDOCX(text,title){return downloadExport('/api/export/docx',{content:text,title},'campusly-makalah.docx')}
function exportPDF(text,title){return downloadExport('/api/export/pdf',{content:text,title},'campusly-makalah.pdf')}
async function exportPPT(text,title){return downloadExport('/api/export/ppt',{content:text,title},'campusly-presentasi.pptx')}
function pptModal(){modal('Buat PPT',`<div class="form">${field('Topik','topic','','text','required')}${field('Jumlah slide','slides',10,'number','min="3" max="20"')}${area('Poin penting','points','','Jika kosong, AI akan menyusun materi')}<div class="output-label">Pratinjau materi PPT</div><div id="ppt-out" class="result output-box">Materi akan dibuat dengan bahasa akademik formal.</div><div id="ppt-actions" class="actions"></div></div>`,async()=>{const f=new FormData($('.modal-body')),out=$('#ppt-out');out.textContent='Menyusun presentasi…';try{const text=await genAI(`Buat presentasi akademik ${f.get('slides')} slide tentang ${f.get('topic')}. ${f.get('points')}. Gunakan bahasa Indonesia baku sesuai KBBI dan EYD/PUEBI, tanpa sapaan percakapan, slang, emoji, atau komentar meta. Format setiap slide: SLIDE N: Judul, lalu bullet, dan satu baris VISUAL: yang menjelaskan gambar/ikon/diagram yang relevan. Jangan menulis instruksi kepada pengguna.`,'ppt');window.__pptText=text;out.textContent=text;$('#ppt-actions').innerHTML='<button class="btn primary" onclick="exportPPT(window.__pptText,\'Campusly Presentasi\')">Download PPTX</button><small class="muted">File PPTX dapat dibuka di PowerPoint atau diunggah ke Canva untuk diedit.</small>'}catch(e){out.textContent='⚠️ '+e.message}},'Generate')}
function translator(){const langs=[['id','Indonesia'],['en','Inggris'],['ms','Melayu'],['ar','Arab'],['zh','Mandarin'],['ja','Jepang'],['ko','Korea'],['fr','Prancis'],['de','Jerman'],['es','Spanyol']];modal('Translator',`<div class="form">${select('Dari','from','id',langs)}${select('Ke','to','en',langs)}${area('Teks input','text','','Tulis teks yang ingin diterjemahkan')}<textarea id="tr-out" class="output-box" readonly placeholder="Hasil terjemahan"></textarea></div>`,async()=>{const f=new FormData($('.modal-body')),out=$('#tr-out');if(!String(f.get('text')||'').trim())return toast('Teks input belum diisi.');out.value='Menerjemahkan…';try{out.value=await genAI(`Terjemahkan dari ${f.get('from')} ke ${f.get('to')}. Pertahankan makna dan format tanpa komentar tambahan.\n\n${f.get('text')}`,'translate')}catch(e){out.value='⚠️ '+e.message}},'Terjemahkan')}
function science(){modal('Kalkulator',`<div class="calc"><input id="calc" readonly placeholder="0"><div class="calc-grid">${['7','8','9','÷','4','5','6','×','1','2','3','−','0','.','(',')','sin','cos','tan','log','√','^','π','⌫','C','='].map(k=>`<button type="button" onclick="calcPress('${k}')">${k}</button>`).join('')}</div></div>`,()=>document.querySelector('.overlay')?.remove(),'Tutup')}
function calcPress(k){const o=$('#calc');if(!o)return;if(k==='C'){o.value='';return}if(k==='⌫'){o.value=o.value.slice(0,-1);return}if(k==='='){try{o.value=Function('return '+o.value.replace(/π/g,'Math.PI').replace(/×/g,'*').replace(/÷/g,'/').replace(/−/g,'-').replace(/√/g,'Math.sqrt').replace(/sin\(/g,'Math.sin(').replace(/cos\(/g,'Math.cos(').replace(/tan\(/g,'Math.tan(').replace(/log\(/g,'Math.log10(').replace(/\^/g,'**'))()}catch{o.value='Error'}return}o.value+=k}
function timer(){modal('Study timer',`<div class="timer"><strong id="timer-v">25:00</strong><div class="actions"><button type="button" class="btn primary" id="timer-start">Mulai</button><button type="button" class="btn" onclick="clearInterval(window.__timer)">Stop</button></div></div>`,()=>clearInterval(window.__timer),'Tutup');$('#timer-start').onclick=()=>{let s=1500;clearInterval(window.__timer);window.__timer=setInterval(()=>{s--;const x=$('#timer-v');if(!x)return clearInterval(window.__timer);x.textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;if(s<=0){clearInterval(window.__timer);toast('Sesi fokus selesai.')}},1000)}}
function convert(){modal('Konversi satuan',`<div class="form">${field('Nilai','v',1,'number')}${select('Dari','from','km',[['km','km'],['m','m'],['cm','cm'],['kg','kg'],['g','g'],['C','C'],['F','F']])}${select('Ke','to','m',[['km','km'],['m','m'],['cm','cm'],['kg','kg'],['g','g'],['C','C'],['F','F']])}<div class="output-label">Hasil</div><div id="convert-out" class="result output-box">Hasil konversi akan muncul di sini.</div></div>`,()=>{const f=new FormData($('.modal-body')),v=Number(f.get('v')),a=f.get('from'),b=f.get('to');let r=v;if(a==='km'&&b==='m')r=v*1000;else if(a==='m'&&b==='km')r=v/1000;else if(a==='m'&&b==='cm')r=v*100;else if(a==='cm'&&b==='m')r=v/100;else if(a==='kg'&&b==='g')r=v*1000;else if(a==='g'&&b==='kg')r=v/1000;else if(a==='C'&&b==='F')r=v*9/5+32;else if(a==='F'&&b==='C')r=(v-32)*5/9;$('#convert-out').textContent=`Hasil: ${r}`},'Konversi')}
function gradeCalc(){modal('Kalkulator nilai',`<div class="form">${field('Nilai tugas','a',80,'number')}${field('Bobot tugas (%)','aw',40,'number')}${field('Nilai ujian','b',80,'number')}${field('Bobot ujian (%)','bw',60,'number')}<div class="output-label">Hasil</div><div id="gr" class="result output-box">Hasil akan muncul di sini.</div></div>`,()=>{const f=new FormData($('.modal-body')),aw=Number(f.get('aw')),bw=Number(f.get('bw'));if(aw+bw!==100)return toast('Total bobot harus 100%.');const r=(Number(f.get('a'))*aw+Number(f.get('b'))*bw)/100;$('#gr').textContent=`Nilai akhir: ${r.toFixed(2)}`},'Hitung')}
function saveSettings(){const f=$('.card.form'),get=n=>f.querySelector(`[name="${n}"]`)?.value||'';Object.assign(S.profile,{name:get('name'),preferredName:get('preferredName'),university:get('university'),major:get('major'),faculty:get('faculty'),nim:get('nim'),semester:Number(get('semester')||1),targetGpa:Number(get('targetGpa')||3.75)});S.settings.theme=$('#theme-select').value;S.settings.notifications=$('#notif-toggle').checked;save();render();toast('Pengaturan disimpan')}
function toggleTheme(){S.settings.theme=S.settings.theme==='dark'?'light':'dark';save();render()}
function collectHits(q){q=String(q||'').trim().toLowerCase();const rows=[...S.tasks.map(x=>['Tugas',x.title,'tasks']),...S.notes.map(x=>['Catatan',x.title,'notes']),...S.schedule.map(x=>['Jadwal',x.name,'schedule']),...S.events.map(x=>['Agenda',x.title,'calendar'])];return q?rows.filter(x=>(x[0]+' '+x[1]).toLowerCase().includes(q)).slice(0,12):[]}
function search(q){const h=collectHits(q);modal('Hasil pencarian',h.length?h.map(x=>`<button class="search-hit" onclick="document.querySelector('.overlay').remove();go('${x[2]}')">${icon('note')}<b>${esc(x[0])}</b><span>${esc(x[1])}</span></button>`).join(''):empty('Tidak ada hasil untuk pencarian tersebut.'),()=>{},'Tutup')}
function backup(){const b=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`campusly-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function importBackup(){const i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=()=>{const f=i.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{S=merge(structuredClone(defaults),JSON.parse(r.result));save();render();toast('Backup berhasil dipulihkan')}catch{toast('Backup tidak valid')}};r.readAsText(f)};i.click()}
function resetApp(){if(confirm('Reset semua data Campusly?')){localStorage.removeItem(KEY);location.reload()}}
function render(){if(!S.profile.completed){$('#app').innerHTML=onboarding();$('#onboard-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);['name','preferredName','university','major','faculty','nim'].forEach(k=>S.profile[k]=String(f.get(k)||'').trim());S.profile.semester=Number(f.get('semester')||1);S.profile.gpa=String(f.get('gpa')||'');S.profile.targetGpa=Number(f.get('targetGpa')||3.75);S.profile.completed=true;save();render()};return}const pages={home,schedule,tasks,calendar,ai,menu,notes,finance,gpa,settings,tools};try{$('#app').innerHTML=(pages[route]||home)()}catch(e){console.error(e);$('#app').innerHTML=`<div class="fatal"><h1>Campusly mengalami kendala.</h1><p>${esc(e.message)}</p><button class="btn primary" onclick="location.reload()">Muat ulang</button></div>`}}
Object.assign(window,{go,back,render,taskModal,toggleTask,eventModal,scheduleModal,deleteSchedule,noteModal,deleteNote,financeModal,deleteFinance,gradeModal,deleteGrade,sendAI,chatModal,scanModal,paperModal,pptModal,translator,science,calcPress,timer,convert,gradeCalc,toggleTheme,saveSettings,backup,importBackup,resetApp,exportPDF,exportDOCX,exportPPT,search,changeMonth:n=>{month=new Date(month.getFullYear(),month.getMonth()+n,1);render()},monthToday:()=>{const d=new Date();month=new Date(d.getFullYear(),d.getMonth(),1);render()}});
render();
})();
