/* Campusly UX + bug-fix layer. Keeps the original app intact while fixing the high-value UI bugs. */
(function(){
  const pad=n=>String(n).padStart(2,'0');
  const escv=v=>typeof esc==='function'?esc(v):String(v??'');
  const minutes=t=>{const [h,m]=String(t||'').split(':').map(Number);return Number.isFinite(h)&&Number.isFinite(m)?h*60+m:null};
  const dateKey=(y,m,d)=>`${y}-${pad(m+1)}-${pad(d)}`;
  const isOverdue=x=>x&&!x.done&&x.deadline&&x.deadline<new Date().toISOString().slice(0,10);
  const confirmDelete=(label,fn)=>{if(window.confirm(`Hapus ${label} ini?`))fn()};

  function taskSortValue(x){return x.deadline||'9999-12-31'}
  window.tasks=function(){
    const q=String(window.__taskFilter||'').toLowerCase();
    let list=(state.tasks||[]).filter(x=>!q||[x.title,x.course,x.priority].some(v=>String(v||'').toLowerCase().includes(q)));
    list=list.slice().sort((a,b)=>{
      if(Boolean(a.done)!==Boolean(b.done))return a.done?1:-1;
      return taskSortValue(a).localeCompare(taskSortValue(b));
    });
    return `${header('WORKSPACE','Tasks','Tugas, deadline, prioritas, dan status.',`<button class="btn primary" onclick="openTask()">+ Add Task</button>`)}
      <div class="card"><div class="actions" style="margin-bottom:12px"><input class="search" style="flex:1;min-width:0" placeholder="Cari tugas..." value="${escv(window.__taskFilter||'')}" oninput="window.__taskFilter=this.value;render()"><button class="btn" onclick="window.__taskFilter='';render()">Reset</button></div>
      ${list.length?list.map(x=>{const i=state.tasks.indexOf(x);return `<div class="row"><button class="check ${x.done?'done':''}" onclick="toggleTask(${x.id})">${x.done?'✓':''}</button><div class="row-main"><div class="row-title">${escv(x.title)}</div><div class="row-meta">${escv(x.course||'Tanpa mata kuliah')} · ${escv(x.deadline||'Tanpa deadline')}${isOverdue(x)?' · <b style="color:#ff8b8b">OVERDUE</b>':''}</div></div><span class="pill">${escv(x.priority||'MEDIUM')}</span><button class="btn small" onclick="editTask(${i})">Edit</button><button class="btn small danger" onclick="deleteTask(${i})">Hapus</button></div>`}).join(''):'<div class="empty">Nggak ada task yang cocok.</div>'}</div>`;
  };
  window.editTask=function(i){const x=state.tasks[i];if(!x)return;formModal('Edit Task',`<div class="field"><label>Judul</label><input name="title" value="${escv(x.title)}" required autofocus></div><div class="field"><label>Mata kuliah</label><input name="course" value="${escv(x.course||'')}"></div><div class="field"><label>Deadline</label><input name="deadline" type="date" value="${escv(x.deadline||'')}"></div><div class="field"><label>Prioritas</label><select name="priority"><option ${x.priority==='HIGH'?'selected':''}>HIGH</option><option ${x.priority==='MEDIUM'||!x.priority?'selected':''}>MEDIUM</option><option ${x.priority==='LOW'?'selected':''}>LOW</option></select></div>`,'saveTaskEdit');window.__editTask=i};
  window.saveTaskEdit=function(e){e.preventDefault();const i=window.__editTask,f=new FormData(e.target);if(state.tasks[i])Object.assign(state.tasks[i],{title:String(f.get('title')||'').trim(),course:String(f.get('course')||''),deadline:String(f.get('deadline')||''),priority:String(f.get('priority')||'MEDIUM')});save();closeOverlay();render();toast('Task diperbarui')};
  window.deleteTask=function(i){confirmDelete('task',()=>{state.tasks.splice(i,1);save();render();toast('Task dihapus')})};

  window.notes=function(){return `${header('WORKSPACE','Notes','Catatan kuliah, ide, dan bahan belajar.',`<button class="btn primary" onclick="openNote()">+ Add Note</button>`)}<div class="grid three">${(state.notes||[]).map((n,i)=>`<div class="card"><div class="card-head"><h2>${escv(n.title)}</h2><div class="actions"><button class="btn small" onclick="editNote(${i})">Edit</button><button class="btn small danger" onclick="deleteNote(${n.id})">Hapus</button></div></div><p class="muted" style="white-space:pre-wrap">${escv(n.body)}</p></div>`).join('')||'<div class="card"><div class="empty">Masih kosong.</div></div>'}</div>`};
  window.editNote=function(i){const n=state.notes[i];if(!n)return;formModal('Edit Note',`<div class="field"><label>Judul</label><input name="title" value="${escv(n.title)}" required autofocus></div><div class="field"><label>Isi</label><textarea name="body">${escv(n.body||'')}</textarea></div>`,'saveNoteEdit');window.__editNote=i};
  window.saveNoteEdit=function(e){e.preventDefault();const i=window.__editNote,f=new FormData(e.target);if(state.notes[i])Object.assign(state.notes[i],{title:String(f.get('title')||'').trim(),body:String(f.get('body')||'')});save();closeOverlay();render();toast('Note diperbarui')};

  function classConflict(candidate,ignore){const a=minutes(candidate.start),b=minutes(candidate.end);if(a===null||b===null||b<=a)return 'Jam mulai/selesai tidak valid.';for(let i=0;i<state.schedule.length;i++){if(i===ignore)continue;const x=state.schedule[i];if(x.day!==candidate.day)continue;const c=minutes(x.start),d=minutes(x.end);if(c!==null&&d!==null&&a<d&&b>c)return `Bentrok dengan ${x.name} (${x.start}–${x.end}).`}return ''}
  window.schedule=function(){return `${header('ACADEMIC','Jadwal','Kelas mingguan + deteksi bentrok.',`<button class="btn primary" onclick="openClass()">+ Add Class</button>`)}<div class="card">${(state.schedule||[]).map((c,i)=>`<div class="row"><div class="row-main"><div class="row-title">${escv(c.name)}</div><div class="row-meta">${escv(c.day)} · ${escv(c.room||'Tanpa ruangan')}</div></div><span class="pill">${escv(c.start||'')}–${escv(c.end||'')}</span><button class="btn small" onclick="editClass(${i})">Edit</button><button class="btn small danger" onclick="deleteClass(${i})">Hapus</button></div>`).join('')||'<div class="empty">Belum ada jadwal.</div>'}</div>`};
  window.editClass=function(i){const x=state.schedule[i];if(!x)return;formModal('Edit Jadwal',`<div class="field"><label>Mata kuliah</label><input name="name" value="${escv(x.name)}" required></div><div class="field"><label>Hari</label><select name="day">${['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'].map(d=>`<option ${x.day===d?'selected':''}>${d}</option>`).join('')}</select></div><div class="field"><label>Mulai</label><input name="start" type="time" value="${escv(x.start||'')}"></div><div class="field"><label>Selesai</label><input name="end" type="time" value="${escv(x.end||'')}"></div><div class="field"><label>Ruangan</label><input name="room" value="${escv(x.room||'')}"></div>`,'saveClassEdit');window.__editClass=i};
  window.saveClassEdit=function(e){e.preventDefault();const i=window.__editClass,f=new FormData(e.target),x={name:String(f.get('name')||'').trim(),day:String(f.get('day')||''),start:String(f.get('start')||''),end:String(f.get('end')||''),room:String(f.get('room')||'')},err=classConflict(x,i);if(err){toast(err);return}state.schedule[i]=x;save();closeOverlay();render();toast('Jadwal diperbarui')};
  window.deleteClass=function(i){confirmDelete('jadwal',()=>{state.schedule.splice(i,1);save();render();toast('Jadwal dihapus')})};
  const oldSaveClass=window.saveClass;window.saveClass=function(e){e.preventDefault();const f=new FormData(e.target),x={name:String(f.get('name')||'').trim(),day:String(f.get('day')||''),start:String(f.get('start')||''),end:String(f.get('end')||''),room:String(f.get('room')||'')},err=classConflict(x,-1);if(err){toast(err);return}state.schedule.push(x);save();closeOverlay();render();toast('Jadwal ditambahkan')};

  let calMonth=new Date();
  window.calendar=function(){const now=new Date(),y=calMonth.getFullYear(),m=calMonth.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();let cells='';for(let i=0;i<42;i++){const n=i-first+1;if(n<1||n>days){cells+=`<div class="cal-cell muted-day"><b>${n<1?new Date(y,m,0).getDate()+n:n-days}</b></div>`;continue}const iso=dateKey(y,m,n),ev=(state.calendarEvents||[]).map((e,idx)=>({...e,__i:idx})).filter(e=>e.date===iso);cells+=`<div class="cal-cell ${now.getFullYear()===y&&now.getMonth()===m&&now.getDate()===n?'today':''}"><b>${n}</b>${ev.map(e=>`<div class="event" title="${escv(e.title)}" onclick="editEvent(${e.__i})">${escv(e.title)}</div>`).join('')}</div>`}return `${header('PLANNER','Calendar',`${calMonth.toLocaleDateString('id-ID',{month:'long',year:'numeric'})} · agenda dan deadline.`,`<div class="actions"><button class="btn" onclick="calendarPrev()">‹</button><button class="btn" onclick="calendarToday()">Hari ini</button><button class="btn" onclick="calendarNext()">›</button><button class="btn primary" onclick="openEvent()">+ Add Event</button></div>`)}<div class="card calendar"><div class="cal-head">${['Min','Sen','Sel','Rab','Kam','Jum','Sab'].map(x=>`<div>${x}</div>`).join('')}</div><div class="cal-grid">${cells}</div></div>`};
  window.calendarPrev=()=>{calMonth=new Date(calMonth.getFullYear(),calMonth.getMonth()-1,1);render()};
  window.calendarNext=()=>{calMonth=new Date(calMonth.getFullYear(),calMonth.getMonth()+1,1);render()};
  window.calendarToday=()=>{calMonth=new Date();render()};
  window.editEvent=function(i){const x=state.calendarEvents[i];if(!x)return;formModal('Edit Event',`<div class="field"><label>Judul</label><input name="title" value="${escv(x.title)}" required></div><div class="field"><label>Tanggal</label><input name="date" type="date" value="${escv(x.date)}" required></div>`,'saveEventEdit');window.__editEvent=i};
  window.saveEventEdit=function(e){e.preventDefault();const i=window.__editEvent,f=new FormData(e.target);if(state.calendarEvents[i])Object.assign(state.calendarEvents[i],{title:String(f.get('title')||'').trim(),date:String(f.get('date')||'')});save();closeOverlay();render();toast('Event diperbarui')};
  window.saveEvent=function(e){e.preventDefault();const f=new FormData(e.target);state.calendarEvents.push({title:String(f.get('title')||'').trim(),date:String(f.get('date')||'')});save();closeOverlay();render();toast('Event ditambahkan')};

  window.semester=function(){return `${header('ACADEMIC','Semester','Mata kuliah dan beban SKS.',`<button class="btn primary" onclick="openCourse()">+ Add Course</button>`)}<div class="card">${(state.courses||[]).map((c,i)=>`<div class="row"><div class="row-main"><div class="row-title">${escv(c.name)} ${c.code?`· ${escv(c.code)}`:''}</div><div class="row-meta">${Number(c.credits)||0} SKS · ${escv(c.lecturer||'Dosen belum diisi')}</div></div><button class="btn small" onclick="editCourse(${i})">Edit</button><button class="btn small danger" onclick="deleteItem('courses',${i})">Hapus</button></div>`).join('')||'<div class="empty">Belum ada mata kuliah.</div>'}</div>`};
  window.editCourse=function(i){const x=state.courses[i];if(!x)return;formModal('Edit Mata Kuliah',`<div class="field"><label>Nama</label><input name="name" value="${escv(x.name)}" required></div><div class="field"><label>Kode</label><input name="code" value="${escv(x.code||'')}"></div><div class="field"><label>SKS</label><input name="credits" type="number" min="1" value="${Number(x.credits)||1}" required></div><div class="field"><label>Dosen</label><input name="lecturer" value="${escv(x.lecturer||'')}"></div>`,'saveCourseEdit');window.__editCourse=i};
  window.saveCourseEdit=function(e){e.preventDefault();const i=window.__editCourse,f=new FormData(e.target);state.courses[i]={name:String(f.get('name')||'').trim(),code:String(f.get('code')||''),credits:Number(f.get('credits')||0),lecturer:String(f.get('lecturer')||'')};save();closeOverlay();render();toast('Mata kuliah diperbarui')};

  window.gpa=function(){const records=state.gpaRecords||[],total=records.reduce((a,x)=>a+(Number(x.credits)||0)*(Number(x.grade)||0),0),credits=records.reduce((a,x)=>a+(Number(x.credits)||0),0),calc=credits?total/credits:(Number(state.profile.gpa)||0);return `${header('ACADEMIC','GPA','Masukkan nilai untuk menghitung IPK semester ini.',`<button class="btn primary" onclick="openGrade()">+ Add Nilai</button>`)}<div class="grid two"><div class="card"><div class="stat-label">IPK hasil perhitungan</div><div class="stat-value">${calc?calc.toFixed(2):'—'}</div><p class="muted">${credits} SKS tercatat.</p></div><div class="card"><div class="stat-label">Target</div><div class="stat-value">${Number(state.profile.targetGpa||3.75).toFixed(2)}</div><p class="muted">Edit target di Settings.</p></div></div><div class="card">${records.map((x,i)=>`<div class="row"><div class="row-main"><div class="row-title">${escv(x.name)}</div><div class="row-meta">${x.credits} SKS · nilai ${x.grade}</div></div><button class="btn small" onclick="editGrade(${i})">Edit</button><button class="btn small danger" onclick="deleteItem('gpaRecords',${i})">Hapus</button></div>`).join('')||'<div class="empty">Belum ada nilai.</div>'}</div>`};
  window.editGrade=function(i){const x=state.gpaRecords[i];if(!x)return;formModal('Edit Nilai',`<div class="field"><label>Mata kuliah</label><input name="name" value="${escv(x.name)}" required></div><div class="field"><label>SKS</label><input name="credits" type="number" min="1" value="${x.credits}" required></div><div class="field"><label>Nilai 0–4</label><input name="grade" type="number" min="0" max="4" step=".01" value="${x.grade}" required></div>`,'saveGradeEdit');window.__editGrade=i};
  window.saveGradeEdit=function(e){e.preventDefault();const i=window.__editGrade,f=new FormData(e.target);state.gpaRecords[i]={name:String(f.get('name')||'').trim(),credits:Number(f.get('credits')||0),grade:Number(f.get('grade')||0)};save();closeOverlay();render();toast('Nilai diperbarui')};

  window.documents=function(){return `${header('WORKSPACE','Documents','Baca file teks tanpa bikin browser ngehang.') }<div class="card"><div class="field"><label>Pilih file</label><input type="file" id="docFile" accept=".txt,.md,.csv,.json,.html,.htm,text/*" onchange="readDocument(this)"></div><div id="docOut" class="doc" style="margin-top:12px">Belum ada file.</div><p class="muted" style="margin-top:10px">PDF/DOCX/XLSX akan kita sambungkan ke extractor server setelah auth/data sync dipasang.</p></div>`};
  window.readDocument=function(input){const f=input.files?.[0];if(!f)return;if(f.size>5*1024*1024){toast('File maksimal 5 MB untuk preview cepat.');input.value='';return}const r=new FileReader();r.onload=()=>{const out=document.getElementById('docOut');if(out)out.textContent=String(r.result||'')};r.onerror=()=>toast('File gagal dibaca.');r.readAsText(f)};

  const oldRender=window.render;
  window.render=function(){oldRender();};
  setTimeout(()=>{if(typeof render==='function')render()},0);
})();
