/* Campusly — clean Gen-Z UX layer
   Keeps one source of truth for profile, theme, home and menu.
*/
(()=>{
  const KEY='campusly_state_v3';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
  const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
  const escx=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const todayKey=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const fmtDate=d=>new Date(d).toLocaleDateString('id-ID',{day:'numeric',month:'short'});
  const notify=(title,body)=>{if(!('Notification'in window))return;if(Notification.permission==='granted')new Notification(title,{body})};

  window.campuslyOnboard=()=>{
    const s=read();s.profile=s.profile||{};
    const p=s.profile;
    const body=`<div class="onboard-intro"><span class="onboard-mark">C</span><h2>Kenalan dulu, yuk 👋</h2><p>Isi data kuliah lo sekali. Setelah itu dashboard, AI, tugas, jadwal, dan rekomendasi Campusly bisa lebih nyambung sama kebutuhan lo.</p></div><div class="form"><label class="field"><span>Nama panggilan</span><input id="ob-name" value="${escx(p.preferredName||'')}" placeholder="Contoh: Rizky" required></label><label class="field"><span>Universitas / kampus</span><input id="ob-uni" value="${escx(p.university||'')}" placeholder="Nama kampus" required></label><label class="field"><span>Jurusan / prodi</span><input id="ob-major" value="${escx(p.major||'')}" placeholder="Informatika" required></label><label class="field"><span>Semester</span><select id="ob-sem">${Array.from({length:14},(_,i)=>`<option value="${i+1}" ${Number(p.semester||1)===i+1?'selected':''}>Semester ${i+1}</option>`).join('')}</select></label><label class="field"><span>GPA sekarang <small>(opsional)</small></span><input id="ob-gpa" type="number" min="0" max="4" step="0.01" value="${escx(p.gpa||'')}" placeholder="3.50"></label><label class="field"><span>Target GPA</span><input id="ob-target" type="number" min="0" max="4" step="0.01" value="${escx(p.targetGpa||3.75)}"></label></div>`;
    modal('Bikin Campusly jadi personal',body,()=>{
      const name=document.getElementById('ob-name').value.trim();
      const uni=document.getElementById('ob-uni').value.trim();
      const major=document.getElementById('ob-major').value.trim();
      if(!name||!uni||!major)return toast('Nama, kampus, dan prodi wajib diisi dulu.');
      const x=read();x.profile={...(x.profile||{}),preferredName:name,name,university:uni,major,semester:Number(document.getElementById('ob-sem').value||1),gpa:Number(document.getElementById('ob-gpa').value||0),targetGpa:Number(document.getElementById('ob-target').value||3.75),onboarded:true};write(x);closeModal();render();toast('Sip. Campusly udah kenal lo 👌');
    },'Mulai pakai Campusly');
  };

  window.home=function(){
    const s=read(),p=s.profile||{},tasks=(s.tasks||[]).filter(x=>!x.done).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'9999')),events=(s.events||[]).filter(x=>x.date===todayKey()),today=new Date(),overdue=tasks.filter(x=>x.deadline&&x.deadline<todayKey()),next=tasks.slice(0,4);
    return `<div class="home-new"><div class="home-greet"><span class="eyebrow">CAMPUSLY</span><h1>Yo, ${escx(p.preferredName||'mahasiswa')} 👋</h1><p>${tasks.length?`Ada <b>${tasks.length} tugas</b> yang belum kelar.`:'Inbox tugas lo masih aman.'} ${events.length?`Hari ini ada <b>${events.length} agenda</b>.`:'Hari ini belum ada agenda.'}</p></div><div class="home-cta"><button class="btn primary" onclick="taskModal()">＋ Tambah tugas</button><button class="btn" onclick="go('schedule')">${icon('calendar')} Lihat jadwal</button></div></div><div class="focus-strip"><div><span>Yang perlu lo lakuin</span><strong>${overdue.length?'Ada deadline kelewat 😬':tasks.length?'Berantas tugas dulu 🔥':'Nikmati hari lo 😎'}</strong></div><button class="btn" onclick="${tasks.length?'go(\'tasks\')':'taskModal()'}">${overdue.length?'Cek yang telat':tasks.length?'Mulai ngerjain':'Tambah tugas'}</button></div><div class="dash-grid"><article class="dash-card wide"><div class="dash-title"><div><span class="eyebrow">PRIORITAS</span><h2>Tugas yang paling dekat</h2></div><button class="link" onclick="go('tasks')">Semua tugas →</button></div>${next.map(t=>`<div class="dash-task"><button class="check" onclick="toggleTask('${escx(t.id)}')"></button><div><b>${escx(t.title)}</b><small>${escx(t.course||'Tanpa mata kuliah')} · ${t.deadline?fmtDate(t.deadline):'tanpa deadline'}</small></div></div>`).join('')||'<div class="empty"><p>Belum ada tugas. Tambahin yang pertama biar dashboard lo langsung berguna.</p><button class="btn" onclick="taskModal()">Tambah tugas</button></div>'}</article><article class="dash-card"><span class="eyebrow">HARI INI</span><h2>${today.toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long'})}</h2>${events.map(e=>`<div class="mini-event"><b>${escx(e.time||'—')}</b><span>${escx(e.title)}</span></div>`).join('')||'<p class="muted">Belum ada agenda hari ini.</p>'}<button class="btn full" onclick="eventModal()">＋ Tambah agenda</button></article></div><div class="utility-row"><button onclick="go('ai')"><span>✦</span><b>AI tools</b><small>Scan · makalah · PPT · gambar</small></button><button onclick="go('tools')"><span>⌘</span><b>Tools</b><small>Kalkulator · translate · timer</small></button><button onclick="go('notes')"><span>▱</span><b>Catatan</b><small>Simpan materi penting</small></button></div>`;
  };

  window.menu=function(){return `<div class="menu-new"><span class="eyebrow">MORE</span><h1>Menu</h1><p>Akses fitur penting tanpa bikin lo muter-muter.</p><div class="menu-section"><button onclick="go('schedule')"><span>📚</span><div><b>Jadwal kuliah</b><small>Atur kelas mingguan, dosen, jam, dan ruangan</small></div><i>›</i></button><button onclick="go('tools')"><span>🧰</span><div><b>Tools kuliah</b><small>Kalkulator sains, translator, timer, konversi</small></div><i>›</i></button><button onclick="go('notes')"><span>📝</span><div><b>Catatan</b><small>Simpan materi, ide, dan rangkuman</small></div><i>›</i></button><button onclick="go('settings')"><span>⚙️</span><div><b>Profil & pengaturan</b><small>Data kuliah, tema, dan notifikasi</small></div><i>›</i></button></div><div class="dev-mini"><div class="dev-mini-avatar">R</div><div><span>Developer</span><b>Rizky Khoilillu Rochman</b><small><a href="mailto:rizkykhoilillurochman@gmail.com">Email</a> · <a href="https://instagram.com/therealramanih_" target="_blank" rel="noreferrer">Instagram</a></small></div></div></div>`};

  window.settings=function(){const s=read(),p=s.profile||{},dark=s.settings?.theme==='dark';return `<div class="settings-new"><span class="eyebrow">PROFILE</span><h1>Profil & pengaturan</h1><p>Atur data kuliah, tema, dan notifikasi lo di sini.</p><article class="card"><div class="profile-line"><div class="dev-avatar">${escx((p.preferredName||'R')[0].toUpperCase())}</div><div><b>${escx(p.preferredName||'Mahasiswa')}</b><small>${escx(p.university||'Kampus belum diisi')} · ${escx(p.major||'Prodi belum diisi')} · Semester ${p.semester||1}</small></div></div><button class="btn primary" onclick="campuslyOnboard()">Edit data kuliah</button></article><article class="card settings-card"><div class="settings-row"><div><b>Tema</b><small>${dark?'Mode gelap aktif':'Mode terang aktif'}. Bisa diganti kapan aja.</small></div><div class="theme-actions"><button class="theme-choice ${!dark?'active':''}" onclick="campuslySetTheme('light')">☀️ Terang</button><button class="theme-choice ${dark?'active':''}" onclick="campuslySetTheme('dark')">🌙 Gelap</button></div></div><div class="settings-row"><div><b>Notifikasi</b><small>Pengingat deadline dan agenda dari browser.</small></div><button class="btn" onclick="requestNotifications()">Aktifkan</button></div><div class="settings-row"><div><b>Backup data</b><small>Simpan data Campusly ke file JSON.</small></div><button class="btn" onclick="exportLocal()">Export</button></div></article><article class="card developer-inline"><span class="eyebrow">DEVELOPER</span><h2>Rizky Khoilillu Rochman</h2><p>Pengembang Campusly</p><div><a href="mailto:rizkykhoilillurochman@gmail.com">✉ rizkykhoilillurochman@gmail.com</a><a href="https://instagram.com/therealramanih_" target="_blank" rel="noreferrer">◎ @therealramanih_</a></div></article></div>};

  window.requestNotifications=()=>{if(!('Notification'in window))return toast('Browser ini belum mendukung notifikasi.');Notification.requestPermission().then(x=>toast(x==='granted'?'Notifikasi aktif 🔔':'Notifikasi belum diizinkan'))};
  window.campuslySetTheme=theme=>{if(typeof window.setTheme==='function')return window.setTheme(theme);const s=read();s.settings={...(s.settings||{}),theme:theme==='dark'?'dark':'light'};write(s);document.documentElement.dataset.theme=s.settings.theme;render()};
  window.toggleCampusTheme=()=>window.campuslySetTheme(read().settings?.theme==='dark'?'light':'dark');
  window.scheduleCampusNotifications=()=>{const s=read(),tasks=(s.tasks||[]).filter(t=>!t.done&&t.deadline);for(const t of tasks){const due=new Date(t.deadline);if(due-Date.now()<48*3600000&&due-Date.now()>0)notify('Campusly · deadline dekat',`${t.title} · ${fmtDate(t.deadline)}`)}};

  setTimeout(()=>{
    const s=read(),p=s.profile||{};
    if(!p.onboarded||!p.preferredName||!p.university||!p.major)campuslyOnboard();
    scheduleCampusNotifications();
  },650);
})();
