/* Campusly — final routing, tools and theme layer */
(()=>{
  const KEY='campusly_state_v3';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
  const coreRender=window.render;
  const coreGo=window.go;
  const escx=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  window.imageModal=()=>modal('Generate gambar',`<div class="tool-modal"><p>Deskripsiin gambar yang lo mau. Campusly bakal bikin dari prompt ini.</p><div class="form"><label class="field"><span>Prompt gambar</span><textarea id="img-prompt" placeholder="Contoh: ilustrasi mahasiswa belajar di perpustakaan modern, clean, 16:9"></textarea></label><div id="img-result" class="image-result"></div></div></div>`,async()=>{const prompt=document.getElementById('img-prompt')?.value.trim();if(!prompt)return toast('Isi prompt gambarnya dulu.');const out=document.getElementById('img-result');out.textContent='Lagi bikin gambar…';try{const r=await fetch('/api/ai/image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.image)throw new Error(d.error||'Generate gambar gagal');out.innerHTML=`<img src="${d.image}" alt="Hasil generate gambar"><a class="btn" href="${d.image}" download="campusly-gambar.png">Simpan gambar</a>`}catch(e){out.textContent='⚠️ '+(e.message||'Generate gambar gagal.')}} ,'Generate');

  window.tools=function(){return `<div class="tools-page"><span class="eyebrow">UTILITY</span><h1>Tools kuliah</h1><p>Yang kecil-kecil tapi sering kepake. Pilih aja.</p><div class="tool-grid"><button type="button" onclick="scienceCalc()"><b>🧮 Kalkulator sains</b><small>sin, cos, tan, log, √, pangkat</small></button><button type="button" onclick="translator()"><b>🌐 Translator</b><small>Terjemahin teks ke bahasa yang lo mau</small></button><button type="button" onclick="studyTimer()"><b>⏱ Study timer</b><small>Pomodoro buat fokus belajar</small></button><button type="button" onclick="unitConvert()"><b>↔️ Konversi satuan</b><small>Panjang, berat, suhu, waktu</small></button><button type="button" onclick="gradeCalc()"><b>📊 Kalkulator nilai</b><small>Hitung nilai akhir dengan bobot</small></button><button type="button" onclick="go('schedule')"><b>📚 Jadwal kuliah</b><small>Lihat kelas mingguan lo</small></button></div></div>`};

  window.scienceCalc=()=>{modal('Kalkulator sains',`<div class="calc"><input id="calc-out" readonly placeholder="0"><div class="calc-keys">${['7','8','9','/','4','5','6','*','1','2','3','-','0','.','(',')','sin','cos','tan','log','√','^','π','C','='].map(k=>`<button type="button" onclick="calcPress('${k}')">${k}</button>`).join('')}</div></div>`,()=>closeModal(),'Tutup');document.getElementById('modal-save').onclick=()=>closeModal()};
  window.calcPress=k=>{const o=document.getElementById('calc-out');if(!o)return;if(k==='C'){o.value='';return}if(k==='='){try{let e=o.value.replace(/π/g,'Math.PI').replace(/√/g,'Math.sqrt').replace(/\^/g,'**').replace(/sin\(/g,'Math.sin(').replace(/cos\(/g,'Math.cos(').replace(/tan\(/g,'Math.tan(').replace(/log\(/g,'Math.log10(');o.value=Function('"use strict";return '+e)()}catch{o.value='Error'}return}o.value+=k};

  async function aiCall(prompt){const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:prompt}],context:JSON.stringify(read())})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.text)throw new Error(d.error||'AI gagal');return d.text}
  window.translator=()=>modal('Translator',`<div class="form"><label class="field"><span>Ke bahasa</span><input id="tr-to" value="English" placeholder="Indonesia, English, Japanese, dll"></label><label class="field"><span>Teks</span><textarea id="tr-text" placeholder="Tulis teks yang mau diterjemahin..."></textarea></label><div id="tr-result" class="result"></div></div>`,async()=>{const text=document.getElementById('tr-text').value.trim(),to=document.getElementById('tr-to').value.trim()||'English';if(!text)return toast('Tulis teks dulu.');const out=document.getElementById('tr-result');out.textContent='Lagi nerjemahin…';try{out.textContent=await aiCall(`Terjemahkan teks berikut ke ${to}. Pertahankan makna, konteks, dan format. Jangan kasih komentar tambahan.\n\n${text}`)}catch(e){out.textContent='⚠️ '+e.message}},'Translate');
  window.gradeCalc=()=>modal('Kalkulator nilai',`<div class="form"><label class="field"><span>Nilai tugas</span><input id="g1" type="number" value="80"></label><label class="field"><span>Bobot tugas (%)</span><input id="w1" type="number" value="40"></label><label class="field"><span>Nilai ujian</span><input id="g2" type="number" value="80"></label><label class="field"><span>Bobot ujian (%)</span><input id="w2" type="number" value="60"></label><div id="grade-result" class="result"></div></div>`,()=>{const r=(+g1.value*+w1.value+ +g2.value*+w2.value)/100;document.getElementById('grade-result').textContent=`Nilai akhir: ${r.toFixed(2)}`},'Hitung');
  window.studyTimer=()=>{modal('Study timer',`<div class="timer"><strong id="timer-num">25:00</strong><div class="actions"><button class="btn primary" id="timer-go" type="button">Mulai</button><button class="btn" type="button" onclick="clearInterval(window.__studyTimer)">Stop</button></div></div>`,()=>closeModal(),'Tutup');document.getElementById('modal-save').onclick=()=>closeModal();document.getElementById('timer-go').onclick=()=>{let sec=1500;clearInterval(window.__studyTimer);window.__studyTimer=setInterval(()=>{sec--;const el=document.getElementById('timer-num');if(!el){clearInterval(window.__studyTimer);return}el.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(sec<=0){clearInterval(window.__studyTimer);if('Notification'in window&&Notification.permission==='granted')new Notification('Campusly',{body:'Sesi fokus selesai. Istirahat bentar 😌'});toast('Sesi fokus selesai. Istirahat bentar 😌')}},1000)}};
  window.unitConvert=()=>modal('Konversi satuan',`<div class="form"><label class="field"><span>Nilai</span><input id="uc-v" type="number" value="1"></label><label class="field"><span>Dari</span><select id="uc-from"><option>km</option><option>m</option><option>cm</option><option>kg</option><option>g</option><option>C</option><option>F</option></select></label><label class="field"><span>Ke</span><select id="uc-to"><option>m</option><option>km</option><option>cm</option><option>g</option><option>kg</option><option>C</option><option>F</option></select></label><div id="uc-r" class="result"></div></div>`,()=>{const v=+document.getElementById('uc-v').value,f=document.getElementById('uc-from').value,t=document.getElementById('uc-to').value;let r=v;if(f==='km'&&t==='m')r=v*1000;else if(f==='m'&&t==='km')r=v/1000;else if(f==='m'&&t==='cm')r=v*100;else if(f==='cm'&&t==='m')r=v/100;else if(f==='kg'&&t==='g')r=v*1000;else if(f==='g'&&t==='kg')r=v/1000;else if(f==='C'&&t==='F')r=v*9/5+32;else if(f==='F'&&t==='C')r=(v-32)*5/9;document.getElementById('uc-r').textContent=`Hasil: ${r}`},'Konversi');

  const renderTools=()=>{const app=document.getElementById('app');if(!app)return;app.innerHTML=typeof shell==='function'?shell(tools()):tools();};
  const renderSchedule=()=>{const app=document.getElementById('app');if(!app)return;app.innerHTML=typeof shell==='function'?shell('<div id="schedule-root"></div>'):'<div id="schedule-root"></div>';window.CampuslySchedule?.render()};
  window.render=function(){if(location.hash==='#tools'){renderTools();return}if(location.hash==='#schedule'){renderSchedule();return}return coreRender?.()};
  window.go=function(r){if(r==='tools'){if(location.hash==='#tools')renderTools();else location.hash='tools';return}if(r==='schedule'){if(location.hash==='#schedule')renderSchedule();else location.hash='schedule';return}return coreGo?.(r)};
  addEventListener('hashchange',()=>{if(location.hash==='#tools')renderTools();else if(location.hash==='#schedule')renderSchedule()});

  const readTheme=()=>read().settings?.theme==='dark'?'dark':'light';
  const setTheme=theme=>{const t=theme==='dark'?'dark':'light';const s=read();s.settings={...(s.settings||{}),theme:t};localStorage.setItem(KEY,JSON.stringify(s));document.documentElement.dataset.theme=t;document.documentElement.style.colorScheme=t;const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=t==='dark'?'#101216':'#f5f6f8';refreshThemeButton();if(typeof window.S==='object'&&window.S)window.S.settings={...(window.S.settings||{}),theme:t}};
  window.campuslySetTheme=theme=>{setTheme(theme);window.render?.()};
  window.campuslyToggleTheme=()=>window.campuslySetTheme(readTheme()==='dark'?'light':'dark');
  function refreshThemeButton(){const b=document.querySelector('[data-theme-toggle]');if(!b)return;const dark=readTheme()==='dark';b.textContent=dark?'☀️':'🌙';b.title=dark?'Pakai tema terang':'Pakai tema gelap'}
  function ensureThemeButton(){const header=document.querySelector('.app main>header');if(!header)return;let b=header.querySelector('[data-theme-toggle]');if(!b){b=document.createElement('button');b.type='button';b.className='icon-btn';b.setAttribute('data-theme-toggle','1');header.insertBefore(b,header.querySelector('.avatar')||null);b.onclick=()=>window.campuslyToggleTheme()}refreshThemeButton()}
  const initial=readTheme();setTheme(initial);
  setTimeout(()=>{window.render?.();ensureThemeButton()},0);
  addEventListener('hashchange',()=>setTimeout(ensureThemeButton,0));
})();
