/* Campusly finance — lightweight, local-first student money tracker */
(()=>{
  const KEY='campusly_finance_v1';
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{"tx":[],"budget":0}')}catch{return {tx:[],budget:0}}};
  const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const rup=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v)||0);
  const monthKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`};
  const current=()=>monthKey(new Date());
  const data=()=>load();
  const totals=s=>{const tx=s.tx.filter(x=>monthKey(x.date)===current());return {in:tx.filter(x=>x.type==='in').reduce((a,x)=>a+x.amount,0),out:tx.filter(x=>x.type==='out').reduce((a,x)=>a+x.amount,0),tx}};
  window.finance=()=>{const s=data(),t=totals(s),bal=t.in-t.out,budget=Number(s.budget)||0,remain=budget-t.out;return `<div class="finance-page"><div class="finance-head"><div><span class="eyebrow">MONEY</span><h1>Keuangan</h1><p>Biar uang bulanan nggak tiba-tiba menghilang entah ke mana 😭</p></div><button class="btn primary" onclick="financeAdd()">＋ Catat transaksi</button></div><div class="finance-cards"><article><small>Saldo bulan ini</small><strong>${rup(bal)}</strong><span>${t.in?`Masuk ${rup(t.in)}`:'Belum ada pemasukan'}</span></article><article><small>Pengeluaran</small><strong>${rup(t.out)}</strong><span>${budget?`${rup(Math.max(0,remain))} sisa budget`:'Belum ada budget'}</span></article><article><small>Budget bulanan</small><strong>${budget?rup(budget):'—'}</strong><button class="link" onclick="financeBudget()">Atur budget</button></article></div><article class="card finance-list"><div class="card-head"><div><h2>Transaksi bulan ini</h2><p>${t.tx.length} catatan</p></div><button class="btn" onclick="financeAdd()">＋ Tambah</button></div>${t.tx.slice().sort((a,b)=>new Date(b.date)-new Date(a.date)).map(x=>`<div class="finance-row"><div class="money-icon ${x.type}">${x.type==='in'?'↓':'↑'}</div><div><b>${esc(x.title)}</b><small>${esc(x.category)} · ${new Date(x.date).toLocaleDateString('id-ID',{day:'numeric',month:'short'})}</small></div><strong class="${x.type}">${x.type==='in'?'+':'−'}${rup(x.amount)}</strong><button class="icon-btn" onclick="financeDelete('${esc(x.id)}')" aria-label="Hapus">×</button></div>`).join('')||'<div class="empty"><p>Belum ada transaksi bulan ini.</p><button class="btn" onclick="financeAdd()">Catat yang pertama</button></div>'}</article><article class="card finance-tip"><b>💡 Tip</b><span>Catat uang masuk dan keluar sekecil apa pun. Nanti Campusly bisa bantu lo lihat pola pengeluaran bulanan.</span></article></div>`};
  window.financeAdd=()=>{const body=`<div class="form"><label class="field"><span>Jenis</span><select id="fin-type"><option value="out">Pengeluaran</option><option value="in">Pemasukan</option></select></label><label class="field"><span>Nominal</span><input id="fin-amount" type="number" min="0" step="1000" placeholder="50000"></label><label class="field"><span>Keperluan</span><input id="fin-title" placeholder="Makan siang, bensin, freelance..."></label><label class="field"><span>Kategori</span><select id="fin-cat"><option>Makan</option><option>Transport</option><option>Kuliah</option><option>Hiburan</option><option>Tagihan</option><option>Belanja</option><option>Gaji/Freelance</option><option>Beasiswa</option><option>Lainnya</option></select></label><label class="field"><span>Tanggal</span><input id="fin-date" type="date" value="${new Date().toISOString().slice(0,10)}"></label></div>`;modal('Catat transaksi',body,()=>{const amount=Number(document.getElementById('fin-amount').value),title=document.getElementById('fin-title').value.trim();if(!amount||amount<0)return toast?.('Nominalnya isi dulu ya.');if(!title)return toast?.('Kasih nama transaksinya dulu.');const s=data();s.tx.push({id:Date.now().toString(36)+Math.random().toString(36).slice(2,6),type:document.getElementById('fin-type').value,amount,title,category:document.getElementById('fin-cat').value,date:document.getElementById('fin-date').value});save(s);closeModal();render();toast?.('Transaksi dicatat ✨')},'Simpan');};
  window.financeDelete=id=>{const s=data();s.tx=s.tx.filter(x=>x.id!==id);save(s);render();toast?.('Transaksi dihapus')};
  window.financeBudget=()=>modal('Budget bulanan',`<div class="form"><label class="field"><span>Batas pengeluaran bulan ini</span><input id="fin-budget" type="number" min="0" value="${Number(data().budget)||''}" placeholder="2000000"></label><p class="muted">Budget disimpan hanya di perangkat ini.</p></div>`,()=>{const s=data();s.budget=Number(document.getElementById('fin-budget').value)||0;save(s);closeModal();render();toast?.('Budget disimpan 👍')},'Simpan');
  const originalMenu=window.menu;window.menu=()=>{const base=originalMenu?.()||'';return base.replace('</div></div>',`<button onclick="go('finance')"><span>💸</span><div><b>Keuangan</b><small>Catat pemasukan, pengeluaran & budget</small></div><i>›</i></button></div></div>`)};
  const originalRender=window.render;window.render=function(){if(location.hash==='#finance'){const app=document.getElementById('app');if(app)app.innerHTML=typeof shell==='function'?shell(finance()):finance();return}return originalRender?.()};
  const originalGo=window.go;window.go=function(r){if(r==='finance'){location.hash='finance';return}return originalGo?.(r)};
  const style=document.createElement('style');style.textContent='.finance-page{display:grid;gap:14px}.finance-head{display:flex;justify-content:space-between;align-items:end;gap:16px}.finance-head h1{font-size:clamp(36px,6vw,58px);letter-spacing:-.06em;margin:4px 0}.finance-head p{color:var(--muted);margin:0}.finance-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.finance-cards article{padding:18px;border:1px solid var(--line);border-radius:20px;background:var(--surface);box-shadow:var(--shadow)}.finance-cards small,.finance-cards span{display:block;color:var(--muted);font-size:11px}.finance-cards strong{display:block;font-size:25px;margin:8px 0}.finance-row{display:flex;align-items:center;gap:10px;padding:12px 0;border-bottom:1px solid var(--line)}.finance-row>div:nth-child(2){flex:1;min-width:0}.finance-row small{display:block;color:var(--muted);font-size:11px}.money-icon{width:36px;height:36px;border-radius:12px;display:grid;place-items:center;background:var(--surface2);font-weight:900}.finance-row strong.in{color:#16834b}.finance-row strong.out{color:#d05b5b}.finance-tip{display:flex;gap:10px;align-items:flex-start}.finance-tip span{color:var(--muted)}@media(max-width:700px){.finance-head{display:block}.finance-head .btn{margin-top:12px}.finance-cards{grid-template-columns:1fr}.finance-row .icon-btn{width:32px;height:32px}}';document.head.appendChild(style);
})();
