/* Campusly stability patch v1 */
(()=>{
  const KEY='campusly_state_v3';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
  const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
  const escx=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const state=()=>{const s=read();s.profile=s.profile||{};s.settings=s.settings||{};s.tasks=Array.isArray(s.tasks)?s.tasks:[];s.notes=Array.isArray(s.notes)?s.notes:[];s.events=Array.isArray(s.events)?s.events:[];return s};
  function setTheme(theme){const s=state();s.settings.theme=theme==='dark'?'dark':'light';write(s);document.documentElement.dataset.theme=s.settings.theme;document.documentElement.style.colorScheme=s.settings.theme;const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=s.settings.theme==='dark'?'#101216':'#f5f6f8';const b=document.querySelector('[data-theme-toggle]');if(b){b.textContent=s.settings.theme==='dark'?'☀️':'🌙';b.title=s.settings.theme==='dark'?'Pakai tema terang':'Pakai tema gelap'}}
  window.campuslySetTheme=setTheme;window.toggleCampusTheme=()=>{const s=state();setTheme(s.settings.theme==='dark'?'light':'dark');window.render?.()};window.campuslyToggleTheme=window.toggleCampusTheme;window.toggleTheme=window.toggleCampusTheme;
  function onboarding(){const s=state(),p=s.profile;if(p.onboarded&&p.university&&p.major)return;if(typeof modal!=='function')return;const body=`<div class="onboard-intro"><span class="onboard-mark">C</span><h2>Kenalan dulu 👋</h2><p>Isi data kuliah sekali. Setelah itu dashboard, AI, jadwal, dan rekomendasi Campusly bisa lebih nyambung ke lo.</p></div><div class="form"><label class="field"><span>Nama panggilan</span><input id="ob-name" value="${escx(p.preferredName||p.name||'')}" placeholder="Nama lo" required></label><label class="field"><span>Universitas / kampus</span><input id="ob-uni" value="${escx(p.university||'')}" placeholder="Nama kampus" required></label><label class="field"><span>Jurusan / prodi</span><input id="ob-major" value="${escx(p.major||'')}" placeholder="Informatika" required></label><label class="field"><span>Semester</span><select id="ob-sem">${Array.from({length:14},(_,i)=>`<option value="${i+1}" ${Number(p.semester||1)===i+1?'selected':''}>Semester ${i+1}</option>`).join('')}</select></label><label class="field"><span>GPA sekarang <small>(opsional)</small></span><input id="ob-gpa" type="number" min="0" max="4" step="0.01" value="${p.gpa||''}" placeholder="3.50"></label><label class="field"><span>Target GPA</span><input id="ob-target" type="number" min="0" max="4" step="0.01" value="${p.targetGpa||3.75}"></label></div>`;modal('Bikin Campusly jadi personal',body,()=>{const x=state(),q=x.profile;q.preferredName=document.getElementById('ob-name').value.trim();q.name=q.preferredName;q.university=document.getElementById('ob-uni').value.trim();q.major=document.getElementById('ob-major').value.trim();q.semester=Number(document.getElementById('ob-sem').value||1);q.gpa=Number(document.getElementById('ob-gpa').value||0);q.targetGpa=Number(document.getElementById('ob-target').value||3.75);if(!q.preferredName||!q.university||!q.major){toast?.('Nama, kampus, dan prodi wajib diisi.');return}q.onboarded=true;write(x);closeModal();window.render?.();toast?.('Sip. Profil lo udah siap 👌')},'Mulai pakai Campusly')}
  window.campuslyOnboard=onboarding;
  function search(q){const term=String(q||'').trim().toLowerCase();if(!term)return;const s=state(),results=[];s.tasks.forEach(t=>{if(`${t.title} ${t.course||''}`.toLowerCase().includes(term))results.push({type:'Tugas',title:t.title,sub:`${t.course||'Tanpa mata kuliah'} · ${t.deadline||'tanpa deadline'}`,action:()=>window.go?.('tasks')})});s.notes.forEach(n=>{if(`${n.title} ${n.course||''} ${n.body||''}`.toLowerCase().includes(term))results.push({type:'Catatan',title:n.title,sub:n.course||'Catatan kuliah',action:()=>window.go?.('notes')})});s.events.forEach(e=>{if(`${e.title} ${e.location||''} ${e.body||''}`.toLowerCase().includes(term))results.push({type:'Agenda',title:e.title,sub:`${e.date||''}${e.time?' · '+e.time:''}${e.location?' · '+e.location:''}`,action:()=>window.go?.('calendar')})});const pages=[['Kalender','Lihat jadwal dan agenda','calendar'],['AI','Chat, scan, makalah, PPT, gambar','ai'],['Tools','Kalkulator, translator, timer, konversi','tools'],['Catatan','Materi dan rangkuman','notes']];pages.forEach(([type,title,sub,route])=>{if(title.toLowerCase().includes(term)||sub.toLowerCase().includes(term)||type.toLowerCase().includes(term))results.push({type,title,sub,action:()=>window.go?.(route)})});const body=results.length?`<div class="search-results">${results.slice(0,12).map((r,i)=>`<button class="search-result" data-search-index="${i}"><span><b>${escx(r.title)}</b><small>${escx(r.type)} · ${escx(r.sub)}</small></span><strong>›</strong></button>`).join('')}</div>`:`<div class="empty"><p>Nggak ketemu “${escx(q)}”. Coba nama tugas, mata kuliah, catatan, atau fitur.</p></div>`;modal(`Hasil pencarian “${q}”`,body,()=>closeModal(),'Tutup');document.querySelectorAll('[data-search-index]').forEach((el,i)=>el.onclick=()=>{closeModal();results[i]?.action()});const save=document.getElementById('modal-save');if(save)save.onclick=()=>closeModal()}
  window.quickSearch=search;
  function cleanup(){document.querySelectorAll('[data-campusly-tools]').forEach(x=>x.remove());const header=document.querySelector('.app main>header');if(header&&!header.querySelector('[data-theme-toggle]')){const b=document.createElement('button');b.type='button';b.className='icon-btn';b.dataset.themeToggle='1';b.style.fontSize='17px';b.onclick=window.toggleCampusTheme;header.insertBefore(b,header.querySelector('.avatar')||null)}const s=state(),dark=s.settings.theme==='dark';document.documentElement.dataset.theme=dark?'dark':'light';const tb=document.querySelector('[data-theme-toggle]');if(tb){tb.textContent=dark?'☀️':'🌙';tb.title=dark?'Pakai tema terang':'Pakai tema gelap'}}
  const renderFixed=()=>{const app=document.getElementById('app');if(!app||typeof shell!=='function')return;const route=location.hash.slice(1)||'home';try{if(route==='schedule'){app.innerHTML=shell('<div id="schedule-root"></div>');window.CampuslySchedule?.render();cleanup();return}const pages={home:window.home,tasks:window.tasks,calendar:window.calendar,ai:window.ai,menu:window.menu,notes:window.notes,settings:window.settings,tools:window.tools};const page=pages[route]||pages.home;app.innerHTML=shell(typeof page==='function'?page():'<div class="error-card"><h1>Halaman belum tersedia</h1></div>');cleanup()}catch(e){console.error(e);app.innerHTML=shell(`<div class="error-card"><h1>Campusly lagi ngadat 😵</h1><p>${escx(e.message||'Halaman gagal dimuat.')}</p><button class="btn primary" onclick="location.reload()">Muat ulang</button></div>`)}};
  window.render=renderFixed;window.go=(r)=>{const target=String(r||'home');if(location.hash.slice(1)===target){renderFixed();return}history.pushState({},'',`#${target}`);renderFixed();window.scrollTo?.({top:0,behavior:'instant'})};addEventListener('hashchange',renderFixed);addEventListener('popstate',renderFixed);
  setTheme(state().settings.theme||'light');setTimeout(()=>{renderFixed();setTimeout(()=>{const s=state();if(!s.profile?.onboarded||!s.profile?.university||!s.profile?.major)onboarding()},120)},60);
})();
