(function(){
  function fmtDate(){return new Intl.DateTimeFormat('id-ID',{weekday:'short',day:'2-digit',month:'short',year:'numeric'}).format(new Date())}
  function liquidHome(){
    const p=state.profile||{}; const tasks=(state.tasks||[]).filter(x=>!x.done); const classes=state.schedule||[];
    const pct=Math.min(100,Math.round(((p.credits||0)/(p.totalCredits||144))*100));
    return `<div class="liquid-home">
      <div class="hero glass"><div><div class="eyebrow">SELAMAT DATANG KEMBALI</div><h1 class="hero-title">${esc(p.preferredName||p.name||'Rizky')} <span>👋</span></h1><p>Hari ini adalah hari yang baik untuk melangkah lebih maju. Keep going!</p></div><div class="hero-meta"><span>📅 ${fmtDate()}</span><span>☀️ Cerah</span></div></div>
      <div class="stats glass-grid"><div class="glass stat-card"><span>🎓 Semester</span><b>${p.semester||1}</b><small>/ 8</small></div><div class="glass stat-card"><span>📈 IPK</span><b>${p.gpa?Number(p.gpa).toFixed(2):'—'}</b><small>${p.gpa?'Saat ini':'Belum ada data'}</small></div><div class="glass stat-card"><span>🎯 Target IPK</span><b>${Number(p.targetGpa||3.75).toFixed(2)}</b><div class="mini-progress"><i style="width:${Math.min(100,Number(p.targetGpa||3.75)/4*100)}%"></i></div></div><div class="glass stat-card"><span>✓ Tugas tersisa</span><b>${tasks.length}</b><small>${tasks.length?'Perlu diberesin':'Clean slate ✨'}</small></div></div>
      <div class="liquid-columns"><div class="liquid-main">
        <div class="glass ai-hero"><div class="ai-orb">✦</div><div class="ai-copy"><div class="eyebrow">CAMPUSLY AI</div><h2>Teman belajar lo, 24/7.</h2><p>Tanya tugas, minta rangkuman, jelasin konsep, atau bikin rencana belajar.</p></div><button class="glass-button" onclick="go('ai')">Buka AI →</button><div class="ai-prompt" onclick="go('ai')">Tanya sesuatu... <span>⌘ ↵</span></div><div class="chips"><button class="chip" onclick="go('ai');setTimeout(()=>quickAI('Ringkas materi kuliah saya'),50)">📚 Ringkas materi</button><button class="chip" onclick="go('ai');setTimeout(()=>quickAI('Bantu saya mengerjakan tugas'),50)">✨ Bantu tugas</button><button class="chip" onclick="go('ai');setTimeout(()=>quickAI('Buat rencana belajar minggu ini'),50)">🗓️ Rencana belajar</button><button class="chip" onclick="go('ai');setTimeout(()=>quickAI('Jelaskan konsep yang sulit dengan sederhana'),50)">💡 Jelaskan konsep</button></div></div>
        <div class="glass"><div class="card-head"><div><div class="eyebrow">HARI INI</div><h2>Yang harus diberesin</h2></div><button class="glass-button" onclick="openTask()">+ Add Task</button></div>${tasks.slice(0,5).map(taskRow).join('')||'<div class="empty">Belum ada tugas. Nikmati clean slate lo 😌</div>'}</div>
        <div class="quick-actions glass"><button onclick="openNote()">✎<span>Buat Catatan</span><small>AI Note</small></button><button onclick="openTask()">✓<span>Tambah Tugas</span><small>Quick Add</small></button><button onclick="openClass()">◫<span>Buat Jadwal</span><small>AI Schedule</small></button><button onclick="go('gpa')">∑<span>Hitung IPK</span><small>GPA Tracker</small></button></div>
        <div class="bottom-grid"><div class="glass progress-card"><div class="card-head"><h2>Progress Kuliah</h2><span class="pill">${pct}%</span></div><div class="progress-ring" style="--pct:${pct}%"><strong>${pct}%</strong><span>Selesai</span></div><div class="course-bars">${(state.courses||[]).slice(0,4).map(c=>`<div><span>${esc(c.name)}</span><i><b style="width:${Math.min(100,Number(c.progress||0))}%"></b></i></div>`).join('')||'<div class="muted">Tambahkan mata kuliah untuk melihat progress.</div>'}</div></div><div class="glass quote-card"><span>✦</span><h2>Disiplin hari ini,<br>kesuksesan esok.</h2><p>— Campusly</p></div></div>
      </div><aside class="liquid-side"><div class="glass"><div class="card-head"><h2>Hari Ini</h2><button class="link-btn" onclick="go('tasks')">Lihat semua</button></div>${tasks.slice(0,4).map(x=>`<div class="side-task"><span class="task-dot"></span><div><b>${esc(x.title)}</b><small>${esc(x.deadline||'Tanpa deadline')}</small></div><em>${esc(x.priority||'Task')}</em></div>`).join('')||'<div class="empty">Tidak ada agenda.</div>'}</div><div class="glass"><div class="card-head"><h2>Jadwal Kuliah</h2><button class="link-btn" onclick="go('schedule')">Lihat semua</button></div>${classes.slice(0,5).map(c=>`<div class="class-row"><span class="time">${esc(c.start||'--:--')}</span><div><b>${esc(c.name)}</b><small>${esc(c.room||c.day||'')}</small></div></div>`).join('')||'<div class="empty">Belum ada jadwal.</div>'}</div></aside></div></div>`;
  }
  function aiPage(){return `${header('CAMPUSLY AI','AI Study Companion','Satu tempat buat nanya, mikir, dan beresin kuliah.',`<span class="pill">GPT powered</span>`)}<div class="ai-layout"><div class="glass ai-chat"><div id="aiMessages" class="ai-messages"><div class="ai-welcome"><div class="ai-orb large">✦</div><h2>Halo ${esc(state.profile?.preferredName||'Rizky')} 👋</h2><p>Gue bisa bantu jelasin materi, bikin rencana belajar, brainstorming tugas, atau ngerapihin ide.</p><div class="chips"><button class="chip" onclick="quickAI('Buatkan rencana belajar 7 hari untuk saya')">📅 Rencana belajar 7 hari</button><button class="chip" onclick="quickAI('Bantu saya memahami materi yang sulit')">🧠 Pahami materi</button><button class="chip" onclick="quickAI('Bantu saya menyusun tugas kuliah')">✍️ Susun tugas</button></div></div></div><form class="ai-input-wrap" onsubmit="sendAI(event)"><textarea id="aiInput" rows="2" placeholder="Tanya apa saja tentang kuliah lo..."></textarea><button class="send-ai" type="submit">↑</button></form></div><aside class="glass ai-context"><h3>Konteks lo</h3><div class="context-item"><span>🎓</span><div><small>Semester</small><b>${state.profile?.semester||1}</b></div></div><div class="context-item"><span>🎯</span><div><small>Target IPK</small><b>${Number(state.profile?.targetGpa||3.75).toFixed(2)}</b></div></div><div class="context-item"><span>✓</span><div><small>Tugas aktif</small><b>${(state.tasks||[]).filter(x=>!x.done).length}</b></div></div><hr><p class="muted">AI memakai konteks profil dan data akademik yang tersedia di Campusly.</p></aside></div>`}
  window.home=liquidHome; window.ai=aiPage;
  window.quickAI=function(text){const el=document.getElementById('aiInput');if(el){el.value=text;el.focus()}else{go('ai');setTimeout(()=>quickAI(text),50)}};
  window.sendAI=async function(e){e.preventDefault();const input=document.getElementById('aiInput'),box=document.getElementById('aiMessages'),text=(input?.value||'').trim();if(!text)return;input.value='';const user=document.createElement('div');user.className='msg user';user.innerHTML=`<div>${esc(text)}</div>`;box.appendChild(user);const wait=document.createElement('div');wait.className='msg ai';wait.innerHTML='<div class="typing">Campusly AI sedang mikir<span>•••</span></div>';box.appendChild(wait);box.scrollTop=box.scrollHeight;try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'system',content:`Kamu adalah Campusly AI, asisten akademik mahasiswa. Gunakan Bahasa Indonesia yang santai, jelas, dan praktis. Nama mahasiswa: ${state.profile?.preferredName||state.profile?.name||'Rizky'}. Semester: ${state.profile?.semester||1}. Target IPK: ${state.profile?.targetGpa||3.75}. Tugas aktif: ${(state.tasks||[]).filter(x=>!x.done).length}.`},{role:'user',content:text}]})});const d=await r.json();if(!r.ok)throw new Error(d.error||'AI gagal merespons');wait.innerHTML=`<div>${esc(d.text||'AI tidak memberi jawaban.')}</div>`}catch(err){wait.innerHTML=`<div><b>AI belum bisa menjawab.</b><br><span class="muted">${esc(err.message)}</span></div>`}box.scrollTop=box.scrollHeight};
})();
