(function(){
  const esc0=window.esc||function(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]))};
  const dateLabel=()=>new Intl.DateTimeFormat('id-ID',{weekday:'short',day:'2-digit',month:'short',year:'numeric'}).format(new Date());
  const taskTime=x=>esc0(x.deadline||x.time||'Tanpa deadline');
  const todayClasses=()=>{const all=state.schedule||[];const day=new Intl.DateTimeFormat('id-ID',{weekday:'long'}).format(new Date());const key=day.slice(0,3).toLowerCase();return all.filter(c=>String(c.day||'').toLowerCase().startsWith(key)||String(c.day||'').toLowerCase()===day.toLowerCase()).sort((a,b)=>String(a.start||'').localeCompare(String(b.start||'')))};
  const financeTotal=()=>((state.finance||[]).reduce((n,x)=>n+Number(x.amount||0),0));
  function liquidHome(){
    const p=state.profile||{},tasks=(state.tasks||[]).filter(x=>!x.done),classes=todayClasses();
    const pct=Math.min(100,Math.round(((p.credits||0)/(p.totalCredits||144))*100)),saldo=financeTotal();
    return `<div class="liquid-home"><div class="liquid-columns"><div class="liquid-main">
      <div class="hero glass"><div><div class="eyebrow">SELAMAT DATANG KEMBALI</div><h1 class="hero-title">${esc0(p.preferredName||p.name||'Rizky')} <span>👋</span></h1><p>“Hari ini adalah hari yang baik untuk melangkah lebih maju. Keep going!”</p></div><div class="hero-meta"><span>☀️ 28°C · Cerah</span><span>⌖ Jakarta</span></div></div>
      <div class="glass-grid"><div class="glass stat-card"><span>🎓 · Semester</span><b>${p.semester||1}</b><small>/ 8</small><div class="mini-progress"><i style="width:${Math.min(100,Number(p.semester||1)/8*100)}%"></i></div></div><div class="glass stat-card"><span>📈 · IPK</span><b>${p.gpa?Number(p.gpa).toFixed(2):'—'}</b><small>${p.gpa?'Saat ini':'Belum ada data'}</small></div><div class="glass stat-card"><span>🎯 · Target IPK</span><b>${Number(p.targetGpa||3.75).toFixed(2)}</b><div class="mini-progress"><i style="width:${Math.min(100,Number(p.targetGpa||3.75)/4*100)}%"></i></div></div><div class="glass stat-card"><span>✓ · Tugas Tersisa</span><b>${tasks.length}</b><small>${tasks.length?'Ada tugas aktif':'Clean slate ✨'}</small></div></div>
      <div class="glass ai-hero"><div class="ai-orb">✦</div><div class="ai-copy"><div class="eyebrow">CAMPUSLY AI</div><h2>AI Assistant</h2><p>Teman belajar 24/7 untuk tugas, rangkuman materi, penjelasan konsep, dan rencana belajar.</p></div><button class="glass-button" onclick="go('ai')">Buka AI →</button><div class="ai-prompt" onclick="go('ai')">Tanyakan sesuatu... <span>⌘ K</span></div><div class="chips"><button class="chip" onclick="go('ai');setTimeout(()=>quickAI('Ringkas materi kuliah saya'),80)">📚 · Ringkas materi</button><button class="chip" onclick="go('ai');setTimeout(()=>quickAI('Bantu kerjain tugas saya'),80)">✨ · Bantu tugas</button><button class="chip" onclick="go('ai');setTimeout(()=>quickAI('Buat rencana belajar minggu ini'),80)">🗓️ · Rencana belajar</button><button class="chip" onclick="go('ai');setTimeout(()=>quickAI('Jelaskan konsep yang sulit dengan sederhana'),80)">💡 · Jelaskan konsep</button></div></div>
      <div class="quick-actions glass"><button onclick="openNote()">✎<span>Buat Catatan</span><small>AI Note</small></button><button onclick="openTask()">✓<span>Tambah Tugas</span><small>Quick Add</small></button><button onclick="openClass()">◫<span>Buat Jadwal</span><small>AI Schedule</small></button><button onclick="go('gpa')">∑<span>Hitung IPK</span><small>GPA Tracker</small></button></div>
      <div class="bottom-grid"><div class="glass progress-card"><div class="card-head"><h2>Progress Kuliah</h2><span class="pill">${pct}%</span></div><div class="progress-ring" style="--pct:${pct}%"><strong>${pct}%</strong><span>Selesai</span></div><div class="course-bars">${(state.courses||[]).slice(0,4).map(c=>`<div><span>${esc0(c.name)}</span><i><b style="width:${Math.min(100,Number(c.progress||0))}%"></b></i></div>`).join('')||'<div class="muted">Tambahkan mata kuliah untuk melihat progress.</div>'}</div></div><div class="glass quote-card"><span>✦</span><h2>Disiplin hari ini,<br>kesuksesan esok.</h2><p>— Campusly</p></div></div>
    </div><aside class="liquid-side"><div class="glass"><div class="card-head"><div><h2>Hari Ini</h2><small class="muted">${dateLabel()}</small></div><button class="link-btn" onclick="go('calendar')">Lihat Semua</button></div>${tasks.slice(0,4).map(x=>`<div class="side-task"><span class="task-dot"></span><div><b>${esc0(x.title)}</b><small>${taskTime(x)}</small></div><em>${esc0(x.priority||'Tugas')}</em></div>`).join('')||'<div class="empty">Tidak ada agenda hari ini. ✨</div>'}</div><div class="glass"><div class="card-head"><h2>Jadwal Kuliah</h2><button class="link-btn" onclick="go('schedule')">Lihat Semua</button></div>${classes.slice(0,6).map(c=>`<div class="class-row"><span class="time">${esc0(c.start||'--:--')}</span><div><b>${esc0(c.name)}</b><small>${esc0(c.room||'')} ${c.end?'· '+esc0(c.end):''}</small></div></div>`).join('')||'<div class="empty">Belum ada jadwal untuk hari ini.</div>'}</div><div class="glass quote-card"><span>🌿</span><h2>“Langkah kecil hari ini,<br>hasil besar nanti.”</h2><p>Campusly</p></div><div class="glass"><div class="card-head"><h2>Keuangan</h2><span class="pill">Saldo</span></div><div class="stat-value">Rp ${saldo.toLocaleString('id-ID')}</div><div class="progress"><span style="width:${Math.min(100,Math.max(0,saldo>0?72:0))}%"></span></div><p class="muted">Total saldo tercatat</p><button class="link-btn" onclick="go('finance')">Lihat Detail →</button></div></aside></div></div>`;
  }
  function aiPage2(){return `${header('CAMPUSLY AI','AI Study Companion','Satu tempat buat nanya, mikir, dan beresin kuliah lo.','<span class="pill">AI siap</span>')}<div class="ai-layout"><div class="glass ai-chat"><div id="aiMessages" class="ai-messages"><div class="ai-welcome"><div class="ai-orb large">✦</div><h2>Halo ${esc0(state.profile?.preferredName||'Rizky')} 👋</h2><p>Gue bisa bantu jelasin materi, bikin rencana belajar, brainstorming tugas, atau ngerapihin ide.</p><div class="chips"><button class="chip" onclick="quickAI('Buatkan rencana belajar 7 hari untuk saya')">📅 Rencana 7 hari</button><button class="chip" onclick="quickAI('Bantu saya memahami materi yang sulit')">🧠 Pahami materi</button><button class="chip" onclick="quickAI('Bantu saya menyusun tugas kuliah')">✍️ Susun tugas</button></div></div></div><form class="ai-input-wrap" onsubmit="sendAI2(event)"><textarea id="aiInput" rows="2" placeholder="Tanya apa saja tentang kuliah lo..." aria-label="Pertanyaan untuk Campusly AI"></textarea><button class="send-ai" type="submit" aria-label="Kirim">↑</button></form></div><aside class="glass ai-context"><h3>Konteks lo</h3><div class="context-item"><span>🎓</span><div><small>Semester</small><b>${state.profile?.semester||1}</b></div></div><div class="context-item"><span>🎯</span><div><small>Target IPK</small><b>${Number(state.profile?.targetGpa||3.75).toFixed(2)}</b></div></div><div class="context-item"><span>✓</span><div><small>Tugas aktif</small><b>${(state.tasks||[]).filter(x=>!x.done).length}</b></div></div><hr><p class="muted">AI memakai konteks profil dan data akademik yang tersedia di Campusly.</p></aside></div>`}
  window.home=liquidHome;window.ai=aiPage2;
  window.quickAI=function(text){const el=document.getElementById('aiInput');if(el){el.value=text;el.focus()}else{go('ai');setTimeout(()=>quickAI(text),80)}};
  async function ensureAiToken(){let t=localStorage.getItem('campusly_ai_token');if(t)return t;const seed=(crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random()).replace(/-/g,'').slice(0,24);const email=`guest_${seed}@campusly.app`,password=`Cly!${seed}9x`;const r=await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Gagal menyiapkan sesi AI');localStorage.setItem('campusly_ai_token',d.token);return d.token}
  window.sendAI2=async function(e){e.preventDefault();const input=document.getElementById('aiInput'),box=document.getElementById('aiMessages'),text=(input?.value||'').trim();if(!text)return;input.value='';const welcome=box?.querySelector('.ai-welcome');if(welcome)welcome.remove();const user=document.createElement('div');user.className='msg user';user.innerHTML='<div>'+esc0(text)+'</div>';box.appendChild(user);const wait=document.createElement('div');wait.className='msg ai';wait.innerHTML='<div>Campusly AI sedang mikir <span>•••</span></div>';box.appendChild(wait);box.scrollTop=box.scrollHeight;try{let token=await ensureAiToken();const payload={messages:[{role:'system',content:'Kamu adalah Campusly AI, asisten akademik mahasiswa. Jawab dalam Bahasa Indonesia yang santai, jelas, praktis, aman, dan jujur. Nama mahasiswa: '+(state.profile?.preferredName||state.profile?.name||'Rizky')+'. Semester: '+(state.profile?.semester||1)+'. Target IPK: '+(state.profile?.targetGpa||3.75)+'. Tugas aktif: '+((state.tasks||[]).filter(x=>!x.done).length)+'.'},{role:'user',content:text}]};let r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify(payload)});if(r.status===401){localStorage.removeItem('campusly_ai_token');token=await ensureAiToken();r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify(payload)})}const d=await r.json();if(!r.ok)throw new Error(d.error||'AI gagal merespons');wait.innerHTML='<div>'+esc0(d.text||'AI tidak memberi jawaban.')+'</div>'}catch(err){wait.innerHTML='<div><b>AI belum bisa menjawab.</b><br><span class="muted">'+esc0(err.message)+'</span></div>'}box.scrollTop=box.scrollHeight};
  if(typeof page==='function')page();
})();