(function(){
  'use strict';
  const features=[
    ['notes','Notes','Catatan & materi','▤'],['calendar','Calendar','Agenda','□'],['semester','Semester','KRS & mata kuliah','◈'],
    ['gpa','GPA','IPK & simulasi','∑'],['finance','Finance','Keuangan','◌'],['focus','Focus','Pomodoro','◷'],
    ['analytics','Analytics','Progress','▥'],['thesis','Thesis','Proyek akhir','▱'],['documents','Documents','File kuliah','▣'],
    ['tools','Academic Tools','Kalkulator & tools','✦'],['notifications','Notifications','Notifikasi','♢'],['reminders','Reminders','Pengingat','⏰'],['settings','Settings','Pengaturan','⚙']
  ];
  const go=r=>{if(typeof window.go==='function')window.go(r);else location.hash='#'+r};
  const css=`
@media(max-width:760px){
  html,body{background:#050814!important;color:#f7f9ff!important;overflow-x:hidden!important}
  body{padding-bottom:calc(104px + env(safe-area-inset-bottom,0px))!important}
  .cmd,.search .cmd{display:none!important!important;visibility:hidden!important;width:0!important;height:0!important;padding:0!important;margin:0!important;overflow:hidden!important}
  .sidebar{display:none!important}.main{margin:0!important;width:100%!important;min-width:0!important}
  .topbar{position:sticky!important;top:0!important;z-index:500!important;padding:12px 14px!important;min-height:76px!important;background:rgba(5,8,20,.86)!important;border-bottom:1px solid rgba(255,255,255,.08)!important;backdrop-filter:blur(28px) saturate(170%)!important;-webkit-backdrop-filter:blur(28px) saturate(170%)!important}
  .search{height:54px!important;width:100%!important;box-sizing:border-box!important;border-radius:19px!important;background:rgba(13,19,39,.94)!important;border:1px solid rgba(255,255,255,.18)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08),0 12px 35px rgba(0,0,0,.28)!important}
  .search input{font-size:16px!important;color:#fff!important}.search input::placeholder{color:rgba(235,241,255,.58)!important}
  .content{padding:24px 16px 32px!important;max-width:none!important}
  .mobile-nav{display:grid!important;position:fixed!important;left:10px!important;right:10px!important;bottom:calc(10px + env(safe-area-inset-bottom,0px))!important;height:76px!important;z-index:99999!important;grid-template-columns:repeat(5,minmax(0,1fr))!important;gap:4px!important;padding:6px!important;box-sizing:border-box!important;border-radius:25px!important;background:rgba(7,11,25,.94)!important;border:1px solid rgba(255,255,255,.18)!important;box-shadow:0 22px 75px rgba(0,0,0,.62),inset 0 1px 0 rgba(255,255,255,.13)!important;backdrop-filter:blur(32px) saturate(185%)!important;-webkit-backdrop-filter:blur(32px) saturate(185%)!important}
  .mobile-nav button{display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:4px!important;min-width:0!important;width:100%!important;height:100%!important;padding:6px 2px!important;margin:0!important;border:0!important;border-radius:19px!important;background:transparent!important;color:rgba(235,241,255,.58)!important;font-size:23px!important;line-height:1!important;font-weight:700!important}
  .mobile-nav button span{font-size:10px!important;line-height:1.1!important;font-weight:700!important}.mobile-nav button.active{color:#fff!important;background:linear-gradient(145deg,rgba(112,105,255,.42),rgba(55,135,255,.16))!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.17),0 7px 25px rgba(80,87,255,.24)!important}
  .cx-force-menu{position:fixed;inset:0;z-index:100000;opacity:0;pointer-events:none;transition:opacity .2s ease}.cx-force-menu.open{opacity:1;pointer-events:auto}.cx-force-backdrop{position:absolute;inset:0;background:rgba(0,0,0,.68);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px)}
  .cx-force-sheet{position:absolute;left:10px;right:10px;bottom:calc(10px + env(safe-area-inset-bottom,0px));max-height:82dvh;overflow:auto;padding:18px;border-radius:28px;background:rgba(8,13,30,.97);border:1px solid rgba(255,255,255,.16);box-shadow:0 28px 100px rgba(0,0,0,.7),inset 0 1px 0 rgba(255,255,255,.10);transform:translateY(24px);transition:transform .22s ease}.cx-force-menu.open .cx-force-sheet{transform:translateY(0)}
  .cx-force-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;margin-bottom:14px}.cx-force-head h2{margin:3px 0;font-size:23px}.cx-force-head p{margin:0;color:rgba(235,241,255,.55);font-size:12px}.cx-force-kicker{font-size:10px;letter-spacing:.18em;color:#9297ff}.cx-force-close{width:38px;height:38px;border-radius:50%;border:1px solid rgba(255,255,255,.14);background:rgba(255,255,255,.07);color:#fff;font-size:22px}
  .cx-force-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.cx-force-item{display:flex;align-items:center;gap:9px;min-width:0;text-align:left;padding:12px;border:1px solid rgba(255,255,255,.10);border-radius:17px;background:rgba(255,255,255,.045);color:#fff}.cx-force-item .ico{width:24px;text-align:center;font-size:19px}.cx-force-item b,.cx-force-item small{display:block}.cx-force-item b{font-size:12px}.cx-force-item small{font-size:9px;color:rgba(235,241,255,.48);margin-top:2px}.cx-force-item i{margin-left:auto;color:rgba(255,255,255,.38)}
  .hero,.card,.glass{background:linear-gradient(145deg,rgba(27,40,77,.80),rgba(8,14,31,.84))!important;border-color:rgba(255,255,255,.14)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.08),0 18px 55px rgba(0,0,0,.25)!important}
  .stats{grid-template-columns:1fr 1fr!important;gap:12px!important}.stats .card{min-height:145px!important}.ai-layout{display:block!important}.ai-context{display:none!important}.ai-chat{min-height:calc(100dvh - 170px)!important}.modal{max-height:88dvh!important}
}
@media(max-width:390px){.cx-force-grid{grid-template-columns:1fr}.content{padding-left:12px!important;padding-right:12px!important}.mobile-nav button{font-size:21px}.mobile-nav button span{font-size:9px}}
`;
  function style(){if(document.getElementById('cx-force-css'))return;const s=document.createElement('style');s.id='cx-force-css';s.textContent=css.replace('!important!important','!important');document.head.appendChild(s)}
  function clean(){document.querySelectorAll('.cmd,.search .cmd').forEach(x=>x.remove())}
  function menu(){let el=document.getElementById('cx-force-menu');if(!el){el=document.createElement('div');el.id='cx-force-menu';el.className='cx-force-menu';el.innerHTML='<div class="cx-force-backdrop"></div><section class="cx-force-sheet"><div class="cx-force-head"><div><div class="cx-force-kicker">CAMPUSLY</div><h2>Semua fitur</h2><p>Semua fitur Campusly, lengkap di HP.</p></div><button class="cx-force-close" aria-label="Tutup">×</button></div><div class="cx-force-grid">'+features.map(([r,n,d,i])=>'<button class="cx-force-item" data-route="'+r+'"><span class="ico">'+i+'</span><span><b>'+n+'</b><small>'+d+'</small></span><i>›</i></button>').join('')+'</div></section></div>';document.body.appendChild(el);el.querySelector('.cx-force-backdrop').onclick=()=>el.classList.remove('open');el.querySelector('.cx-force-close').onclick=()=>el.classList.remove('open');el.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{const r=b.dataset.route;el.classList.remove('open');setTimeout(()=>go(r),80)})}el.classList.add('open')}
  function nav(){const n=document.querySelector('.mobile-nav');if(!n)return;n.innerHTML='<button data-route="home">⌂<span>Home</span></button><button data-route="tasks">✓<span>Tasks</span></button><button data-route="schedule">◫<span>Jadwal</span></button><button data-route="ai">✧<span>AI</span></button><button data-menu="1">☰<span>Menu</span></button>';const r=location.hash.slice(1)||'home';n.querySelectorAll('[data-route]').forEach(b=>{b.classList.toggle('active',b.dataset.route===r);b.onclick=()=>go(b.dataset.route)});n.querySelector('[data-menu]').onclick=menu}
  function run(){if(innerWidth>760)return;style();clean();nav()}
  let t;const schedule=()=>{clearTimeout(t);t=setTimeout(run,60)};
  window.addEventListener('resize',schedule);window.addEventListener('hashchange',schedule);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});
})();
