(()=>{
const KEY='campusly_state_v3';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const schedule=()=>{try{return JSON.parse(localStorage.getItem('campusly_schedule_v1')||'[]')}catch{return[]}};
const css=()=>{if(document.getElementById('product-upgrade-css'))return;const s=document.createElement('style');s.id='product-upgrade-css';s.textContent=`
.daily-wrap{display:grid;grid-template-columns:1.35fr .65fr;gap:16px;margin-top:18px}.daily-card{border:1px solid var(--line);background:var(--surface);border-radius:26px;padding:20px;box-shadow:var(--shadow)}.daily-card h2{margin:0 0 5px}.daily-card p{margin:0;color:var(--muted)}.next-class{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:16px;padding:17px;border-radius:20px;background:var(--surface2)}.next-class strong{display:block;font-size:17px}.next-class small{display:block;color:var(--muted);margin-top:4px}.daily-list{display:grid;gap:8px;margin-top:12px}.daily-item{display:flex;align-items:center;gap:11px;padding:12px;border-radius:16px;background:var(--surface2)}.daily-dot{width:9px;height:9px;border-radius:50%;background:currentColor;flex:none}.daily-item b{font-size:14px}.daily-item small{display:block;color:var(--muted);margin-top:2px}.quick-actions{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:16px}.quick-actions button{border:1px solid var(--line);background:var(--surface);color:var(--text);border-radius:18px;padding:15px;text-align:left;cursor:pointer;transition:transform .15s ease,box-shadow .15s ease}.quick-actions button:hover{transform:translateY(-2px);box-shadow:var(--shadow)}.quick-actions b{display:block;margin-top:7px}.quick-actions small{color:var(--muted)}.smart-box{margin-top:16px;padding:15px 17px;border-radius:20px;background:var(--surface2);border:1px solid var(--line)}.smart-box strong{display:block}.smart-box span{display:block;color:var(--muted);font-size:13px;margin-top:4px}.upgrade-section{margin-top:18px}.upgrade-section h2{margin:0}.upgrade-section>p{color:var(--muted)}@media(max-width:850px){.daily-wrap{grid-template-columns:1fr}.quick-actions{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.quick-actions{grid-template-columns:1fr 1fr}.daily-card{padding:16px;border-radius:20px}}
`;document.head.appendChild(s)};
function dueTasks(){const s=read();return(s.tasks||[]).filter(t=>!t.done).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'9999')).slice(0,5)}
function nextClass(){const rows=schedule(),d=new Date(),day=(d.getDay()+6)%7,mins=d.getHours()*60+d.getMinutes();return rows.filter(x=>Number(x.day)===day&&Number(x.start?.slice(0,2))*60+Number(x.start?.slice(3,5))>=mins).sort((a,b)=>a.start.localeCompare(b.start))[0]||null}
function dashboard(){const s=read(),tasks=dueTasks(),events=(s.events||[]).filter(e=>e.date===today()),nc=nextClass(),name=esc(s.profile?.preferredName||s.profile?.name||'teman'),focus=tasks[0];const focusText=focus?`Kerjain ${esc(focus.title)} dulu. Deadline ${esc(focus.deadline||'belum ditentukan')}.`:events[0]?`Agenda lo hari ini: ${esc(events[0].title)}.`:'Hari ini masih kosong. Bisa mulai 25 menit belajar biar tetap jalan.';const taskHtml=tasks.length?tasks.map(t=>`<div class="daily-item"><span class="daily-dot"></span><div><b>${esc(t.title)}</b><small>${esc(t.course||'Kuliah')} · ${esc(t.deadline||'Tanpa deadline')}</small></div></div>`).join(''):'<div class="daily-item"><div><b>Belum ada tugas aktif 🎉</b><small>Tambah tugas kalau ada yang perlu dikejar.</small></div></div>';const eventHtml=events.length?events.slice(0,4).map(e=>`<div class="daily-item"><span class="daily-dot"></span><div><b>${esc(e.title)}</b><small>${esc(e.time||'')} ${e.location?'· '+esc(e.location):''}</small></div></div>`).join(''):'<div class="daily-item"><div><b>Nggak ada agenda hari ini</b><small>Hari yang cukup lega. Gas belajar atau istirahat.</small></div></div>';const cls=nc?`<div class="next-class"><div><small>Kelas berikutnya</small><strong>${esc(nc.name)}</strong><small>${esc(nc.start)}–${esc(nc.end)} · ${esc(nc.room||'Ruangan belum diisi')}</small></div><button class="btn" onclick="go('schedule')">Lihat jadwal</button></div>`:`<div class="next-class"><div><small>Kelas berikutnya</small><strong>Belum ada kelas hari ini</strong><small>Tambahin jadwal kuliah biar Campusly bisa ngingetin.</small></div><button class="btn" onclick="go('schedule')">Atur jadwal</button></div>`;return `<div class="daily-wrap"><div class="daily-card"><p>HARI INI</p><h2>Yo, ${name} 👋</h2><p>${new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long'})}</p>${cls}<div class="smart-box"><strong>🎯 Saran Campusly</strong><span>${focusText}</span><button class="btn primary" style="margin-top:10px" onclick="go('${focus?'tasks':'ai'}')">${focus?'Kerjain sekarang':'Mulai belajar'}</button></div></div><div class="daily-card"><p>AGENDA HARI INI</p><div class="daily-list">${eventHtml}</div></div></div><div class="upgrade-section"><h2>Yang perlu lo beresin</h2><p>Deadline terdekat biar nggak kecolongan.</p><div class="daily-card"><div class="daily-list">${taskHtml}</div></div></div><div class="quick-actions"><button onclick="taskModal()">📝<b>Tambah tugas</b><small>Deadline baru</small></button><button onclick="eventModal()">📅<b>Tambah agenda</b><small>Jadwal atau acara</small></button><button onclick="go('ai')">✨<b>Tanya AI</b><small>Bantu tugas kuliah</small></button><button onclick="go('tools')">🧰<b>Tools</b><small>Kalkulator & lainnya</small></button></div>`}
function replaceHome(){if(location.hash&&location.hash!=='#home')return;const section=document.querySelector('#app main>section');if(!section||!section.querySelector('.hero'))return;const h=section.querySelector('.page-head');if(h){const p=h.querySelector('p');if(p)p.textContent='Yang penting hari ini, langsung kelihatan.'}section.querySelector('.hero')?.remove();section.querySelector('.quick-grid')?.remove();section.querySelector('.stats')?.remove();section.querySelector('.two')?.remove();section.insertAdjacentHTML('beforeend',dashboard())}
function addNotifyButton(){const h=document.querySelector('.app main>header');if(!h||h.querySelector('[data-notify]'))return;const b=document.createElement('button');b.type='button';b.className='icon-btn';b.dataset.notify='1';b.textContent='🔔';b.title='Notifikasi';b.onclick=async()=>{if(!('Notification'in window))return toast?.('Browser ini belum mendukung notifikasi.');if(Notification.permission!=='granted'){const p=await Notification.requestPermission();if(p!=='granted')return toast?.('Notifikasi belum diizinkan.')}toast?.('Notifikasi aktif 🔔')};h.insertBefore(b,h.querySelector('[data-theme-toggle]')||h.querySelector('.avatar')||null)}
css();const base=window.render;window.render=function(){const r=base?.();setTimeout(()=>{css();replaceHome();addNotifyButton()},0);return r};addEventListener('hashchange',()=>setTimeout(()=>{css();replaceHome();addNotifyButton()},50));setTimeout(()=>{replaceHome();addNotifyButton()},100);
})();
