(()=>{
const KEY='campusly_schedule_v1';
const DAYS=['Senin','Selasa','Rabu','Kamis','Jumat','Sabtu','Minggu'];
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const save=x=>localStorage.setItem(KEY,JSON.stringify(x));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const page=()=>`<div class="page-head"><div><div class="eyebrow">JADWAL KULIAH</div><h1>Jadwal lo.</h1><p>Semua kelas mingguan dalam satu tempat. Sekali isi, tinggal jalan.</p></div><button class="btn primary" id="add-class">＋ Tambah kelas</button></div><div class="schedule-wrap"><div class="schedule-toolbar"><button class="btn" id="today-class">Hari ini</button><span id="schedule-note"></span></div><div id="schedule-list"></div></div><div class="modal-host" id="schedule-modal"></div>`;
function render(){const root=document.querySelector('#app main>section')||document.querySelector('#app section');if(!root)return;root.innerHTML=page();root.querySelector('#add-class').onclick=()=>modal();root.querySelector('#today-class').onclick=()=>focusToday();draw();}
function draw(){const data=load().sort((a,b)=>a.day-b.day||a.start.localeCompare(b.start));const host=document.querySelector('#schedule-list');if(!host)return;host.innerHTML=DAYS.map((d,i)=>{const rows=data.filter(x=>x.day===i);return `<section class="schedule-day ${new Date().getDay()===((i+1)%7)?'today':''}"><header><b>${d}</b><small>${rows.length?rows.length+' kelas':'kosong'}</small></header>${rows.length?rows.map(x=>`<article class="class-card"><div class="class-time">${esc(x.start)}<span>${esc(x.end)}</span></div><div class="class-main"><strong>${esc(x.name)}</strong><small>${esc(x.room||'Ruangan belum diisi')} · ${esc(x.lecturer||'Dosen belum diisi')} · ${esc(x.sks||0)} SKS</small></div><button class="icon-btn del-class" data-id="${esc(x.id)}" aria-label="Hapus">×</button></article>`).join(''):'<div class="schedule-empty">Belum ada kelas.</div>'}</section>`}).join('');host.querySelectorAll('.del-class').forEach(b=>b.onclick=()=>{save(load().filter(x=>x.id!==b.dataset.id));draw();});}
function modal(){const host=document.querySelector('#schedule-modal');host.innerHTML=`<div class="overlay"><div class="modal"><div class="modal-head"><h2>Tambah jadwal</h2><button class="icon-btn close">×</button></div><form class="modal-body form" id="class-form"><label class="field"><span>Mata kuliah</span><input name="name" required placeholder="Contoh: Pemrograman Web"></label><label class="field"><span>Dosen</span><input name="lecturer" placeholder="Nama dosen"></label><label class="field"><span>Hari</span><select name="day">${DAYS.map((d,i)=>`<option value="${i}">${d}</option>`).join('')}</select></label><div class="form-row"><label class="field"><span>Mulai</span><input type="time" name="start" required></label><label class="field"><span>Selesai</span><input type="time" name="end" required></label></div><div class="form-row"><label class="field"><span>Ruangan</span><input name="room" placeholder="Gedung C / Lab 2"></label><label class="field"><span>SKS</span><input type="number" min="0" max="20" name="sks" value="3"></label></div><label class="field"><span>Link kelas online (opsional)</span><input type="url" name="link" placeholder="https://..."></label><div class="modal-actions"><button type="button" class="btn close">Batal</button><button class="btn primary">Simpan jadwal</button></div></form></div></div>`;host.querySelectorAll('.close').forEach(b=>b.onclick=()=>host.innerHTML='');host.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),x=Object.fromEntries(f);if(x.end<=x.start)return alert('Jam selesai harus setelah jam mulai.');x.id=crypto.randomUUID();x.day=Number(x.day);x.sks=Number(x.sks||0);const data=load();data.push(x);save(data);host.innerHTML='';draw();};}
function focusToday(){const day=(new Date().getDay()+6)%7;const el=document.querySelectorAll('.schedule-day')[day];el?.scrollIntoView({behavior:'smooth',block:'center'});}
window.CampuslySchedule={render,load};
})();
