const http=require('http');const {spawn}=require('child_process');
const PUBLIC_PORT=Number(process.env.PORT||8787),INTERNAL_PORT=PUBLIC_PORT+1,MAX_BODY=512*1024;
const MODELS=['gemini-3.5-flash-lite','gemini-3.8-flash','gemini-3.6-flash','gemini-3.5-flash'];
function json(res,code,body){const s=JSON.stringify(body);res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Content-Length':Buffer.byteLength(s)});res.end(s)}
function readJson(req){return new Promise((resolve,reject)=>{let b='',done=false;req.on('data',c=>{if(done)return;b+=c;if(Buffer.byteLength(b)>MAX_BODY){done=true;reject(new Error('Payload terlalu besar'));req.destroy()}});req.on('end',()=>{if(done)return;try{resolve(b?JSON.parse(b):{})}catch{reject(new Error('JSON tidak valid'))}});req.on('error',reject)})}
function payload(messages){const list=Array.isArray(messages)?messages:[],system=list.filter(m=>m?.role==='system').map(m=>String(m?.content??'')).filter(Boolean).join('\n\n'),contents=list.filter(m=>m?.role!=='system').map(m=>({role:m?.role==='assistant'?'model':'user',parts:[{text:String(m?.content??'')}]})).filter(m=>m.parts[0].text);const p={contents,generationConfig:{maxOutputTokens:2048}};if(system)p.systemInstruction={parts:[{text:system}]};return p}
async function models(key){const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models?key='+encodeURIComponent(key));const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||`HTTP ${r.status}`);return(d.models||[]).filter(m=>m.supportedGenerationMethods?.includes('generateContent')).map(m=>String(m.name||'').replace(/^models\//,''))}
async function ask(messages){const key=String(process.env.GEMINI_API_KEY||'').trim();if(!key)throw new Error('GEMINI_API_KEY kosong');const configured=String(process.env.GEMINI_MODEL||'').trim().replace(/^models\//,'');let available=[];try{available=await models(key)}catch(e){available=[]}let candidates=[configured,...MODELS].filter(Boolean);if(available.length)candidates=[...new Set(candidates.filter(m=>available.includes(m)))];else candidates=[...new Set(candidates)];let last='';for(const model of candidates){try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(messages))});const d=await r.json().catch(()=>({}));if(r.ok){const text=d?.candidates?.[0]?.content?.parts?.map(p=>p?.text||'').join('').trim()||'';if(text)return{text,model};last=model+': jawaban kosong'}else{last=model+': HTTP '+r.status+' — '+(d?.error?.message||'Gemini error')}}catch(e){last=model+': '+(e?.message||'koneksi gagal')}}throw new Error(last||'Semua model Gemini gagal')}
async function handle(req,res){const u=new URL(req.url,'http://localhost');if(req.method==='GET'&&u.pathname==='/api/ai/health'){const key=String(process.env.GEMINI_API_KEY||'').trim();if(!key)return json(res,503,{ok:false,configured:false,error:'GEMINI_API_KEY kosong'});try{const a=await models(key);return json(res,200,{ok:true,configured:true,model:process.env.GEMINI_MODEL||null,available:a.filter(x=>/^gemini-3\.(8|7|6|5)-flash(-lite)?$/.test(x)),recommended:MODELS})}catch(e){return json(res,502,{ok:false,configured:true,error:e.message})}}
if(req.method==='POST'&&u.pathname==='/api/ai'){try{const b=await readJson(req),messages=Array.isArray(b.messages)?b.messages:[];if(!messages.length)return json(res,400,{ok:false,error:'Pesan AI kosong'});const r=await ask(messages);return json(res,200,{ok:true,text:r.text,provider:'gemini',model:r.model})}catch(e){console.error('[AI]',e.stack||e);return json(res,502,{ok:false,error:e.message||'Gemini gagal'})}}
return false}
const child=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:String(INTERNAL_PORT)},stdio:['ignore','pipe','pipe']});child.stdout.on('data',d=>process.stdout.write(d));child.stderr.on('data',d=>process.stderr.write(d));
function proxy(req,res){const o={hostname:'127.0.0.1',port:INTERNAL_PORT,method:req.method,path:req.url,headers:{...req.headers,host:`127.0.0.1:${INTERNAL_PORT}`}};const p=http.request(o,r=>{res.writeHead(r.statusCode||200,r.headers);r.pipe(res)});p.on('error',e=>json(res,502,{error:'Campusly server belum siap',detail:e.message}));req.pipe(p)}
const server=http.createServer(async(req,res)=>{try{if(await handle(req,res))return;proxy(req,res)}catch(e){json(res,500,{error:e.message||'Internal error'})}});
server.listen(PUBLIC_PORT,'0.0.0.0',()=>console.log(`Campusly AI gateway listening on ${PUBLIC_PORT}; app on ${INTERNAL_PORT}`));
function stop(){server.close(()=>child.kill('SIGTERM'));setTimeout(()=>child.kill('SIGKILL'),5000).unref()}process.on('SIGTERM',stop);process.on('SIGINT',stop);