/* Campusly Tools v2 — defensive, mobile-friendly utility layer. */
(()=>{
  const state=()=>{try{return JSON.parse(localStorage.getItem('campusly_state_v3')||'{}')}catch{return {}}};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const toast=m=>window.toast?.(m);
  const safeAI=async(prompt,timeout=30000)=>{
    const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),timeout);
    try{
      const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:prompt}],context:JSON.stringify(state())}),signal:ctl.signal});
      const d=await r.json().catch(()=>({}));
      if(!r.ok||!d.text)throw new Error(d.error||`AI gagal (${r.status})`);
      return d.text;
    }catch(e){if(e.name==='AbortError')throw new Error('AI terlalu lama merespons. Coba lagi sebentar.');throw e}finally{clearTimeout(timer)}
  };
  const injectStyle=()=>{if(document.getElementById('tools-v2-style'))return;const s=document.createElement('style');s.id='tools-v2-style';s.textContent=`
    .tools-v2-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:20px}
    .tools-v2-card{border:1px solid var(--line);background:var(--surface);color:var(--text);border-radius:24px;padding:18px;text-align:left;min-height:132px;display:flex;flex-direction:column;justify-content:space-between;transition:.18s transform,.18s box-shadow}
    .tools-v2-card:hover{transform:translateY(-2px);box-shadow:var(--shadow)}.tools-v2-card b{font-size:17px}.tools-v2-card small{color:var(--muted);line-height:1.45}.tools-v2-icon{font-size:25px}.tools-v2-search{width:100%;box-sizing:border-box;margin-top:14px;padding:13px 15px;border:1px solid var(--line);border-radius:16px;background:var(--surface2);color:var(--text)}
    .calc-v2{display:grid;gap:10px}.calc-v2-display{width:100%;box-sizing:border-box;height:58px;border:1px solid var(--line);border-radius:15px;background:var(--surface2);color:var(--text);padding:0 14px;text-align:right;font-size:23px}.calc-v2-mode{display:flex;gap:7px;justify-content:flex-end}.calc-v2-mode button{border:1px solid var(--line);background:var(--surface);color:var(--text);border-radius:999px;padding:7px 11px}.calc-v2-keys{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.calc-v2-keys button{height:43px;border:1px solid var(--line);background:var(--surface);color:var(--text);border-radius:11px;font-weight:700}.calc-v2-keys button.op{background:var(--surface2)}
    .tool-result{margin-top:12px;padding:13px 14px;border:1px solid var(--line);background:var(--surface2);border-radius:15px;white-space:pre-wrap;overflow:auto}.tool-error{color:#d64545}.tool-row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.tool-row-3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px}.tool-actions{display:flex;gap:8px;flex-wrap:wrap}.tool-actions .btn{flex:1;min-width:120px}.timer-v2{text-align:center}.timer-v2 strong{display:block;font-size:54px;letter-spacing:-.04em;margin:4px 0 15px}.timer-presets{display:flex;justify-content:center;gap:7px;flex-wrap:wrap;margin-bottom:12px}.timer-presets button{border:1px solid var(--line);background:var(--surface);color:var(--text);border-radius:999px;padding:8px 12px}.grade-rows{display:grid;gap:8px}.grade-row{display:grid;grid-template-columns:1fr 90px 90px auto;gap:7px;align-items:center}.grade-row input{min-width:0}.tool-help{color:var(--muted);font-size:12px;line-height:1.5;margin-top:7px}.tool-valid{color:#2e9b68}.tool-invalid{color:#d64545}@media(max-width:600px){.tools-v2-grid{grid-template-columns:1fr}.tool-row,.tool-row-3{grid-template-columns:1fr}.grade-row{grid-template-columns:1fr 80px 80px auto}.calc-v2-keys button{height:40px}}
  `;document.head.appendChild(s)};

  const evaluate=(input,angle='DEG')=>{
    let e=String(input||'').replace(/×/g,'*').replace(/÷/g,'/').replace(/π/g,'PI').replace(/√/g,'sqrt').replace(/\s+/g,'');
    if(!e)throw new Error('Masukin ekspresi dulu.');
    if(!/^[0-9+\-*/().,^A-Za-z_]+$/.test(e))throw new Error('Ekspresi mengandung karakter yang nggak didukung.');
    e=e.replace(/\^/g,'**');
    const names=['sin','cos','tan','asin','acos','atan','sqrt','log','ln','abs','floor','ceil','round','PI','E'];
    const ids=e.match(/[A-Za-z_]+/g)||[];if(ids.some(x=>!names.includes(x)))throw new Error('Fungsi nggak dikenal.');
    const trig=n=>angle==='DEG'?`(${n}*Math.PI/180)`:n;
    e=e.replace(/sin\(/g,`Math.sin(${trig('`'+'X'+'`').replace(/X/g,'')`);`); // replaced safely below
    // Rebuild function calls explicitly to avoid accidental identifier access.
    e=String(input||'').replace(/×/g,'*').replace(/÷/g,'/').replace(/π/g,'Math.PI').replace(/√\s*\(/g,'Math.sqrt(').replace(/\^/g,'**');
    const fnMap={sin:'Math.sin',cos:'Math.cos',tan:'Math.tan',asin:'Math.asin',acos:'Math.acos',atan:'Math.atan',sqrt:'Math.sqrt',log:'Math.log10',ln:'Math.log',abs:'Math.abs',floor:'Math.floor',ceil:'Math.ceil',round:'Math.round'};
    Object.entries(fnMap).forEach(([k,v])=>{e=e.replace(new RegExp(`\\b${k}\\s*\\(`,'g'),`${v}(`)});
    if(angle==='DEG')for(const k of ['sin','cos','tan'])e=e.replace(new RegExp(`Math\\.${k}\\(([^()]*)\\)`,'g'),`Math.${k}((($1)*Math.PI/180))`);
    if(!/^[0-9+\-*/().,\s*MathPI_]+$/.test(e))throw new Error('Ekspresi nggak valid.');
    const value=Function(`"use strict";return (${e})`)();
    if(typeof value!=='number'||!Number.isFinite(value))throw new Error('Hasilnya nggak terdefinisi.');
    return Number(value.toFixed(12));
  };

  window.scienceCalc=()=>{
    injectStyle();let angle='DEG',expr='';
    const keys=['7','8','9','÷','(',')','4','5','6','×','sin','cos','tan','1','2','3','-','√','0','.','+','^','π','C','='];
    const html=()=>`<div class="calc-v2"><input id="calc-v2-display" class="calc-v2-display" readonly value=""><div class="calc-v2-mode"><button type="button" id="calc-v2-deg">DEG</button><button type="button" id="calc-v2-rad">RAD</button></div><div class="calc-v2-keys">${keys.map(k=>`<button type="button" data-k="${k}" class="${/[÷×+\-^]/.test(k)?'op':''}">${k}</button>`).join('')}</div><div id="calc-v2-help" class="tool-help">Mode DEG aktif. Contoh: sin(30) → 0.5</div></div>`;
    modal('Kalkulator sains',html(),()=>{},'Tutup');
    const d=document.getElementById('calc-v2-display'),help=document.getElementById('calc-v2-help');
    const paint=()=>{if(d)d.value=expr};
    document.querySelectorAll('#modal [data-k]').forEach(b=>b.onclick=()=>{const k=b.dataset.k;if(k==='C'){expr='';paint();return}if(k==='='){try{expr=String(evaluate(expr,angle));help.textContent=`Hasil: ${expr}`;help.className='tool-help tool-valid'}catch(e){help.textContent=e.message;help.className='tool-help tool-invalid'}return}if(k==='√')expr+='√(';else if(['sin','cos','tan'].includes(k))expr+=k+'(';else expr+=k;paint()});
    document.getElementById('calc-v2-deg').onclick=()=>{angle='DEG';help.textContent='Mode DEG aktif. Contoh: sin(30) → 0.5'};
    document.getElementById('calc-v2-rad').onclick=()=>{angle='RAD';help.textContent='Mode RAD aktif. Contoh: sin(1.5708) → 1'};
  };

  window.translator=()=>{injectStyle();modal('Translator',`<div class="form"><div class="tool-row"><label class="field"><span>Dari</span><input id="tr-v2-from" value="Auto" placeholder="Auto / Indonesia / English"></label><label class="field"><span>Ke</span><input id="tr-v2-to" value="English" placeholder="Bahasa tujuan"></label></div><label class="field"><span>Teks</span><textarea id="tr-v2-text" rows="7" placeholder="Tempel teks apa aja di sini..."></textarea></label><div id="tr-v2-result" class="tool-result" hidden></div></div>`,async()=>{const text=document.getElementById('tr-v2-text')?.value.trim(),from=document.getElementById('tr-v2-from')?.value.trim()||'Auto',to=document.getElementById('tr-v2-to')?.value.trim()||'English',out=document.getElementById('tr-v2-result');if(!text){toast('Teksnya belum diisi.');return}if(out){out.hidden=false;out.textContent='Lagi nerjemahin…'}try{const r=await safeAI(`Terjemahkan dari ${from} ke ${to}. Pertahankan arti, nama, angka, struktur paragraf, dan format penting. Jangan jelaskan proses. Jika teks sudah dalam bahasa tujuan, tetap berikan versi yang natural.\n\n${text}`);if(out)out.textContent=r}catch(e){if(out){out.textContent='⚠️ '+e.message;out.classList.add('tool-error')}}},'Translate')};

  window.studyTimer=()=>{injectStyle();let total=25*60,remaining=total,running=false;modal('Study timer',`<div class="timer-v2"><strong id="timer-v2-num">25:00</strong><div class="timer-presets"><button type="button" data-min="25">25 min</button><button type="button" data-min="50">50 min</button><button type="button" data-min="5">5 min</button></div><div class="tool-actions"><button class="btn primary" type="button" id="timer-v2-start">Mulai</button><button class="btn" type="button" id="timer-v2-pause">Pause</button><button class="btn" type="button" id="timer-v2-reset">Reset</button></div></div>`,()=>{clearInterval(window.__campuslyTimer);closeModal()},'Tutup');
    const num=document.getElementById('timer-v2-num');const draw=()=>{if(num)num.textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`};
    const start=()=>{if(running)return;running=true;clearInterval(window.__campuslyTimer);window.__campuslyTimer=setInterval(()=>{remaining--;draw();if(remaining<=0){remaining=0;running=false;clearInterval(window.__campuslyTimer);toast('Sesi fokus selesai. Istirahat bentar 😌');if('Notification' in window&&Notification.permission==='granted')new Notification('Campusly · selesai fokus',{body:'Waktunya istirahat sebentar 😌'})}},1000)};
    document.getElementById('timer-v2-start').onclick=start;document.getElementById('timer-v2-pause').onclick=()=>{running=false;clearInterval(window.__campuslyTimer)};document.getElementById('timer-v2-reset').onclick=()=>{running=false;clearInterval(window.__campuslyTimer);remaining=total;draw()};document.querySelectorAll('[data-min]').forEach(b=>b.onclick=()=>{running=false;clearInterval(window.__campuslyTimer);total=remaining=Number(b.dataset.min)*60;draw()});
  };

  const unitSets={
    length:{units:{mm:0.001,cm:0.01,m:1,km:1000,in:0.0254,ft:0.3048,yd:0.9144,mi:1609.344},label:'Panjang'},
    mass:{units:{mg:0.000001,g:0.001,kg:1,ton:1000,oz:0.028349523125,lb:0.45359237},label:'Massa'},
    area:{units:{'cm²':0.0001,'m²':1,'km²':1e6,'ft²':0.09290304,'ha':10000,'acre':4046.8564224},label:'Luas'},
    volume:{units:{mL:0.001,L:1,'m³':1000,'cm³':0.001,gal:3.785411784,qt:0.946352946},label:'Volume'},
    time:{units:{ms:0.001,s:1,min:60,h:3600,day:86400,week:604800},label:'Waktu'},
    data:{units:{B:1,KB:1024,MB:1024**2,GB:1024**3,TB:1024**4},label:'Data'}
  };
  const tempConvert=(v,f,t)=>{let c=f==='C'?v:f==='F'?(v-32)*5/9:(v-273.15);return t==='C'?c:t==='F'?c*9/5+32:c+273.15};
  window.unitConvert=()=>{injectStyle();let html=`<div class="form"><label class="field"><span>Kategori</span><select id="uc-v2-cat">${Object.entries(unitSets).map(([k,v])=>`<option value="${k}">${v.label}</option>`).join('')}<option value="temp">Suhu</option></select></label><div class="tool-row"><label class="field"><span>Nilai</span><input id="uc-v2-value" type="number" inputmode="decimal" value="1"></label><label class="field"><span>Dari</span><select id="uc-v2-from"></select></label></div><label class="field"><span>Ke</span><select id="uc-v2-to"></select></label><div id="uc-v2-result" class="tool-result">Pilih satuan lalu tekan Konversi.</div></div>`;modal('Konversi satuan',html,()=>{const cat=document.getElementById('uc-v2-cat').value,v=Number(document.getElementById('uc-v2-value').value),f=document.getElementById('uc-v2-from').value,t=document.getElementById('uc-v2-to').value,out=document.getElementById('uc-v2-result');if(!Number.isFinite(v)){out.textContent='Masukin angka yang valid.';return}let r;if(cat==='temp')r=tempConvert(v,f,t);else r=v*unitSets[cat].units[f]/unitSets[cat].units[t];out.textContent=`Hasil: ${Number(r.toPrecision(12))} ${t}`},'Konversi');
    const cat=document.getElementById('uc-v2-cat'),from=document.getElementById('uc-v2-from'),to=document.getElementById('uc-v2-to');const fill=()=>{const c=cat.value,units=c==='temp'?{C:1,F:1,K:1}:unitSets[c].units;const opts=Object.keys(units).map(x=>`<option>${x}</option>`).join('');from.innerHTML=opts;to.innerHTML=opts;to.selectedIndex=Math.min(1,to.options.length-1)};cat.onchange=fill;fill();
  };

  window.gradeCalc=()=>{injectStyle();let rows=[{n:'Tugas',g:80,w:40},{n:'Ujian',g:80,w:60}];const html=()=>`<div class="grade-rows" id="grade-v2-rows">${rows.map((r,i)=>`<div class="grade-row"><input data-i="${i}" data-k="n" value="${esc(r.n)}" placeholder="Komponen"><input data-i="${i}" data-k="g" type="number" min="0" max="100" value="${r.g}"><input data-i="${i}" data-k="w" type="number" min="0" max="100" value="${r.w}"><button type="button" data-del="${i}">×</button></div>`).join('')}</div><p class="tool-help">Kolom: komponen · nilai · bobot. Total bobot harus 100%.</p><div id="grade-v2-result" class="tool-result">Belum dihitung.</div><div class="tool-actions"><button type="button" class="btn" id="grade-v2-add">＋ Komponen</button></div>`;modal('Kalkulator nilai',html,()=>{document.querySelectorAll('#grade-v2-rows input').forEach(i=>rows[Number(i.dataset.i)][i.dataset.k]=i.dataset.k==='n'?i.value:Number(i.value));const sum=rows.reduce((a,r)=>a+r.w,0),out=document.getElementById('grade-v2-result');if(Math.abs(sum-100)>0.001){out.textContent=`Bobot sekarang ${sum}%. Bikin totalnya tepat 100%.`;out.classList.add('tool-error');return}const score=rows.reduce((a,r)=>a+r.g*r.w,0)/100;out.textContent=`Nilai akhir: ${score.toFixed(2)}`},'Hitung');
    document.getElementById('grade-v2-add').onclick=()=>{rows.push({n:`Komponen ${rows.length+1}`,g:80,w:0});document.getElementById('modal-body').innerHTML=html();document.getElementById('grade-v2-add').onclick=()=>{};toast('Komponen ditambah. Isi bobotnya lalu hitung.');};
  };

  window.gpaCalc=()=>{injectStyle();modal('Kalkulator GPA',`<div class="form"><label class="field"><span>IP/GPA sekarang</span><input id="gpa-v2-now" type="number" min="0" max="4" step="0.01" value="3.2"></label><label class="field"><span>Total SKS yang sudah ditempuh</span><input id="gpa-v2-credits" type="number" min="0" value="60"></label><label class="field"><span>GPA target</span><input id="gpa-v2-target" type="number" min="0" max="4" step="0.01" value="3.5"></label><label class="field"><span>SKS semester berikutnya</span><input id="gpa-v2-next" type="number" min="1" value="20"></label><div id="gpa-v2-result" class="tool-result">Masukin data lalu hitung.</div></div>`,()=>{const now=+document.getElementById('gpa-v2-now').value,cr=+document.getElementById('gpa-v2-credits').value,target=+document.getElementById('gpa-v2-target').value,next=+document.getElementById('gpa-v2-next').value,out=document.getElementById('gpa-v2-result');if(now<0||now>4||target<0||target>4||cr<0||next<=0){out.textContent='Cek lagi angkanya.';return}const required=(target*(cr+next)-now*cr)/next;out.textContent=required>4?`Butuh GPA ${required.toFixed(2)} — target itu belum realistis dalam 1 semester.`:required<=0?`Secara hitungan, target ${target.toFixed(2)} sudah aman.`:`Butuh sekitar GPA ${required.toFixed(2)} semester depan buat ngejar ${target.toFixed(2)}.`},'Hitung')};

  window.tools=function(){injectStyle();return `<div class="tools-page"><span class="eyebrow">UTILITY</span><h1>Tools</h1><p>Yang kecil-kecil tapi kepake terus buat kuliah.</p><input id="tools-v2-search" class="tools-v2-search" placeholder="Cari tool…"><div class="tools-v2-grid" id="tools-v2-grid"><button class="tools-v2-card" data-search="kalkulator sains scientific calculator" onclick="scienceCalc()"><span class="tools-v2-icon">🧮</span><b>Kalkulator sains</b><small>sin, cos, tan, log, akar, pangkat + mode DEG/RAD.</small></button><button class="tools-v2-card" data-search="translator terjemahan bahasa translate" onclick="translator()"><span class="tools-v2-icon">🌐</span><b>Translator</b><small>Terjemahin teks ke bahasa yang lo mau lewat AI.</small></button><button class="tools-v2-card" data-search="timer pomodoro fokus" onclick="studyTimer()"><span class="tools-v2-icon">⏱️</span><b>Study timer</b><small>25/50/5 menit, pause, reset, dan pengingat selesai.</small></button><button class="tools-v2-card" data-search="konversi satuan unit length mass temperature" onclick="unitConvert()"><span class="tools-v2-icon">↔️</span><b>Konversi satuan</b><small>Panjang, massa, luas, volume, waktu, data, suhu.</small></button><button class="tools-v2-card" data-search="nilai grade kalkulator nilai" onclick="gradeCalc()"><span class="tools-v2-icon">📊</span><b>Kalkulator nilai</b><small>Tambah komponen sendiri dan pastikan bobot 100%.</small></button><button class="tools-v2-card" data-search="gpa ip ipk indeks prestasi" onclick="gpaCalc()"><span class="tools-v2-icon">🎓</span><b>Kalkulator GPA</b><small>Hitung kebutuhan GPA semester depan buat ngejar target.</small></button><button class="tools-v2-card" data-search="kalender jadwal agenda" onclick="go('calendar')"><span class="tools-v2-icon">📅</span><b>Jadwal</b><small>Lihat deadline dan agenda kuliah tanpa pindah jauh.</small></button><button class="tools-v2-card" data-search="ai scan makalah ppt gambar" onclick="go('ai')"><span class="tools-v2-icon">✨</span><b>AI Campusly</b><small>Chat, scan soal, makalah, PPT, dan generator gambar.</small></button></div></div>`};

  const originalRender=window.render;
  window.render=function(){injectStyle();return originalRender?.()};
  addEventListener('DOMContentLoaded',injectStyle,{once:true});
})();
