/* Campusly canonical UI utilities: icons + mobile back navigation. */
(() => {
  'use strict';
  const icons={home:'M3 10.5 12 3l9 7.5V21a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z',tasks:'M5 12.5 9.2 17 19 6.5',calendar:'M5 4h14a2 2 0 0 1 2 2v13H3V6a2 2 0 0 1 2-2zm3-2v4m8-4v4M3 9h18M7 13h3M14 13h3M7 17h3',ai:'M12 3l1.5 5.5L19 10l-5.5 1.5L12 17l-1.5-5.5L5 10l5.5-1.5zM19 16l.6 2.4L22 19l-2.4.6L19 22l-.6-2.4L16 19l2.4-.6z',menu:'M4 7h16M4 12h16M4 17h16',search:'M11 17.5a6.5 6.5 0 1 0 0-13 6.5 6.5 0 0 0 0 13zM16 16l4.5 4.5',back:'M19 12H5M12 19l-7-7 7-7'};
  const svg=(path,cls='')=>`<svg class="campusly-svg ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${path}"/></svg>`;
  const internal=new Set(['home','tasks','calendar','ai','menu','notes','schedule','semester','gpa','finance','focus','analytics','thesis','documents','tools','notifications','reminders','settings']);
  let current=location.hash.slice(1)||'home';let previous=current;
  function routeFromButton(button){const m=(button.getAttribute('onclick')||'').match(/go\(['"]([^'"]+)['"]\)/);return m?.[1]||'';}
  function applyIcons(){document.querySelectorAll('.side-nav button').forEach(b=>{const r=routeFromButton(b),slot=b.querySelector('.ico');if(slot&&icons[r])slot.innerHTML=svg(icons[r]);});document.querySelectorAll('.mobile-nav button').forEach(b=>{const r=routeFromButton(b),slot=b.querySelector('.micon');if(slot&&icons[r])slot.innerHTML=svg(icons[r]);});const search=document.querySelector('.search'),input=search?.querySelector('input');if(search&&input&&!search.querySelector('.campusly-search-icon')){const slot=document.createElement('span');slot.className='campusly-search-icon';slot.innerHTML=svg(icons.search);search.insertBefore(slot,input);}}
  function addBack(){const route=location.hash.slice(1)||'home';document.querySelector('.campusly-back')?.remove();if(route==='home')return;const content=document.querySelector('.content'),first=content?.firstElementChild;if(!content||!first)return;const button=document.createElement('button');button.className='campusly-back';button.type='button';button.innerHTML=`${svg(icons.back)}<span>Kembali</span>`;button.onclick=()=>{if(internal.has(previous)&&previous!==route&&typeof window.go==='function'){window.go(previous);return;}if(typeof window.go==='function')window.go('home');else location.hash='home';};content.insertBefore(button,first);}
  function apply(){applyIcons();addBack();}
  window.addEventListener('hashchange',()=>{const next=location.hash.slice(1)||'home';if(internal.has(next)){previous=current;current=next;}setTimeout(apply,0);});
  const app=document.getElementById('app');if(app)new MutationObserver(()=>{applyIcons();if((location.hash.slice(1)||'home')!=='home'&&!document.querySelector('.campusly-back'))addBack();}).observe(app,{childList:true,subtree:true});
  document.addEventListener('DOMContentLoaded',apply,{once:true});setTimeout(apply,0);
})();
