const createAIClient = ({ fail, safeError, text, AI_TIMEOUT, MODEL_PREF }) => {
const { chatInstruction, modeInstruction } = require('./prompts.cjs').createPrompts();
let modelCache={at:0,models:[],selected:null};
const mockEnabled=()=>process.env.AI_MOCK==='1';
function mockResult({contents,mode,config,tools}){const schema=config?.responseSchema?.properties||{};const prompt=contents?.at(-1)?.parts?.map(part=>part.text||'').join(' ')||'';if(schema.chapters)return{text:JSON.stringify({title:'Contoh Makalah',abstract:'Ringkasan contoh untuk pengujian integrasi lokal.',keywords:['contoh','pengujian'],chapters:[{number:1,title:'Pembahasan',targetWords:260,sections:[{title:'Uraian',targetWords:260}]}]}),model:'mock-gemini-flash'};if(schema.slides)return{text:JSON.stringify({title:'Contoh Presentasi',slides:[{layout:'title',title:'Contoh Presentasi',bullets:[],iconKeywords:[],imageQuery:'',notes:'Contoh catatan pembicara.'},{layout:'content-bullets',title:'Ringkasan',bullets:['Poin contoh'],iconKeywords:[],imageQuery:'',notes:'Contoh.'}]}),model:'mock-gemini-flash'};if(tools?.length)return{text:'Referensi tidak diminta dalam mode pengujian.',model:'mock-gemini-flash',grounding:null};if(config?.responseMimeType==='application/json')return{text:'{}',model:'mock-gemini-flash'};if(mode==='paper'&&/Tulis BAB/.test(prompt)){const paragraph='Pembahasan ini disediakan oleh AI_MOCK untuk menguji jalur pembuatan dokumen secara lokal tanpa menghubungi penyedia eksternal. Isi contoh ini tidak dimaksudkan sebagai sumber akademik. ';return{text:paragraph.repeat(35),model:'mock-gemini-flash'}}return{text:mode==='chat'?'Ini jawaban simulasi lokal dari Campusly AI.':mode==='translate'?prompt.split(/\\n\\n/).at(-1).slice(0,20000):prompt.slice(0,1000)||'OK',model:'mock-gemini-flash'}}
async function fetchJson(url,options={},timeout=AI_TIMEOUT){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{...options,signal:c.signal});const raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch{}return{r,d,raw}}catch(e){if(e.name==='AbortError')throw fail('AI request timeout.',504,{code:'AI_TIMEOUT'});throw fail('AI network error.',502,{code:'AI_NETWORK'})}finally{clearTimeout(t)}}
async function listModels(force=false){const key=String(process.env.GEMINI_API_KEY||'').trim();if(mockEnabled())return{at:Date.now(),models:[{name:'mock-gemini-flash',displayName:'Campusly Test Mock',methods:['generateContent']}],selected:'mock-gemini-flash'};if(!key){modelCache={at:Date.now(),models:[],selected:null};return modelCache}if(!force&&Date.now()-modelCache.at<5*60*1000)return modelCache;const {r,d}=await fetchJson('https://generativelanguage.googleapis.com/v1beta/models?pageSize=1000',{headers:{'x-goog-api-key':key}},10000);if(!r.ok)throw fail(d?.error?.message||'Gagal mengambil daftar model Gemini.',r.status===429?429:502,{code:'MODELS_LIST_FAILED',geminiStatus:r.status});const models=(d.models||[]).filter(m=>Array.isArray(m.supportedGenerationMethods)&&m.supportedGenerationMethods.includes('generateContent')).map(m=>({name:String(m.name||'').replace(/^models\//,''),displayName:m.displayName||'',methods:m.supportedGenerationMethods||[],inputTokenLimit:m.inputTokenLimit||null,outputTokenLimit:m.outputTokenLimit||null})).filter(m=>m.name);
const score=m=>{const n=m.name.toLowerCase();let s=0;if(MODEL_PREF&&n===MODEL_PREF.replace(/^models\//,''))s+=100000;if(n.includes('flash'))s+=1000;if(n.includes('lite'))s+=300;if(n.includes('pro'))s-=100;if(n.includes('preview'))s-=20;if(n.includes('image'))s-=300;return s};models.sort((a,b)=>score(b)-score(a));modelCache={at:Date.now(),models,selected:models[0]?.name||null};return modelCache}
async function modelChain(){const x=await listModels();if(!x.selected)throw fail('Tidak ada model Gemini yang mendukung generateContent.',503,{code:'MODEL_UNAVAILABLE'});return x.models.slice(0,3).map(m=>m.name)}
function normalizeHistory(messages){if(!Array.isArray(messages))return[];return messages.slice(-12).map(m=>{if(!['assistant','model','user'].includes(m?.role))return null;const role=m.role==='assistant'||m.role==='model'?'model':'user';const c=text(m?.content||m?.text,12000);return c&&!/^⚠️/.test(c)?{role,parts:[{text:c}]}:null}).filter(Boolean)}
function compactContext(c){if(!c)return'';let x=c;try{const d=typeof c==='string'?JSON.parse(c):c;x={profile:d.profile||{},tasks:Array.isArray(d.tasks)?d.tasks.slice(0,10):[],schedule:Array.isArray(d.schedule)?d.schedule.slice(0,10):[],events:Array.isArray(d.events)?d.events.slice(0,10):[],grades:Array.isArray(d.grades)?d.grades.slice(0,10):[]};x=JSON.stringify(x)}catch{x=text(c,10000)}return text(x,12000)}
async function gemini({contents,system,mode='chat',tools,config={},extraParts=[]}){const key=String(process.env.GEMINI_API_KEY||'').trim();if(mockEnabled())return mockResult({contents,mode,config,tools});if(!key)throw fail('GEMINI_API_KEY belum diatur.',503,{code:'MISSING_API_KEY'});let last=null;for(const model of await modelChain()){for(let attempt=0;attempt<3;attempt++){try{const payload={systemInstruction:{parts:[{text:system||modeInstruction(mode)}]},contents, generationConfig:{temperature:mode==='chat'?0.8:0.35,...config}};if(tools)payload.tools=tools;if(extraParts.length)payload.contents[payload.contents.length-1].parts.push(...extraParts);const {r,d}=await fetchJson(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify(payload)},AI_TIMEOUT);if(!r.ok){const e=fail(d?.error?.message||`Gemini HTTP ${r.status}`,r.status===429?429:502,{code:'GEMINI_HTTP',geminiStatus:r.status,model});last=e;if([429,500,502,503].includes(r.status)&&attempt<2){await new Promise(r=>setTimeout(r,350*Math.pow(2,attempt)+Math.random()*250));continue}if([400,401,403,404].includes(r.status))break;continue}const candidate=d?.candidates?.[0],out=candidate?.content?.parts?.map(p=>p?.text||'').join('')||'';if(!out)throw fail('Gemini mengembalikan jawaban kosong.',502,{code:'EMPTY_AI',model});return{text:out,model,grounding:candidate?.groundingMetadata||null,raw:d}}catch(e){last=e;if(e.code==='MISSING_API_KEY'||e.code==='MODEL_UNAVAILABLE')throw e;if(e.code==='AI_TIMEOUT'&&attempt<2){await new Promise(r=>setTimeout(r,350*Math.pow(2,attempt)+Math.random()*250));continue}if(e.geminiStatus&&[400,401,403,404].includes(e.geminiStatus))break}}}throw fail(safeError(last),last?.status||502,{code:'ALL_MODELS_FAILED',cause:last?.code})}
function jsonInstruction(schema){return {responseMimeType:'application/json',responseSchema:schema,maxOutputTokens:12000}}
return {fetchJson,listModels,modelChain,chatInstruction,modeInstruction,normalizeHistory,compactContext,gemini,jsonInstruction};
};
module.exports={createAIClient};
