function createRoutes(deps) {
  const { security, json, binary, staticFile, limited, body, fail, safeError, text, jobs, canvaConfig, cookieSession, canvaLogin, canvaCallback, canvaImport, resumeJob, createJob, listModels, chatInstruction, gemini, modeInstruction, chat, jsonInstruction, makeDoc, makePdf, makePpt } = deps;const languageNames = { auto: 'auto-detect', id: 'Indonesian', en: 'English', ms: 'Malay', ar: 'Arabic', zh: 'Chinese', ja: 'Japanese', ko: 'Korean', fr: 'French', de: 'German', es: 'Spanish' };
async function translateText(data) {
  const raw = String(data?.text ?? data?.message ?? data?.prompt ?? '');
  if (!raw.trim()) throw fail('Teks yang mau diterjemahkan masih kosong.', 400, { code: 'EMPTY_TRANSLATION' });
  if (raw.length > 20000) throw fail('Teks maksimal 20.000 karakter.', 413, { code: 'TRANSLATION_TOO_LONG' });
  const from = String(data.from || 'auto').toLowerCase();
  const to = String(data.to || 'id').toLowerCase();
  if (!languageNames[from] || from === 'auto' && !languageNames[to] || !languageNames[to] || to === 'auto') throw fail('Bahasa yang dipilih belum didukung.', 400, { code: 'UNSUPPORTED_LANGUAGE' });
  return gemini({ contents: [{ role: 'user', parts: [{ text: `Terjemahkan teks berikut dari ${languageNames[from]} ke ${languageNames[to]}. Pertahankan makna, format, nama, dan angka. Output hanya hasil terjemahan.\n\n${text(raw, 20000)}` }] }], system: modeInstruction('translate'), mode: 'translate', config: { maxOutputTokens: 3000 } });
}async function route(req,res){security(res);const p=new URL(req.url,`http://${req.headers.host||'localhost'}`).pathname;if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type'});return res.end()}
if(req.method==='GET'&&p==='/api/health')return json(res,200,{ok:true,version:'campusly-ai-v2',keyConfigured:Boolean(process.env.GEMINI_API_KEY),model:(await listModels()).selected});
if(req.method==='GET'&&p==='/api/ready')return json(res,200,{ready:true,version:'campusly-ai-v2',features:['chat','translate','paper','ppt','vision','jobs','canva'],exports:['docx','pdf','pptx']});
if(req.method==='GET'&&p==='/api/ai/models'){try{return json(res,200,{ok:true,keyConfigured:Boolean(process.env.GEMINI_API_KEY),...(await listModels())})}catch(e){return json(res,e.status||502,{ok:false,error:safeError(e),code:e.code||'MODELS_FAILED'})}}
if(req.method==='GET'&&p==='/api/ai/check'){if(!process.env.GEMINI_API_KEY)return json(res,503,{ok:false,error:safeError(fail('',503,{code:'MISSING_API_KEY'})),code:'MISSING_API_KEY'});try{const r=await gemini({contents:[{role:'user',parts:[{text:'Balas hanya: OK'}]}],system:chatInstruction(),mode:'chat',config:{maxOutputTokens:20}});return json(res,200,{ok:true,model:r.model,text:r.text})}catch(e){return json(res,e.status||502,{ok:false,error:safeError(e),code:e.code||'AI_CHECK_FAILED'})}}
if(req.method==='GET'&&p==='/api/canva/status'){const s=cookieSession(req,res);return json(res,200,{ok:true,configured:Boolean(canvaConfig()),connected:Boolean(s.canva)})}
if(req.method==='GET'&&p==='/api/canva/login')return canvaLogin(req,res);
if(req.method==='GET'&&p==='/api/canva/callback')return canvaCallback(req,res);
if(req.method==='POST'&&p==='/api/canva/import'){if(!limited(req,'export',5))return json(res,429,{ok:false,error:'Terlalu banyak import Canva. Coba lagi nanti.'});try{return await canvaImport(req,res)}catch(e){return json(res,e.status||500,{ok:false,error:safeError(e)})}}
if(req.method==='POST'&&/^\/api\/jobs\/[^/]+\/resume$/.test(p)){try{const id=p.split('/')[3];await resumeJob(id);return json(res,202,{ok:true,jobId:id,status:'queued'})}catch(e){return json(res,e.status||500,{ok:false,error:safeError(e),code:e.code})}}
if(req.method==='GET'&&p.startsWith('/api/jobs/')){const id=p.split('/').pop(),j=jobs.get(id);if(!j)return json(res,404,{ok:false,error:'Job tidak ditemukan atau sudah kedaluwarsa.'});return json(res,200,{ok:true,id:j.id,status:j.status,progress:j.progress,stage:j.stage,message:j.message,result:j.status==='done'?j.result:null,error:j.error})}
if(req.method==='POST'&&p==='/api/jobs'){if(!limited(req,'generate',8))return json(res,429,{ok:false,error:'Antrean generate sedang padat. Coba lagi sebentar.'});const d=await body(req,2*1024*1024);const kind=d.kind==='ppt'?'ppt':'paper';try{return json(res,202,{ok:true,jobId:await createJob(kind,d)})}catch(e){return json(res,e.status||500,{ok:false,error:safeError(e),code:e.code})}}
const aiAliases=['/api/ai','/api/chat','/api/ai/chat','/api/translate','/api/ai/translate','/api/generate-paper','/api/generate-makalah','/api/paper','/api/generate/paper','/api/generate-ppt','/api/generate-powerpoint','/api/ppt','/api/generate/ppt'];
if(req.method==='POST'&&aiAliases.includes(p)){const bucket=(p.includes('paper')||p.includes('ppt')||p.includes('generate'))?'generate':'chat';if(!limited(req,bucket,bucket==='chat'?30:8))return json(res,429,{ok:false,error:'Terlalu banyak request. Coba lagi sebentar.'});try{const d=await body(req);let mode=String(d.mode||'chat');if(p.includes('translate'))mode='translate';if(p.includes('paper'))mode='paper';if(p.includes('ppt'))mode='ppt';if(mode==='paper'||mode==='ppt'){return json(res,202,{ok:true,jobId:await createJob(mode==='paper'?'paper':'ppt',d)})}const r=mode==='translate'?await translateText(d):await chat(d);return json(res,200,{ok:true,text:r.text,result:r.text,response:r.text,answer:r.text,message:r.text,content:r.text,model:r.model})}catch(e){return json(res,e.status||500,{ok:false,error:safeError(e),code:e.code||'AI_FAILED'})}}
if(req.method==='POST'&&p==='/api/ai/vision'){if(!limited(req,'vision',10))return json(res,429,{ok:false,error:'Terlalu banyak scan. Coba lagi sebentar.'});try{const d=await body(req,7*1024*1024),m=String(d.image||'').match(/^data:(image\/(?:jpeg|png|webp));base64,(.+)$/s);if(!m)throw fail('Gambar tidak valid. Gunakan JPG, PNG, atau WebP.',400);const bytes=Buffer.byteLength(m[2],'base64');if(bytes>5*1024*1024)throw fail('Ukuran gambar maksimal 5 MB.',413);const r=await gemini({contents:[{role:'user',parts:[{text:text(d.question||'Baca soal pada gambar, jelaskan langkah pengerjaan, lalu jawab dengan bahasa Indonesia yang jelas.')},{inlineData:{mimeType:m[1],data:m[2]}}]}],system:'Kamu membantu mahasiswa membaca soal dari gambar. Jelaskan langkah secara akurat dan jangan mengarang bagian gambar yang tidak terbaca.',mode:'chat',config:{temperature:.3,maxOutputTokens:3000}});return json(res,200,{ok:true,text:r.text,model:r.model})}catch(e){return json(res,e.status||500,{ok:false,error:safeError(e),code:e.code||'VISION_FAILED'})}}
if(req.method==='POST'&&['/api/export/docx','/api/export/word'].includes(p)){if(!limited(req,'export',10))return json(res,429,{ok:false,error:'Terlalu banyak export. Coba lagi sebentar.'});try{const d=await body(req,5*1024*1024);const model=d.document||{title:d.title||'Campusly',chapters:[{number:1,title:'Dokumen',sections:[{title:'',paragraphs:[text(d.content||d.text)]}]}],identity:{}};return binary(res,200,await makeDoc(model),'application/vnd.openxmlformats-officedocument.wordprocessingml.document','campusly-makalah.docx')}catch(e){return json(res,e.status||500,{ok:false,error:safeError(e)})}}
if(req.method==='POST'&&p==='/api/export/pdf'){if(!limited(req,'export',10))return json(res,429,{ok:false,error:'Terlalu banyak export. Coba lagi sebentar.'});try{const d=await body(req,5*1024*1024);const model=d.document||{title:d.title||'Campusly',chapters:[{number:1,title:'Dokumen',sections:[{title:'',paragraphs:[text(d.content||d.text)]}]}],identity:{}};return binary(res,200,await makePdf(model),'application/pdf','campusly-makalah.pdf')}catch(e){return json(res,e.status||500,{ok:false,error:safeError(e)})}}
if(req.method==='POST'&&['/api/export/ppt','/api/export/pptx','/api/export/powerpoint'].includes(p)){if(!limited(req,'export',10))return json(res,429,{ok:false,error:'Terlalu banyak export. Coba lagi sebentar.'});try{const d=await body(req,10*1024*1024);const model=d.document||{title:d.title||'Campusly',theme:'auto',slides:[{layout:'title',title:d.title||'Campusly',bullets:[],imageQuery:'',notes:''},{layout:'content-bullets',title:'Materi',bullets:text(d.content||d.text).split(/\n/).filter(Boolean).slice(0,5),imageQuery:'',notes:''}]};return binary(res,200,await makePpt(model),'application/vnd.openxmlformats-officedocument.presentationml.presentation','campusly-presentasi.pptx')}catch(e){return json(res,e.status||500,{ok:false,error:safeError(e)})}}
if(req.method==='GET'&&staticFile(res,p))return;return json(res,404,{ok:false,error:'Endpoint tidak ditemukan.'})}  return route;
}
module.exports = { createRoutes };